### ISSUE TITLE
On Reconnection, unable to set client name right before resubscribing to channels

### ISSUE THREAD

**Issue by noriega3** [redis/node-redis#1172]
* **Version**: 2.6.3
* **Platform**: Ubuntu 16.14
* **Description**: 

In code, I am able to do a client setname right before I placed it into subscriber mode to track the name through a platform, **but** if the client reconnects.. the setname erases or I can't have noderedis set the client name at the in-between time before it reconnects to the channels.  

Note, this happens when I have **disable_resubscribing = false** 

The error it generates seems like its already in subscriber mode by the time I try to hook into the reconnection function through node when trying to do a client('setname')

```
 ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
 0|node-mul |     at parseError (/home/nodeuser/node_modules/redis-parser/lib/parser.js:167:12)
 0|node-mul |     at parseType (/home/nodeuser/node_modules/redis-parser/lib/parser.js:228:14)
```

It would be nice if it could or maybe inside the retry_strategy, i could do any commands before the subscribing of channels, or get the last client setname

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
@noriega3 I like the idea of having such a function

**Comment by rogerweb** [comment]
Have you guys figured out how to workaround this without the feature?

I'm on 2.8.0 and would like to keep my sub client named even after a re-connection.

Thanks.

**Comment by rogerweb** [comment]
I was able to work around this by setting `disable_resubscribing: true` and moving both the SETNAME and the SUBSCRIBE commands to the `connect` event handler, in that order.

Cheers.

**Comment by leibale** [comment]
see `name` [here](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md).
