### ISSUE TITLE
subscriptions of multiple channels returns latest channel only

### ISSUE THREAD

**Issue by hex7c0** [redis/node-redis#1188]
* **Version**: 2.6.3
* **Platform**: Node.js@7.3.0 macOS
* **Description**: data from `subscribe` callback with array of channels as argument, is a string with latest channel only

debug trace
```sh
Net read sm.sp.dev:6379 id 1
Redis server ready.
on_ready called sm.sp.dev:6379 id 1
Send sm.sp.dev:6379 id 1: *3
$9
subscribe
$21
home/garden/fountain2
$4
foobar

Net read sm.sp.dev:6379 id 1
subscribe home/garden/fountain2
subscribe foobar
``` 

redis-cli
```sh
127.0.0.1:6379> SUBSCRIBE me/garden/fountain2 foobar
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "me/garden/fountain2"
3) (integer) 1
1) "subscribe"
2) "foobar"
3) (integer) 2
```

code
```js
consumer.subscribe(['home/garden/fountain2', 'foobar'], function(err, res) {

  console.log(res); // foobar
});
```

It would be nice if it could returns an Array of specified channels

**Comment by BridgeAR** [comment]
This is a known issue and worked this way from the beginning on due to a faulty implementation. As this would be a BC I can not change this right away though. This is planned for v.3.

**Comment by hex7c0** [comment]
thank you
