### ISSUE TITLE
Return `hgetall` keys as buffer

### ISSUE THREAD

**Issue by silverwind** [redis/node-redis#1298]
* **Version**: 2.8.0
* **Platform**: Linux, Node v9.4.0
* **Description**: 

On `hgetall` with the `return_buffers` option set the module returns buffers for the hash values but not for the hash keys. If one needs those keys as buffers, one has to first undo [this toString()](https://github.com/NodeRedis/node_redis/blob/9bb1454ca183f4132dbec8d12d010f28303cdebd/lib/utils.js#L12), which obviously hurts performance.

I suggest an option to also return hash keys as buffers, maybe called `hash_key_buffers`. One obvious issue is that buffers cannot be used as object keys, so a new reply format like

````js
[
  [key1, value1],
  [key2, value2]
]
````

will be necessary.

**Comment by stockholmux** [comment]
To paraphrase: 
1) if you're using `return_buffers === true` then `hgetall` would produce something like:
```
[ 
   [key1_as_buffer, value1_as_buffer],
   [key2_as_buffer, value2_as_buffer],
   ...
]
```
Correct?

**Comment by silverwind** [comment]
Here's an example of how it currently works:

````js
const r = require('redis').createClient({return_buffers: true});
r.hset('buffertest', Buffer.from([0xca]), Buffer.from([0xfe]), () => {
  r.hgetall('buffertest', console.log);
});
```
It logs:
```
null { 'Ê': <Buffer fe> }
```
Ideally, the return value should be `[[<Buffer ca>],[<Buffer fe>]]`, but I don't think you want to break backward compatibilty, so that's why I was suggesting the option. The new return value could be done in a `replyToArray` util function and I think I can do a PR if this feature request gets approved.

**Comment by stockholmux** [comment]
@BridgeAR Thoughts?

**Comment by silverwind** [comment]
For anyone wondering, this can be achieved with ioredis: See https://github.com/luin/ioredis/pull/620.

**Comment by leibale** [comment]
You can use `sendCommand` with `returnBuffers`:

```javascript
client.sendCommand(['HGETALL', 'key'], {
  returnBuffers: true
});
```
