### ISSUE TITLE
README to include definitely supported versions of Redis Engine

### ISSUE THREAD

**Issue by zargold** [redis/node-redis#1391]
* **Version**: I want to make sure that the Library supports a Redis Engine Version of 5.0.
* **Platform**:  Linux Elastic Cache
* **Description**: I think the README could have a little table that shows different versions and the level of support of that engine and its features such as:

| redis version | Support | Tested |
| --- | --- | --- |
| 2.8.24 | Full | 
| 3.* | Full |
| 5.* | Full |

or maybe like 2
[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
Humm. I like where this is going, but the Redis landscape is fairly complex these days (vendor variants, modules, etc) - not sure something that simple would be effective. 

The other issue is that commands are actually managed by another project (redis-commands) - so we'd need to keep this updated even though the actual project hasn't changed.

Generally, I think it's needed but we need to have a more comprehensive statement on support.

**Comment by zargold** [comment]
well even if people just each contributed what version they're using and if it works with that I can start and say that at least set and connect work on 2.8.24 I could make a PR with a simple chart like that and other people could say which version they're using and it wouldn't be a definitive guide but you know similar to MDN it seems to be compatible with this. Not an end all be all, but if somebody at least said 5.0.0 worked for my purposes, then I'd be less scared to try it.

**Comment by BridgeAR** [comment]
I like the idea and even though it might be outdated as some point, it's still a good start. The documentation needs a general rework, so this could do for the meanwhile.

**Comment by leibale** [comment]
https://github.com/redis/node-redis#supported-redis-versions
