### ISSUE TITLE
Multi (transaction) queues up all the commands and keeps them in memory

### ISSUE THREAD

**Issue by ppatotski** [redis/node-redis#1419]
* **Version:** latest version
* **Platform:** any platform
* **Description:** It seems multi (transaction) mode queues up all the commands and keeps them in memory causing out of memory issue.

Is there a way to execute heavy transaction without keeping all the commands in memory?

**Comment by BridgeAR** [comment]
It is possible to set the [`CLIENT REPLY`](https://redis.io/commands/client-reply) to `off`. That way all commands are fire and forget commands until turned on again and if I remember correct nothing is kept in memory in that case anymore. Please give that a try.

**Comment by leibale** [comment]
You can take advantage of `.sendCommand` and do something like:

```javascript
await client.sendCommand(['MULTI']);
for (let i = 0; i < 10; i++) {
  await client.sendCommand(['SET', 'key', 'value']);
}
const replies = await client.sendCommand(['EXEC']);
```
