### ISSUE TITLE
Safer Redis reconnection behavior out of the box

### ISSUE THREAD

**Issue by mcandre** [redis/node-redis#1530]
### Issue

> Describe your issue here

The node-redis library offers several options for manually tuning how transactions and connections are retried, in the event that the Redis server experiences a brief outage / changes DNS records. Could more of these settings be turned on by default, so that Redis clients "just work"?

**Comment by stockholmux** [comment]
@mcandre I don't believe there is a "just work" setting as there are a way range of different deployments. Changing the default to "just works" for one person may be disruptive for others.

**Comment by leibale** [comment]
Some defaults have changed in v4 :)
