### ISSUE TITLE
RedisLabs cloud and "ReplyError: NOAUTH Authentication required" error

### ISSUE THREAD

**Issue by BassOfBass** [redis/node-redis#1541]
### Issue

I am using [RedisLabs](https://app.redislabs.com) cloud server to run a test project in which Redis connection looks like this:

```javascript
if (process.env.REDIS_URL) {
  var client = redis.createClient(process.env.REDIS_URL);  // creates a new redisClient
} else {
  const redisHost = process.env.REDIS_HOST || '127.0.0.1';
  const redisPort = process.env.REDIS_PORT || 6379;
  const redisPassword =  process.env.REDIS_PASSWORD || '';

  const options = {
    host: redisHost,
    port: redisPort
  };

  if (process.env.NODE_ENV == 'production') {
    options.password = redisPassword;
  }

  var client = redis.createClient(options);  // creates a new redisClient
}
```

I've provided the `Endpoint` URL as `REDIS_URL` and it works just fine, but then spews out `ReplyError: NOAUTH Authentication required` errors every now and then. After some digging I found out it is an error related to the lack of password or something. There is a `Default User Password` field in the cloud server, so I've inserted its value as `{ password: "string" }` `options` object in `createClient()`, but it hadn't get rid of the errors. Neither does `Endpoint` URL conform to the `options.url` format, so I don't know where to insert the password in there, if it's the right password in the first place.

### Environment

 - **Node.js Version**: 12.18.4
 - **Redis Version**: 6.0.5
 - **Platform**: Windows 7 actually, that's why I am using cloud version.

**Comment by ferasallaou** [comment]
@BassOfBass Any luck with this one, I've the same issue!

**Comment by BassOfBass** [comment]
@ferasallaou You have to insert `Database Name` and `Default User Password` values as `[user][:password@]` in the [`redis_url`](https://github.com/NodeRedis/node-redis#rediscreateclient) as [per `url` format](https://github.com/NodeRedis/node-redis#options-object-properties), so no `options` object in the end, at least for the url.
