### ISSUE TITLE
Client should autodetect IP version by default

### ISSUE THREAD

**Issue by zhaofengli** [redis/node-redis#1550]
### Issue

Currently, when using host names node-redis will [only attempt to resolve IPv4 addresses](https://github.com/NodeRedis/node-redis/blob/0041e3e53d5292b13d96ce076653c5b91b314fda/index.js#L67) by default. This is undesirable as apps using this library will have to provide an additional config option for the user to select the IP version apart from the `redis://` URI (none of them do), otherwise they will not be usable on IPv6-only environments like an IPv6-only Kubernetes cluster without being patched (that is, _all_ of them).

`node-redis` should use the `0` (auto) family when creating the connection so it works out of the box in IPv6-only environments, and not make a negative impact in our migration to an IPv6 world.

---

### Environment

 - **Node.js Version**: `N/A`
 

 - **Redis Version**: `N/A`
 

 - **Platform**: `N/A`

**Comment by leibale** [comment]
Fixed in v4
