### ISSUE TITLE
No documentation for commands with options

### ISSUE THREAD

**Issue by marcosmol204** [redis/node-redis#1561]
#ISSUE
There is not documentation for commands that can have options like SET.
SET key value [EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL] [NX|XX] [GET]
let's supose I want to create the following command
SET someKey someString EX 3153599 NX GET
const asyncSET = promisify(client.SET).bind(client);
const redisSET = async (key, value,options) => asyncSET(key, value, options);
what options should be ? an array? some strings? an object?
Please add documentation for cases like this.

**Comment by gionapaolini** [comment]
Any update on this? 
I'm looking for the same info

**Comment by DewZ89** [comment]
Any update ?

**Comment by ParkerOu** [comment]
https://github.com/redis/redis-doc/blob/master/commands/set.md

It looks like there is no way to use NX EX at the same time.

Also see: https://github.com/NodeRedis/node-redis/issues/1517

**Comment by joerg-walter-de** [comment]
[How to set AND get atomatically? Getting a sytax error](https://github.com/redis/node-redis/issues/1710)
