### ISSUE TITLE
xReadGroup not working on node redis

### ISSUE THREAD

**Issue by chiragkhanna28** [redis/node-redis#1608]
Hi Team,

We tried to read data using xreadgroup on redis using node but we are getting below issue:

rc.XREADGROUP('GROUP', 'PredectionsGroup', 'consuemr:1', 'Block', 2000,'STREAMS', 'predections', '>', function (err: any, stream: any) {})

**Exception** coming is 'ERR Unbalanced XREAD list of streams: for each stream key an ID or '$' must be specified.'

Can you please help us on the same as early as possible.

Regards,
Chirag Khanna

**Comment by simonprickett** [comment]
@chiragkhanna28 we've added an example of how to use `XREADGROUP` in node-redis 4 here: https://github.com/redis/node-redis/blob/master/examples/stream-consumer-group.js
