### ISSUE TITLE
Connect multiple Redis Server

### ISSUE THREAD

**Issue by rupamking1** [redis/node-redis#1622]
How to connect multiple Redis server and One set update both data, I means multiple Cluster update or Read same time or Subscribe same time,
How that will possible with your Package?
Please tell me

**Comment by NovaAtWarren** [comment]
Trying to make sure I know what you're asking. Are you
1. Trying to set up a Redis cluster, and connect to it
2. Trying to connect to multiple separate Redis instances
3. Something else entirely

**Comment by leibale** [comment]
If you're still having problems feel free to reopen the issue.
