### ISSUE TITLE
Monitor mode clarification

### ISSUE THREAD

**Issue by basaran** [redis/node-redis#1627]
### Issue

I was reviewing some old code base, and I encountered an issue while using redis-client with monitoring enabled from a recent yarn install of the old code base. Please allow me to clarify.

This is working fine:

```js
const redisClient = require("redis").createClient();
redisClient.set("oodoo_rand000000000000", "OK");
```

This is throwing an error. I'm 99% sure this used to work at some point last year. Basically adding monitor to the client and trying to set something afterwards.

```js
const redisClient = require("redis").createClient();

redisClient.monitor(function (err, res) {
    debug("enabling redis client monitor");
});

redisClient.on("monitor", (time, args, rawReply) => {
    debug(time + ": " + args);
});

redisClient.set("oodoo_rand000000000000", "OK");
```

Gives of the following error:

```
error ERR Replica can't interract with the keyspace 
```

I just wanted to clarify, if one is expected to use a different clients for monitoring and setting. If so, we should probably have this stated in the docs.

---

### Environment

 - **Node.js Version**: 16
 

 - **Redis Version**: 6.2.4
 

 - **Platform**: Arch (Manjaro)

**Comment by NovaAtWarren** [comment]
Redis doesn't tend to like interacting while monitoring:
```
# nc localhost 6379
monitor
+OK
set a b
-ERR Replica can't interract with the keyspace
```
If you want to do this you'll likely have to create 2 `redisClient`s, using one to monitor and the other to interact with the data.

**Comment by leibale** [comment]
+1 to @NovaAtWarren commant.

BTW, you can use `client.duplicate()` to duplicate a connection with the settings.

```javascript
const redisMonitor = Redis.createClient(),
    redisClient = redisMonitor.duplicate();
```

**Comment by basaran** [comment]
Thank you both for the clarifications. Perhaps this should be added to the docs?

**Comment by HeCorr** [comment]
Hello! Isn't the [Isolated Execution](https://github.com/redis/node-redis/blob/master/docs/isolated-execution.md) appropriated for this use-case (instead of `duplicate()`)?

Unless I misunderstood how `executeIsolated()` works.

**Comment by MR4online** [comment]
@leibale in the related Pull-request you mention that "this is not relevant anymore". Well, how can I monitor / debug / log the Redis requests made by node-redis?
None of the terms above occurr in the very compact Readme.md
Are there any "real" docs I didn't found?
Thanks a lot!

**Comment by leibale** [comment]
@MR4online the `MONITOR` command is not supported by the client, that's why it's not relevant anymore.. BTW, `MONITOR` would not help you debug a specific client, as it monitors all the commands on the server, not just the one that was executed by the "current" client..

**Comment by leibale** [comment]
We don't support v3 anymore
