### ISSUE TITLE
How to close out a connection?

### ISSUE THREAD

**Issue by a-koka** [redis/node-redis#1663]
### Issue

There doesn't seem to be an API to close out a created connection. Is there?

**Comment by a-koka** [comment]
I see that there is a `quit` method available in the library. Would be nice to update the documentation with this.

**Comment by madelineurl** [comment]
@a-koka There's also now an asynchronous client.disconnect() method- had to dig into the codebase to find this though. Agree the new API should be better documented

**Comment by a-koka** [comment]
I see the update in the documentation but I'm getting a `disconnect is not a function` error when using version `3.1.2`.

**Comment by leibale** [comment]
@a-koka checkout the [v3.1 branch](https://github.com/redis/node-redis/tree/v3.1) to see the v3 docs

**Comment by leibale** [comment]
https://github.com/redis/node-redis#disconnecting
