### ISSUE TITLE
HSET cannot use - syntax error

### ISSUE THREAD

**Issue by fdsagizi** [redis/node-redis#1672]
Hi bro, i cannot use client.HSET because, syntax error:
<img width="1023" alt="Снимок экрана 2021-10-07 в 14 12 58" src="https://user-images.githubusercontent.com/6450420/136348773-3db13d41-c095-4a92-878b-e9fb9cb6b88b.png">

client.SET work normal

**Environment:**
 - **Node.js 14 LTS
 - **Platform**:

**Comment by leibale** [comment]
It works for me in both VSCode and WebStorm. Please try to upgrade your idea, and make sure that it uses the latest typescript version (4.4.3).
