### ISSUE TITLE
Export TypeScript types from package

### ISSUE THREAD

**Issue by sgoll** [redis/node-redis#1673]
For the recent version 4, the `redis` package includes TypeScript types but so far only the signatures of `createClient()`, `commandOptions()`, and `createCluster()` are exported (i.e. exported explicitly by name).

This makes it more difficult than necessary to use objects of the "public" types in custom code, such as:

```ts
class SomeClass {
  // Unable to declare this attribute:
  private redisClient: RedisClientType;
}
```

One workaround is to infer the types from the exported signatures:

```ts
// You _can_ get the type like this but this is hard to do for all types:
type RedisClientType = typeof redis.createClient extends () => infer ResultType
  ? ResultType
  : never;
```

I would suggest that `index.ts` should include at least exports of the most common types such as `RedisClientType`, `RedisClientOptions`, `RedisClusterType`, `RedisClusterOptions`, `TuplesObject`, option types for commands etc.

The only downside to this is that these types now form the public interface of the package API, i.e. may introduce breaking changes if later removed or renamed.

**Comment by leibale** [comment]
`RedisClient/RedisClientType` and `RedisCluster/RedisClusterType` can be extended with Redis modules & Lua Scripts, therefore in most cases the [`typeof`](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html) operator is a better solution:

```typescript
import { createClient } from '@node-redis/client';

export const client = createClient();

export type RedisClientType = typeof client;
```

**Comment by realpha** [comment]
Although I would also be in favor of exporting the client types directly instead of providing work arounds, the following also works if you can't/wont instantiate the client to obtain the interface:
```ts
import { createClient } from 'redis';

export type RedisClientType = ReturnType<typeof createClient>;
```

**Comment by jamesarosen** [comment]
I had to also explicitly coerce the result of `createClient` to `RedisClientType`:
```ts
export type RedisClientType = ReturnType<typeof createClient>

export default async function start(): Promise<RedisClientType> {
  const redis: RedisClientType = createClient({ url: … })
  await redis.connect()
  return redis
}
```

**Comment by jasontibbetts** [comment]
And how would you infer the type of RedisClientOptions? Use case being options passed into a function to initialize redis from a config vs hardcoded in code.

**Comment by tbinna** [comment]
The `RedisClientType` exported since 4.0.1 still does not work for me. Could not figure out how to make the exported `RedisClientType`, `RedisClientOptions` and the type returned by `createClient` compatible. Here is an [example that illustrates the issue](https://codesandbox.io/s/node-redis-typescript-fhzck).

The following does not compile unless someone knows how to type `RedisClientOptions` correctly (refer to the code sandbox link above).

```
import { createClient, RedisClientOptions, RedisClientType } from "redis";

const factory = (options: RedisClientOptions<any, any>): RedisClientType => {
  return createClient(options);
};

const client: RedisClientType = factory({...});
```

Instead, I am doing this for now:

```
import { createClient} from "redis";
type RedisClientType = ReturnType<typeof createClient>;
type RedisClientOptions = Parameters<typeof createClient>[0];

const factory = (options: RedisClientOptions): RedisClientType => {
  return createClient(options);
};

const client: RedisClientType = factory({...});
```
