### ISSUE TITLE
scanIterator ReplyError: ERR syntax error

### ISSUE THREAD

**Issue by myartings** [redis/node-redis#1691]
**Environment:**
 - **Node.js Version**: 
 - **Redis Server Version**: 
 - **Node Redis Version**: 
 - **Platform**: 

   
` const scanOptions = {
      TYPE: "string",
      MATCH: "patter*",
      COUNT: 100,
    };
    for await (const key of client.scanIterator(scanOptions)) {
      // use the key!
      await client.get(key);
    }`

(node:22144) UnhandledPromiseRejectionWarning: ReplyError: ERR syntax error
    at parseError (Z:\Dev\NodeJs\namingserver\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (Z:\Dev\NodeJs\namingserver\node_modules\redis-parser\lib\parser.js:302:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leibale** [comment]
@myartings which version of Redis (the server, not the client) are you using?

**Comment by myartings** [comment]
> @myartings which version of Redis (the server, not the client) are you using?

v14.18.1

**Comment by leibale** [comment]
@myartings `14.18.1` is prob the Node version, I'm talking about the `redis-server` version..

**Comment by myartings** [comment]
> @myartings `14.18.1` is prob the Node version, I'm talking about the `redis-server` version (because the `TYPE` option was added in Redis `6.0.0`)..

redis-6.2.6

**Comment by leibale** [comment]
Hi, does the issue still exists in `redis@4.0.0-rc.4` or `@node-redis/client@1.0.0-rc.0`?

**Comment by hezbymuhammad** [comment]
@leibale I got exactly the same issue. I'm using:
- node redis `redis@4.0.1`
- redis server `redis_version:5.0.6`

Do you have any suggestion on how to use `scanIterator` with redis 5?
Thanks!

**Comment by hezbymuhammad** [comment]
The the easiest thing to do is removing `TYPE` from readme. I can help create PR for it. Let me know what you think 🙏
