### ISSUE TITLE
[Documentation] node-redis 3.0.2 supports which versions of redis

### ISSUE THREAD

**Issue by cicadaDroid** [redis/node-redis#1702]
Hi,
Can anyone help me in confirming node-redis v3.0.2 supports till which redis version.
To be more specific does it supports redis v6.x ?

**P.S** : I couldn't find any information regarding this in documentation so had to post it here.

**Environment:**
 - **Node.js Version**: 8.17.0
 - **Redis Server Version**: 6.x
 - **Node Redis Version**: 3.0.2
 - **Platform**: Ubuntu

**Comment by leibale** [comment]
@cicadaDroid
1. Connecting using ACL username & password was added in v3.1.0.
2. v3 relies on a package called "redis-commands" to add all the commands functions, Redis 6 commands were added in `redis-commands@1.6.0`, Redis 6.2 commands were added in `redis-commands@1.7.0`. You can upgrade the "redis-commands" without upgrading the client itself (`npm install redis-commands@1.7.0`).
3. You can always use `client.sendCommand('', '', ...)` to execute commands that are "not supported" by the client
