### ISSUE TITLE
Redis property `ready` not defined in the interface

### ISSUE THREAD

**Issue by szygendab** [redis/node-redis#1703]
I'm trying to access property `ready` of Redis client but Typescript returns an error that this property was not defined in the interface.

![redis client structure](https://user-images.githubusercontent.com/78420305/139389351-69d7684b-1475-40ac-a3c5-9948d50c9adc.png)
![console error](https://user-images.githubusercontent.com/78420305/139389394-12c2aaac-6751-4243-94d5-5e7966a7e401.png)

**Environment:**
 - **Node.js Version**:  14.x
 - **Redis Server Version**: 6.x
 - **Node Redis Version**:  3.1.2
 - **Platform**: MacOS

**Comment by leibale** [comment]
Hi @szygendab, are you using `@types/redis`? If you are, you may submit an issue [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redis).
