### ISSUE TITLE
Sorted set - from the highest to the lowest score

### ISSUE THREAD

**Issue by petermasica** [redis/node-redis#1705]
redis server: docker image `redis:latest`
npm package: v4 version installed with `npm install redis@next`

Hi, I added a few entries to the set
```
await redisClient.zAdd('test', {
    score: 1,
    value: 'a',
  });

await redisClient.zAdd('test', {
    score: 2,
    value: 'b',
  });

 await redisClient.zAdd('test', {
    score: 3,
    value: 'c',
  });
```

The following query gets me this `[ 'a', 'b', 'c' ]` which is OK.
```
let result = await redisClient.zRange('test', 0, -1);
console.log('result', result);
```

However, I need to get the items in reversed order by score, but I don't know how to do it. I tried the following
```
result = await redisClient.zRange('test', '-inf', '+inf', {
    BY: 'SCORE',
    REV: true,
  });
console.log('result', result);
```
but it gets me an empty array. Can you pls help? Thanks

**Comment by khashayar** [comment]
You are doing it correctly, except that when you specify the `REV: true` then you have to reverse the max & min as following:

```javascript
redisClient.zRange('test', '+inf', '-inf', {
  BY: 'SCORE',
  REV: true
});
```

**Comment by petermasica** [comment]
Thanks a lot :) Btw, is it possible to also retrieve scores with `zRange` function call? I'm not that familiar with typecript, but digging into the source code a little bit it seems like the `options` object can only be configured with `by`, `rev` and `limit` keywords.

**Comment by khashayar** [comment]
Sure... You can get the scores like this:
```javascript
await redisClient.zRangeWithScores('test', '+inf', '-inf', {
    BY: 'SCORE',
    REV: true
  });
```

**Comment by petermasica** [comment]
Instead, I was thinking about the possibility of using the very same `zRange` function with different arguments, something like `{ WITHSCORES: true }`. I was thinking something like that might work because when reading through redis documentation it looks like the `ZRANGE` command can replace many  other commands such as  `ZREVRANGE, ZRANGEBYSCORE, ZREVRANGEBYSCORE`, etc. and you can use this `zrange test +inf -inf BYSCORE REV WITHSCORES` when using the client that comes with redis by default  ... but that's probably not possible here.

One more thing, when speaking about `zRangeWithScores` how do you even know that such a function exists? I couldn't find any api documentation. Do you just rely on the methods and properties shown by IDE?

**Comment by leibale** [comment]
`zRangeWithScores/ZRANGE_WITHSCORES` is actually executing a `ZRANGE` command, but because the `WITHSCORES` argument changes the reply type (from `Array<string>`  to `Array<{ score: number, member: string }>`), it's implemented as a different command.

```typescript
await redisClient.zRange('test', '+inf', '-inf', {
  BY: 'SCORE',
  REV: true
}); // `ZRANGE test +inf -inf BY SCORE REV`

await redisClient.zRangeWithScores('test', '+inf', '-inf', {
  BY: 'SCORE',
  REV: true
}); // `ZRANGE test +inf -inf BY SCORE REV WITHSCORES`
```

Regarding what commands exist - you can totally trust the IDE - it's generating the suggestions based on the package TypeScript declaration files. On top of that, you can alwayes check the [repo wiki](https://github.com/redis/node-redis/wiki).

**Comment by petermasica** [comment]
Thank you guys for your guidance.

**Comment by drahnieR** [comment]
@leibale I feel like this should be documented somewhere (maybe there was but I don't the wiki is available anymore). Is it possible to put it in the readme page?

**Comment by leibale** [comment]
@drahnieR Wanna add the examples into the [examples folder](https://github.com/redis/node-redis/tree/master/examples)?
Regarding the wiki - see the "documentation" links under the [packages section in the main README](https://github.com/redis/node-redis/tree/master#packages).

**Comment by drahnieR** [comment]
@leibale OK, I missed that "documentation" button in the package session, it looks too similar to the stats badge at side, just my POV. The doc itself is good enough to me.

**Comment by simonprickett** [comment]
I'm amending the existing sorted set example script in the `examples` folder to show this.
