### ISSUE TITLE
How to set AND get atomatically? Getting a sytax error

### ISSUE THREAD

**Issue by joerg-walter-de** [redis/node-redis#1710]
I haven't found a documentation of the usage of command modifiers in node-redis.
My intention is to SET and GET atomically (as with the SETGET command).

My code:

```
    let x = await client.set('semaphore', '1', { EX: 1, GET: true });
```
I get a syntax error - apparently because my command modifier syntax is not correct.

Where is the error?

**Comment by joerg-walter-de** [comment]
[https://github.com/redis/node-redis/issues/1710](url)

**Comment by khashayar** [comment]
What's the error that you are receiving?

I'm running the following code and it works fine for me
```javascript
const result = await client.set('name', 'John', { EX: 10, GET: true });
```

Are you sure that the `semaphore` key was empty before and a value other that string is not save at this key. I am asking because, in that case, an error is returned and `SET` is aborted if the value stored at key is not a string.

**Comment by joerg-walter-de** [comment]
Version: node-redis 4.0.0-rc.3

**Comment by joerg-walter-de** [comment]
> ```js
> const result = await client.set('name', 'John', { EX: 10, GET: true });
> ```

Just ran your code:

![image](https://user-images.githubusercontent.com/33499391/140496875-2ca76e5b-f9b9-445f-a9cc-191ee08c8f02.png)

**Comment by joerg-walter-de** [comment]
result of client.info():

`"# Server\r\nredis_version:3.0.504\r\nredis_git_sha1:00000000\r\nredis_git_dirty:0\r\nredis_build_id:a4f7a6e86f2d60b3\r\nredis_mode:standalone\r\nos:Windows  \r\narch_bits:64\r\nmultiplexing_api:WinSock_IOCP\r\nprocess_id:30948\r\nrun_id:2b5ed1840df94cd4c71aea14dbd39258c3105d5d\r\ntcp_port:6379\r\nuptime_in_seconds:72238\r\nuptime_in_days:0\r\nhz:10\r\nlru_clock:8718534\r\nconfig_file:C:\\Program Files\\Redis\\redis.windows-service.conf\r\n\r\n# Clients\r\nconnected_clients:1\r\nclient_longest_output_list:0\r\nclient_biggest_input_buf:0\r\nblocked_clients:0\r\n\r\n# Memory\r\nused_memory:692352\r\nused_memory_human:676.13K\r\nused_memory_rss:654600\r\nused_memory_peak:693104\r\nused_memory_peak_human:676.86K\r\nused_memory_lua:36864\r\nmem_fragmentation_ratio:0.95\r\nmem_allocator:jemalloc-3.6.0\r\n\r\n# Persistence\r\nloading:0\r\nrdb_changes_since_last_save:8\r\nrdb_bgsave_in_progress:0\r\nrdb_last_save_time:1636108089\r\nrdb_last_bgsave_status:ok\r\nrdb_last_bgsave_time_sec:0\r\nrdb_current_bgsave_time_sec:-1\r\naof_enabled:0\r\naof_rewrite_in_progress:0\r\naof_rewrite_scheduled:0\r\naof_last_rewrite_time_sec:-1\r\naof_current_rewrite_time_sec:-1\r\naof_last_bgrewrite_status:ok\r\naof_last_write_status:ok\r\n\r\n# Stats\r\ntotal_connections_received:14\r\ntotal_commands_processed:63\r\ninstantaneous_ops_per_sec:1\r\ntotal_net_input_bytes:2152\r\ntotal_net_output_bytes:2310\r\ninstantaneous_input_kbps:0.03\r\ninstantaneous_output_kbps:0.01\r\nrejected_connections:0\r\nsync_full:0\r\nsync_partial_ok:0\r\nsync_partial_err:0\r\nexpired_keys:13\r\nevicted_keys:0\r\nkeyspace_hits:38\r\nkeyspace_misses:11\r\npubsub_channels:0\r\npubsub_patterns:0\r\nlatest_fork_usec:3318\r\nmigrate_cached_sockets:0\r\n\r\n# Replication\r\nrole:master\r\nconnected_slaves:0\r\nmaster_repl_offset:0\r\nrepl_backlog_active:0\r\nrepl_backlog_size:1048576\r\nrepl_backlog_first_byte_offset:0\r\nrepl_backlog_histlen:0\r\n\r\n# CPU\r\nused_cpu_sys:0.52\r\nused_cpu_user:0.92\r\nused_cpu_sys_children:0.00\r\nused_cpu_user_children:0.00\r\n\r\n# Cluster\r\ncluster_enabled:0\r\n\r\n# Keyspace\r\ndb0:keys=3,expires=1,avg_ttl=1424\r\n"`

**Comment by khashayar** [comment]
What is your version of Redis? The `GET` option was added in Redis 6.2

**Comment by joerg-walter-de** [comment]
3.0.504. OK, it is way too old. Sorry about that

**Comment by khashayar** [comment]
In that case you can use the `GETSET` command with the Redis version below 6.2 but be aware that `GETSET` command is deprecated from 6.2 on.

```javascript
const result = await client.getSet('name', 'John');
```

**Comment by joerg-walter-de** [comment]
> In that case you can use the `GETSET` command with the Redis version below 6.2 but be aware that `GETSET` command is deprecated from 6.2 on.
> 
> ```js
> const result = await client.getSet('name', 'John');
> ```

Yeah, already saw and used that. But it seems that I cannot combine that with the ex modifier. Working:

```
    [error, x] = await to ( client.getSet('id', '1') );
    [expireError, expireResult] = await to ( client.expire('id', 3 ) ); // 3 sec
```
