### ISSUE TITLE
scanStream is not working with database number even though the client specifies it

### ISSUE THREAD

**Issue by slidenerd** [redis/node-redis#1713]
**Environment:**
 - **Node.js Version**: v14.18.1
 - **Redis Server Version**: Redis server v=6.2.6 sha=00000000:0 malloc=libc bits=64 build=c6f3693d1aced7d9
 - **Node IORedis Version**: ioredis@4.28.0
 - **Platform**: Mac OS 12.0.1 (21A559) Apple M1

*How to reproduce*
```
var Redis = require('ioredis');
var connection = {database: 5, host: 'localhost', port: 6379, password: 'pwd'};
var client = new Redis(connection);
var stream = client.scanStream('');
stream.on('data', console.log);
```

It loads all the keys from database 0 instead of 5

**Comment by leibale** [comment]
https://github.com/luin/ioredis/issues
