### ISSUE TITLE
Pub/sub with binary in v4

### ISSUE THREAD

**Issue by darrachequesne** [redis/node-redis#1718]
Hi! Is it possible to send binary content with PUB/SUB in v4?

```js
const { createClient } = require("redis");

(async () => {
  const client = createClient();
  await client.connect();

  const subscriber = client.duplicate();
  await subscriber.connect();

  await subscriber.subscribe("channel", (message, channel) => {
    console.log(Buffer.from(message, "utf8")); // prints "<Buffer ef bf bd ef bf bd ef bf bd>"
  });

  client.publish("channel", Buffer.from([0xa1, 0xa2, 0xa3]));

})();
```

`message` is typed as string here:

https://github.com/redis/node-redis/blob/f93e28f8f2439a19bade4491903f5227848fd3bc/packages/client/lib/client/commands-queue.ts#L38

And it seems we have no control over the `setReturnBuffers()` here:

https://github.com/redis/node-redis/blob/f93e28f8f2439a19bade4491903f5227848fd3bc/packages/client/lib/client/commands-queue.ts#L268

Thanks in advance!

**Environment:**
 - **Node.js Version**: `v12.9.0`
 - **Redis Server Version**: `5.0.9`
 - **Node Redis Version**: `4.0.0-rc.3`
 - **Platform**: `Ubuntu 20.04.3`

**Comment by leibale** [comment]
The support for binary messages was mistakenly removed, I'll add it back this week

**Comment by leibale** [comment]
@chayim

**Comment by leibale** [comment]
Hi @darrachequesne, I've just added support for buffers, if you can test it will be very helpful.. :) (if you need help with building the project let me know)

**Comment by darrachequesne** [comment]
@leibale it works!

```js
const { createClient } = require("redis");

(async () => {
  const client = createClient();
  await client.connect();

  const subscriber = client.duplicate();
  await subscriber.connect();

  await subscriber.subscribe("channel", (message, channel) => {
    console.log(message); // prints "<Buffer a1 a2 a3>"
  }, true);

  client.publish("channel", Buffer.from([0xa1, 0xa2, 0xa3]));

})();
```

Thanks a lot for fixing it this quickly :+1: 

A minor nitpick: the boolean argument at the end of the `subscribe` method is a bit disturbing to me, would it make sense to always return a buffer and let the user decide whether to call `toString()`?

**Comment by leibale** [comment]
@darrachequesne I agree that the boolean is a little bit confusing, but I also think that most of the users expect to get a string, and not everyone is comfortable with using buffers...
