### ISSUE TITLE
Redis cluster connection issue

### ISSUE THREAD

**Issue by tiwariprateek** [redis/node-redis#1719]
Hi,
I was trying to establish a connection to redis cluster, using createCluster(). But was not able to. Following was the error returned :
ReplyError: NOAUTH Authentication required.
at parseError (/redis-parser/lib/parser.js:179:12)
at parseType (/redis-parser/lib/parser.js:302:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:89375) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Also, I have verified the connection string and there is no issue in terms of that. Here's the code snippet.
(async () => {
    const cluster = createCluster({
      rootNodes: [
        {
          url: 'redis://:CLUSTER_PASSWORD@CLUSTER_IP:CLUSTER_PORT'
        }
      ]
    });
  
    cluster.on('error', (err) => console.log('Redis Cluster Error', err));
    cluster.on('connect', () => {
        console.log("Redis client connected. RedisHost");
      });
    await cluster.connect();
  })();

**Comment by leibale** [comment]
specifying the password in the URL or a root node will only affect the connection to that specific node. In case you want to set the password for all the connections being created from a cluster instance - use the `defaults` option:
```javascript
const cluster = createCluster({
  rootNodes: [{
    url: 'redis://CLUSTER_IP:CLUSTER_PORT'
  }]
}, {
  defaults: {
    password: 'CLUTSER_PASSWORD'
  }
});

**Comment by yangbodong22011** [comment]
Following the workaround above, I still get the NOAUTH error

1. start redis cluster at 7379, 7380, 7381

2. vim rediscluster.mjs
```
import { createCluster } from 'redis';

const cluster = createCluster({
  rootNodes: [{
      url: 'redis://default:cluster@localhost:7379'
  }]
}, {
  defaults: {
    username: 'default',
    password: 'cluster'
  }
});

cluster.on('error', (err) => console.log('Redis Cluster Error', err));

await cluster.connect();

await cluster.set('key', 'value');
const value = await cluster.get('key');
console.log("get key: %s", value);

await cluster.disconnect();
```

3.
```
$ node --experimental-modules rediscluster.mjs
node:internal/process/esm_loader:79
    internalBinding('errors').triggerUncaughtException(
                              ^

[ErrorReply: NOAUTH Authentication required.]

Node.js v19.4.0
```

**Comment by leibale** [comment]
@yangbodong22011 I fixed the example above. This should work:

```javascript
const cluster = createCluster({
  rootNodes: [{
      url: 'redis://default:cluster@localhost:7379'
  }],
  defaults: {
    username: 'default',
    password: 'cluster'
  }
});
```

**Comment by yangbodong22011** [comment]
@leibale thank you very much, it worked. my new code is:
```
import { createCluster } from 'redis';

const cluster = createCluster({
  rootNodes: [{
      url: 'redis://default:cluster@localhost:7379'
  }],
  defaults: {
      username: 'default',
      password: 'cluster'
 }
});

cluster.on('error', (err) => console.log('Redis Cluster Error', err));

await cluster.connect();

await cluster.set('key', 'value');
const value = await cluster.get('key');
console.log("get key: %s", value);

await cluster.disconnect();
```
