### ISSUE TITLE
node-redis latest version nto working with connect-redis ..........req.session coming undefined

### ISSUE THREAD

**Issue by rukmanidevi-bh** [redis/node-redis#1725]
I am using connect- redis  to store  session variables , whoch requires a redis client instance, with node-redis version 3.2.0 it was working fine . but with redis@next , it is giving req.session undefined.

**Environment:**
 - **Node.js Version**: 14
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**:  redis@next
 - **Platform**: win10
here is my code:
`import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const express = require('express');
const session = require('express-session');
const app = express();
import { createClient } from 'redis';
const redisStore = require('connect-redis')(session);

const port = process.env.PORT || 8030;
const config= {
      "host":"127.0.0.1",
      "port":6379,
      "username":"",
      "password":"test"
      };

 
     
 
  async function setupsession(){
//   const client = await createClient({ url: 'redis://default:test@127.0.0.1:6379'});
   const client = await createClient({ ...config});
    client.on('error', (err) => console.log('Redis Client Error', err));
  
    await client.connect();
	
	
   app.use(session({
      secret: 'top_secrect_react_app_hub',
      name: 'local.cookie',
      proxy: true,
      resave: false,
      saveUninitialized: true,
      cookie: { 
        secure: true,
        httpOnly: true
      },
     store: new redisStore({ client:client}),
    }
    ));
	

    await client.set('age', '31');
    await client.set('field1', 'value1');
     await client.set( 'field2', 'value2');
     await client.hSet('myhash', 'field1', "Hello");
  
   const val=await client.hGetAll('myhash');
    const value = await client.get('field1');
    console.log(value);
    console.log(val);
    const [ping, get, quit] = await Promise.all([
    client.ping(),
    client.get('key1'),
    //client.quit()
  ]); // ['PONG', null, 'OK']
  console.log(ping,get,quit);
  try {
    await client.get('key');
  } catch (err) {
    // ClosedClient Error
    console.log(err);
  }
  }
  
    app.get('/', function (req, res) {
		 req.session.test="new";
			   req.session.save();
			   res.send('server started');
			  
		
	});
	app.get('/rbac', function (req, res) {
			   req.session.expiresOn = 'test stored';
		
	});
	setupsession();
var server = app.listen(port, function() {
	console.log(`Server started on PORT ${port}`);
	
});`

**Comment by leibale** [comment]
`connect-redis` expect redis client to support callbacks, which v4.0.0 does not support by default. You should:
1. Open this issue under the `connect-redis` repo
2. Try to use the legacy mode until then
