### ISSUE TITLE
in node-redis @next version password with special characters like @ are giving auth error due to percent encoding

### ISSUE THREAD

**Issue by rukmanidevi-bh** [redis/node-redis#1728]
in create client my **password** is **Rukm@ni23** and **username** is **alice**.
but auth is failing when m passing this to create client.
when i checked redis-cli of server it was getting : AUTH alice Rukm%40ni 
and hence i get wrong username password error.
how can i prevent enocding of special characters.
it seems node redis doing oit by default.

`  const client = createClient({ url: 'redis://alice:Rukm@ni23@redis-135678.89.334.cloud.redislabs.com:12312'});`

**Comment by leibale** [comment]
the username and password in the url should be encoded using `encodeURIComponent`:
```javascript
const client = createClient({ url: `redis://${encodeURIComponent('alice'):${encodeURIComponent('Rukm@ni23')}@redis-135678.89.334.cloud.redislabs.com:12312` });
```
another way is to use the `username` and `password` properties instead:
```javascript
const client = createClient({
  url: `redis://redis-135678.89.334.cloud.redislabs.com:12312`,
  username: 'alice',
  password: 'Rukm@ni23'
});
```
