### ISSUE TITLE
Events not triggering in v4

### ISSUE THREAD

**Issue by adriaanmeuris** [redis/node-redis#1731]
In `v3.x.x` we could subscribe to client events:
```js
  client.on('connect', () => { connected = true; });
  client.on('reconnecting', () => { connected = false; });
  client.on('end', () => { connected = false; });
  client.on('error', err => console.error(`Redis error: ${err.message}`));
  client.on('warning', err => console.error(`Redis warning: ${err.message()}`));
```

It seems these are not triggered anymore. The migration guide has no information on whether this has changed.
How can we subscribe to these events in `v4.0.0`?

**Environment:**
 - **Node.js Version**: `16.13.0`
 - **Redis Server Version**: `6.0`
 - **Node Redis Version**: `4.0.0`
 - **Platform**: `Debian buster`

**Comment by huineng** [comment]
for this works , have you added 

await client.connect(); ?

**Comment by adriaanmeuris** [comment]
no, afaik that wasn't necessary in v3 and did not found that in the migration guide. But it did the trick. Thanks!
