### ISSUE TITLE
Unable to run redis in docker with node.js 8 

### ISSUE THREAD

**Issue by dipenappscrip** [redis/node-redis#1735]
**Environment:**
 - **Node.js Version**: 8
 - **Redis Server Version**: 
 - **Node Redis Version**: 4.0.0
 - **Platform**: docker
 
 I am getting following issue
 node_modules/@node-redis/client/dist/lib/client/index.js:237
 async *scanIterator(options) {
 
 SyntaxError: Unexpected token *

**Comment by huineng** [comment]
i think async iterators are supported since node 10

**Comment by leibale** [comment]
v4.0.0 is tested with node 12 and up (the oldest active LTS node version), and as @huineng said, async iterators are only supported since node v10.0.0.
