### ISSUE TITLE
redis json not working

### ISSUE THREAD

**Issue by hoangphongdhhp** [redis/node-redis#1736]
(node:7664) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command `JSON.GET`, with args beginning with: `keyUser:noderedis:jsondata`, `.pets[1].name`, `.pets[1].age`, 
    at parseError (E:\myG\con-thong-minh-server-dt\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\myG\con-thong-minh-server-dt\node_modules\redis-parser\lib\parser.js:302:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Environment:**
 - **Node.js Version**:  v14
 - **Redis Server Version**: 6.2.6 
 - **Node Redis Version**:  4.0.0
 - **Platform**: centos 7

**Comment by leibale** [comment]
It seems like Redis JSON is not installed on your redis-server

**Comment by hoangphongdhhp** [comment]
Looks like it, can you help me install RedisJSON? i tried following this tutorial: https://github.com/RedisJSON/RedisJSON but i have no way to get the librejson.so file can someone help me

**Comment by leibale** [comment]
Hi @hoangphongdhhp, what do you mean by "i have no way to get the librejson.so"?

**Comment by leibale** [comment]
You have 3 options:
1. https://app.redislabs.com/#/rlec-downloads
2. use the `redislabs/rejson` docker
3. [build it yourself](https://github.com/RedisJSON/RedisJSON#build)

**Comment by Preen** [comment]
I dont understand this... is it a requirement to have redis json installed in order to use this lib?
