### ISSUE TITLE
HMSET under v4 doesn't work. HSET does

### ISSUE THREAD

**Issue by BarryCarlyon** [redis/node-redis#1746]
HMSET does not seem to be supported

I have to resort to `sendcommand` instead?

```javascript
                redis_client.HMSET(
                    'test_key',
                    'some_key',
                    'some_value',
                    'another_key',
                    'another_value'
                )
                .then(r => {
                    console.log(r);
                })
                .catch(e => {
                    console.error(e);
                });
```

and

```javascript
                let r = await redis_client.HMSET(
                    'test_key',
                    'some_key',
                    'some_value',
                    'another_key',
                    'another_value'
                )
```

Results in

```
                redis_client.HMSET(
                             ^

TypeError: redis_client.HMSET is not a function
```

Additionally, after

> 127.0.0.1:6379> hset test_key some_key a another_key thing

HMGET can't get multiple keys?

```
                let ra = await redis_client.HMGET(
                    'test_key',
                    'some_key',
                    'some_value',
                    'another_key',
                    'another_value'
                )
                console.log(ra);
```

results in

```json
[ 'a' ]
```
Or is this a case of "node redis doesn't know about this yet" but it did in the last v3 version?

**Environment:**
 - **Node.js Version**: v16.9.0
 - **Redis Server Version**: v=6.2.6 sha=00000000:0 malloc=libc bits=64 build=c6f3693d1aced7
 - **Node Redis Version**: redis@4.0.0
 - **Platform**: Mac 12.0.1

**Comment by leibale** [comment]
`HMSET` is deprecated since redis 4.0.0, you can use `HSET` to set multiple fields as well:
```javascript
// with an object
client.HMSET('key', {
  field1: 'value1',
  field2: 'value2'
});

// with flat array
client.HMSET('key', ['field1', 'value1', 'field2', 'value2']);

// with tuples
client.HMSET('key', [['field1', 'value1'], ['field2', 'value2']]);
```

for `MGET`, instead of passing the field names as multiple arguments, pass them as an array:
```javascript
client.HMGET('key', ['field1', 'field2']);
```

**Comment by BarryCarlyon** [comment]
This might be the sort of thing to include/add to the migration guide perhaps?

**Comment by djaffer** [comment]
It is due to commands becoming camel case and if you were using lower case then you would hit this issue. Not the best way of releasing a new release. I was stuck on this too.
#1760

**Comment by madprops** [comment]
>you can use HSET to set multiple fields as well

Why then use the example with HMSET, this confused me.

**Comment by Scorpiour** [comment]
> `HMSET` is deprecated since redis 4.0.0, you can use `HSET` to set multiple fields as well:
> 
> ```js
> // with an object
> client.HSET('key', {
>   field1: 'value1',
>   field2: 'value2'
> });
> 
> // with flat array
> client.HSET('key', ['field1', 'value1', 'field2', 'value2']);
> 
> // with tuples
> client.HSET('key', [['field1', 'value1'], ['field2', 'value2']]);
> ```
> 
> for `MGET`, instead of passing the field names as multiple arguments, pass them as an array:
> 
> ```js
> client.HMGET('key', ['field1', 'field2']);
> ```

Your example doesn't work on 4.6.11, while there is an error of [ErrorReply: ERR wrong number of arguments for 'hset' command]
