### ISSUE TITLE
Getting the ClientClosedError when using quit() / disconnect() methods

### ISSUE THREAD

**Issue by peterdee** [redis/node-redis#1756]
Hi. I've noticed that calling the `quit()` or `disconnect()` methods throws the following error:

```
ClientClosedError: The client is closed
    at RedisSocket.disconnect (/Users/peter/Playground/test-redis/node_modules/@node-redis/client/dist/lib/client/socket.js:62:19)
    at Commander.disconnect (/Users/peter/Playground/test-redis/node_modules/@node-redis/client/dist/lib/client/index.js:279:64)
    at stop (/Users/peter/Playground/test-redis/index.js:6:16)
    at Object.<anonymous> (/Users/peter/Playground/test-redis/index.js:9:1)
```

I am running the following script:

```javascript
const redis = require('redis');

const client = redis.createClient();

async function stop() {
  await client.disconnect();
}

stop();
```

I am using:
- Node 16.2
- redis-server 5.0.7
- node-redis 4.0.0
- Mac OS Monterey 12.0.1

I am not sure if this behaviour is valid, since it prevents me from shutting down the connection gracefully.

I did not have this problem previously when using the 3.1.2 version of `node-redis`.

**Comment by peterdee** [comment]
I've upgraded my `redis-server` to version 6.2.6, but it did not help.

**Comment by peterdee** [comment]
I've also checked the `client.isOpen` property. It equals to `false` after connection is created:

```javascript
const redis = require('redis');

async function run() {
  const client = redis.createClient();

  console.log(client.isOpen); // this is false

  await client.disconnect();
}

run();
```

This explains why the error is thrown when using the `quit()` method:

```typescript
    async quit(fn: () => Promise<unknown>): Promise<void> {
        if (!this.#isOpen) {
            throw new ClientClosedError(); // this is the thrown error
        }

        this.#isOpen = false;
        await fn();
        this.disconnect();
    }
```

I am not sure about the `disconnect()` though, because it checks the existing socket connection. Connection itself is stored as a private property and I cannot access it.

**Comment by leibale** [comment]
You should call `.quit`/`.disconnect` only after you have called `.connect`

```javascript
const redis = require('redis');

async function run() {
  const client = redis.createClient();

  await client.connect();

  console.log(client.isOpen); // this is true

  await client.disconnect();
}

run();
```

**Comment by peterdee** [comment]
@leibale Thank you, it works as expected now. 

I thought that `createClient()` will create connection without the explicit `connect()` call.

**Comment by jeroen-hoekstra** [comment]
That changed in [V4](https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md#no-auto-connect)

**Comment by rajiff** [comment]
Hi

With the newly introduced, explicit connect() method and having used Promises, how do we use the Redis connection in scenario, where there are multiple node modules/files 

Eg:
  src/module_foo/foo.js // sets a value for a key in redis
  src/module_foo/bar.js // gets a value from redis for a key

How is this scenario supported? none of the example try to show this

**Comment by peterdee** [comment]
@rajiff I don't understand what is your issue exactly. You can store Redis connection in a singleton instance and reuse it in several modules.

Here's a very simple example of Redis connection:

```javascript
// redis-connection.js
import redis from 'redis';

class RedisClient {
  constructor() {
    this.Client = null;
  }

  async connect({ host, port, password }) {
    this.Client = redis.createClient({ host, port, password });
    await this.Client.connect();
    return this.Client;
  }
}

export default new RedisClient();
```

Create connection somewhere in your application during your application launch:

```javascript
// launcher.js
import connection from './redis-connection.js';

async function launch() {
  await connection.connect({ host, port, password });
}

launch();
```
You can then access the connected client from other modules:

```javascript
// write-value.js
import connection from './redis-connection.js';

async function storeValue() {
  await connection.Client.set('key', 'value');
}

storeValue();
```

```javascript
// read-value.js
import connection from './redis-connection.js';

async function readValue() {
  const key = await connection.Client.get('key');
  console.log(key);
}

readValue();
```

**Comment by siyavashhamdi** [comment]
Here, there is a `Hello World` sample that works with
> node -v => v16.13.0
> npm -v => 8.3.0
> redis-cli -v => redis-cli 6.0.15

// read-value.js
import connection from './redis-connection.js';

async function readValue() {
  const key = await connection.Client.get('key');
  console.log(key);
}

readValue();

**Comment by siyavashhamdi** [comment]
Here, there is a `Hello World` sample that works with

```
node -v => v16.13.0
npm -v => 8.3.0
redis-cli -v => redis-cli 6.0.15
```

```
import { createClient } from 'redis';

const bootstrap = async () => {
  const client = createClient();

  await client.connect();
  await client.set('hello', 'world!');

  const key1Val = await client.get('hello');

  console.log(key1Val);
};

bootstrap();

```

**Comment by siyavashhamdi** [comment]
Here, there is a `Hello World` sample that works with

> node -v => v16.13.0
> npm -v => 8.3.0
> redis-cli -v => redis-cli 6.0.15


```
import { createClient } from 'redis';

const bootstrap = async () => {
  const client = createClient();

  await client.connect();
  await client.set('hello', 'world!');

  const key1Val = await client.get('hello');

  console.log(key1Val);
};

bootstrap();
```

**Comment by rajiff** [comment]
Hey @siyavashhamdi thanks for posting it

Yes that should work, after posting question here, I did below and it worked for me, was about to update here too

```javascript
const redis = require('redis');

async function createRedisClient () {
  const client = redis.createClient();

  client.on('connect', () => console.log('Connected to REDIS!'));
  client.on('error', (err) => console.log('Error connecting to REDIS: ', err));

  await client.connect();

  return client;
}

module.exports = createRedisClient();
``` 

and to use it

```javascript
const redisClient = require("./reidsClient");

redisClient.then((client) => { 
  // do something with the client
  await client.set("Hello", "Await World");
  // this also works, if we don't want to use await
  client.set("Hello", "Real World").then(()=> { // can do something here });
});
```

**Comment by rajiff** [comment]
@peterdee  if you see the code example you provided, every method is a `async` method, that is the issue I am pointing, as not every one like to use async/await as it hides true parallelism that JS offers can cause code readability issue in understanding parallelism 

How I have found a work around, I wish there was a way without using async/await as node-redid is really an awesome library

Thanks for responding, sorry if I sounded arrogant

**Comment by yanxel18** [comment]
> @rajiff I don't understand what is your issue exactly. You can store Redis connection in a singleton instance and reuse it in several modules.
> 
> Here's a very simple example of Redis connection:
> 
> ```js
> // redis-connection.js
> import redis from 'redis';
> 
> class RedisClient {
>   constructor() {
>     this.Client = null;
>   }
> 
>   async connect({ host, port, password }) {
>     this.Client = redis.createClient({ host, port, password });
>     await this.Client.connect();
>     return this.Client;
>   }
> }
> 
> export default new RedisClient();
> ```
> 
> Create connection somewhere in your application during your application launch:
> 
> ```js
> // launcher.js
> import connection from './redis-connection.js';
> 
> async function launch() {
>   await connection.connect({ host, port, password });
> }
> 
> launch();
> ```
> 
> You can then access the connected client from other modules:
> 
> ```js
> // write-value.js
> import connection from './redis-connection.js';
> 
> async function storeValue() {
>   await connection.Client.set('key', 'value');
> }
> 
> storeValue();
> ```
> 
> ```js
> // read-value.js
> import connection from './redis-connection.js';
> 
> async function readValue() {
>   const key = await connection.Client.get('key');
>   console.log(key);
> }
> 
> readValue();
> ```

This helps me to create connection ,set and get keys from redis 6.2.6

**Comment by ParkerOu** [comment]
Here's my version of Redis connection. 
No need to call Client every time.

1. Define Redis instance
```js
// redisClient.js
const redis = require('redis');
const { redisConfig } = require('./config/redis');

class RedisClient {
    constructor() {
        if (!RedisClient.instance) {
            this.client = redis.createClient(redisConfig);
            RedisClient.instance = this;
        }
        return RedisClient.instance.client;
    }

    async connect() {
        // error handling
        this.client.on('error', console.error);
        await this.client.connect();
    }
}

module.exports = new RedisClient();
```

2. Create connection at entry point of the app.
```js
// index.js
const redisClient = require('./redisClient');

(async () => {
    await redisClient.connect();
})();
```

3. Use case
```js
const redisClient = require('./redisClient');

const geData = async () => {
    return await redisClient.GET('test');
};
```

**Comment by domajor** [comment]
ununtu server 20.04 
Error: The client is closed
    at Commander._RedisClient_sendCommand (/home/major/pool/node_modules/@redis/client/dist/lib/client/index.js:493:31)
    at Commander.commandsExecutor (/home/major/pool/node_modules/@redis/client/dist/lib/client/index.js:188:154)
    at BaseClass.<computed> [as info] (/home/major/pool/node_modules/@redis/client/dist/lib/commander.js:8:29)
    at checkRedisVersion (/home/major/pool/init.js:147:15)

I'm so tired I can't find the mistake :(

**Comment by ParkerOu** [comment]
> ununtu server 20.04 
> Error: The client is closed

Do your redis client `connect()` first?

**Comment by domajor** [comment]
yess

**Comment by ParkerOu** [comment]
> yess

Show your code that we could help.

**Comment by domajor** [comment]
~/pool$ redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> set test "It's working!
Invalid argument(s)
127.0.0.1:6379> get test
(nil)      :(((

**Comment by ParkerOu** [comment]
This’s not this package issue.
Check redis docs and try with redis playground.
https://redis.io/commands/set/

Your `set` command lack of  Quotation mark （”）

**Comment by domajor** [comment]
l$ redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> set test "It's working!"
OK
127.0.0.1:6379> get test
"It's working!"
127.0.0.1:6379> exit
Error: The client is closed
    at Commander._RedisClient_sendCommand  :/ :/ :/
