### ISSUE TITLE
Give client a name

### ISSUE THREAD

**Issue by tdimnet** [redis/node-redis#1758]
Hi,

I am trying to add a name to my client when I create it.

On Python, I can do:

```python
cache = redis.Redis(
    host='redis',
    port=6379,
    client_name='flask-app'
)
```

However I don't find how to do it with node-redis.
Here is how I create my client:

```javascript
const client = createClient({
    socket: {
        host: 'redis',
        port: 6379
    }
})
```

I looked at the types definition inside the package but I haven't find something yet.
Should I add it elsewhere?

Thank you,
Tom.

**Comment by AnnAngela** [comment]
You can use this command to set the name of you client:
```typescript
await client.sendCommand(["SETNAME", "YOUR_CLIENT_NAME"])l
````
But it will be nice to have a dedicated command.

**Comment by tdimnet** [comment]
Hi @AnnAngela 

Thank you for your answer!
I tried the command this morning and it still doesn't work. Here is the error message:

```
/products-api/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: ERR unknown command `SETNAME`, with args beginning with: `YOUR_CLIENT_NAME`,
    at parseError (/products-api/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/products-api/node_modules/redis-parser/lib/parser.js:302:14)
```

Once I've found what's wrong, I'll try to create the feature 😄

**Comment by tdimnet** [comment]
Ok, I've found it!

This is what you should do:

```javascript
await redisClient.sendCommand(["CLIENT", "SETNAME", "products-api"])
```

And for instance if I want to pass another command, like `CLIENT LIST`, I could do:

```javascript
const clients = await redisClient.sendCommand(["CLIENT", "LIST"])
```

**Comment by AnnAngela** [comment]
@tdimnet sorry I forgot the full command, so basically that's what you should do: just split the command to a array and pass to `sendCommand`.
