### ISSUE TITLE
HMSET command is not available in v4.0.0

### ISSUE THREAD

**Issue by airs0urce** [redis/node-redis#1759]
Running this code:

```
const redis = require('redis');

(async function() {
    const client = redis.createClient({url: 'redis://127.0.0.1:6379'});
    await client.connect();
    await client.HMSET('key2', {test: 1});
})();
```

Gives this output:
```/Users/airs0urce/DEV/test/test.js:6
    await client.HMSET('key2', {test: 1});
                 ^

TypeError: client.HMSET is not a function
    at /Users/airs0urce/DEV/test/test.js:6:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

if this is not bug I would ask how to call HMSET command? (https://redis.io/commands/HMSET)

**Environment:**
 - **Node.js Version**: v16.13.0
 - **Redis Server Version**: 6.2.3
 - **Node Redis Version**: 4.0.0
 - **Platform**: Mac OS 12.0.1

**Comment by leibale** [comment]
Duplicate of #1746

**Comment by djaffer** [comment]
It is due to everything becoming camel case. Not the best way of releasing a new release. I was stuck on this too. 
#1760
