### ISSUE TITLE
rejectUnauthorized not working anymore with new Redis version

### ISSUE THREAD

**Issue by p-real96** [redis/node-redis#1767]
Since our app is deployed on Heroku which is using self signed certificates I need to disable certificate verification...
This is what we were using previously:
```
     var client = redis.createClient({
        url: process.env.REDIS_URL,
        tls: {
            rejectUnauthorized: false
        }
    }); 

```
And I have now changed it to this:
```
    var client = redis.createClient({
        url: process.env.REDIS_URL,
        socket: {
            tls: true
        },
        tls: {
            rejectUnauthorized: false
        }
    });
```

But its not taking the options into account 😒
Had a look at the new node-redis documentation: https://www.npmjs.com/package/redis
Which has lead me to the createClient config: https://github.com/redis/node-redis/blob/HEAD/docs/client-configuration.md
And this one has lead me to the tls connection options: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

But I'm really struggeling about how to pass those TLS configurations into the createClient config... Anyone out there to help me?

**Comment by leibale** [comment]
```javascript
createClient({
  url: process.env.REDIS_URL,
  socket: {
    tls: true,
    rejectUnauthorized: false
  }
});
```

**Comment by shernshiou** [comment]
I tried

> ```js
> createClient({
>   url: process.env.REDIS_URL,
>   socket: {
>     tls: true,
>     rejectUnauthorized: false
>   }
> });
> ```

but I get

```
Types of property 'tls' are incompatible.
          Type 'boolean' is not assignable to type 'true'
```

**Comment by nlfiedler** [comment]
This is still not working as advertised. I'm passing all the options and still getting `SELF_SIGNED_CERT_IN_CHAIN`, despite using these options:

```javascript
{
  url,
  socket = {
    tls: true,
    rejectUnauthorized: false,
    ca: loadAuthorityCerts(settingsRepository)
  }
}
```

According to Heroku I need to pass some "verify_mode" option, but that does not appear to be an option in node-redis.

**Comment by lluio** [comment]
Same happening here. Cannot disable tls when testing against local Redis server. Getting same as @shernshiou: 
```
Types of property 'tls' are incompatible. Type 'boolean' is not assignable to type 'true'
```

**Comment by yigaldviri** [comment]
For anyone who might reach this issue. The property you should use is `tls` and not `socket`. Im using version 3.1.2 on Node 14 - maybe it related to older versions.
```
{
      tls: {
        rejectUnauthorized: false
      },
      url: env.REDIS_URL
}
```

**Comment by nicholaswmin** [comment]
Extremely annoying that you keep breaking this with every new version.
