### ISSUE TITLE
GEOADD command doesn't work, throws error

### ISSUE THREAD

**Issue by Pic2490** [redis/node-redis#1768]
Standard Post Request
```
app.post('/test', (req, res) => {

    addGeo('Sicily', '13.361389', '38.115556', 'Palermo').then((data) => {
        if(data == 0){
            console.log(chalk.green("Works"))
            res.send("Complete")         
        //Error
        } else{
            console.log(chalk.red(data))
        }
    })
})

async function addGeo(regionKey, longitude, latitude, key){

    const client = createClient();

    client.on('error', (err) => 
        console.log('Redis Client Error', err));
  
    await client.connect();

    console.log("RegionKey: " + regionKey)
    console.log("Longitude: " + longitude)
    console.log("Latitude: " + latitude)
    console.log("Key: " + key)

    //ERROR HERE
    const value = await client.geoAdd(regionKey, longitude, latitude, key) 
    return value 

}

```
**_Log Message:_** 

>RegionKey: Sicily
Longitude: 13.361389
Latitude: 38.115556
Key: Palermo
/Users/admin/node_modules/@node-redis/client/dist/lib/commands/GEOADD.js:18
        args.push(longitude.toString(), latitude.toString(), member);
                            ^
TypeError: Cannot read properties of undefined (reading 'toString') 

The values logged are valid but still throws an error. I've tried turning Longitude and Latitude into Floats but got the same result.

**Environment:**
 - **Node.js Version**: 16.3.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.0
 - **Platform**: Mac OS 10.15.7(Catalina)

**Comment by leibale** [comment]
The command expects an object, not flat strings (https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/GEOADD.ts):
```javascript
client.getAdd('key', {
  longitude: 1, // string works as well
  latitude: 1, // string works as well
  member: 'regionKey'
});
```

In case you want to use an optional modifier (such as XX):
```javascript
client.getAdd('key', {
  longitude: 1, // string works as well
  latitude: 1, // string works as well
  member: 'regionKey'
}, {
  XX: true
});
```
