### ISSUE TITLE
Error: "Cannot read property 'toString' of undefined" in multi().zAdd() execution

### ISSUE THREAD

**Issue by mrShturman** [redis/node-redis#1770]
`
    const multi = client.multi();
   ...
    multi.zAdd(key, score,  code);
   ...
    await multi.exec();
`

this code produces next error:

`
TypeError: Cannot read property 'toString' of undefined
    at transformArgumentNumberInfinity ({projectFolder}/node_modules/@node-redis/client/dist/lib/commands/generic-transformers.js:55:24)
    at Object.transformArguments ({projectFolder}/node_modules/@node-redis/client/dist/lib/commands/ZADD.js:30:78)
    at Commander.commandsExecutor ({projectFolder}/node_modules/@node-redis/client/dist/lib/client/multi-command.js:50:40)
    at Commander.zAdd ({projectFolder}/node_modules/@node-redis/client/dist/lib/commander.js:8:29)
`

**Environment:**
 - **Node.js Version**: 14.17.3
 - **Redis Server Version**: 4.0.2
 - **Node Redis Version**: 4.0.0
 - **Platform**: 18.04.1-Ubuntu

**Comment by leibale** [comment]
```javascript
await client.multi()
  .zAdd('key', { score: 1, value: 'value' })
  .zAdd('key', [{ score: 1, value: '1' }, { score: 2, value: '2' }])
  .exec()
```

**Comment by FAQ1** [comment]
I ran into the same problem but spent some hours checking docs.

I think it should be listed on the docs to save other's time.

**Comment by CodeJuggernaut** [comment]
Where are the docs that explain the interface of zAdd? I can't find anywhere that shows it should contain an object as shown here `{ score: 1, value: 'value' }`

**Comment by XiroEx** [comment]
> Where are the docs that explain the interface of zAdd? I can't find anywhere that shows it should contain an object as shown here `{ score: 1, value: 'value' }`

Seriously, I found this very annoying.

**Comment by leibale** [comment]
https://redis.js.org/documentation/client/modules/lib_commands_ZADD.html
https://redis.js.org/documentation/client/

**Comment by hosein** [comment]
As this was a change from previous versions it should really be called out in the migration docs, or mentioned somewhere, or, at the very least, provide a more succinct error message.  I've spent entirely too much time only to find that the fix is simply a change to the provided arguments.  

Are there any other functions that have changed and are not called out in the migration docs?  How many more entirely non-descriptive errors will I need to track down?
