### ISSUE TITLE
v4 resubscribe not working

### ISSUE THREAD

**Issue by Redjik** [redis/node-redis#1771]
https://github.com/redis/node-redis/issues/1764

fix not working, it is not fixing the problem
I've taken code from the master branch and tested with the same script.

**Environment:**
same as in original issue

**Comment by leibale** [comment]
Hi @Redjik, first of all, thanks for testing my fix! :)
I tested my changes using your example script, without my changes it didn't work (as expected) - but with the changes it looks like it works for me.. wanna debug it together?

**Comment by Redjik** [comment]
sure, how can I help?

**Comment by leibale** [comment]
@Redjik I've sent u an email
