### ISSUE TITLE
ERROR SocketClosedUnexpectedlyError: Socket closed unexpectedly

### ISSUE THREAD

**Issue by Serveyk0** [redis/node-redis#1772]
Hi)
I'm new to redis and trying to get document id from `ft.aggregate` as '@__key' with help redis package, but after first query I get 'SocketClosedUnexpectedlyError: Socket closed unexpectedly' error every time .
May someone help with this problem, please? 
Thanks)

**Comment by leibale** [comment]
Have you tried running the exact same command using `redis-cli`? Can you share the command you are trying to execute (including the arguments)?

**Comment by Serveyk0** [comment]
Sure

const searchQuery = `${multiQuery}|${fuzzyQuery}`;
const results = await this.redisClientConnect.ft.aggregate(index, searchQuery, {
  LOAD: ["@city", "@__key"]
});
    
after the first request everything returns fine, but after the second I get this error
    
![image](https://user-images.githubusercontent.com/57505835/145273934-6f7dc691-5775-4544-a579-3b8a3990213d.png)

Also without "@__key" everything works well and there are no errors and this command has worked fine with `redis-cli`

**Comment by leibale** [comment]
The socket closes because the `redis-server` crashes... please open this issue under the [RediSearch repository](https://github.com/RediSearch/RediSearch/issues).
