### ISSUE TITLE
This is not working 

### ISSUE THREAD

**Issue by DhairyaBahl** [redis/node-redis#1777]
Not working ! I had to switch to ioredis because this is not working !

**Comment by DhairyaBahl** [comment]
I kept on doing redis.createClient but it didn't work ! I was giving proper hostUrl, password and port by passing an object in the createClient function but it didn't worked ! It would be amazing if you can tell me the reason why it didn't worked !!

```
const client = redis.createClient({
host: host,
password: password,
port: port
});
```

Kindly tell me what is wrong with this ??

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/docs/client-configuration.md

```javascript
const client = redis.createClient({
  socket: {
    host,
    port
  },
  password
});
```
