### ISSUE TITLE
The client is closed error while using v4

### ISSUE THREAD

**Issue by Fexyler** [redis/node-redis#1780]
Hey There!

I was trying to connect my Redis server with node-redis but can't reach the server. After a couple of searches on the internet, I tried to downgrade the version and it was solved. I just wondered that why I couldn't reach the server with the new version?

This is my code to connect to the server:

```javascript
const client = redis.createClient({
  host: '127.0.0.1',
  port: 6379,
  enableOfflineQueue: false,
  retry_strategy(options) {
    if (options.error && options.error.code === 'ECONNREFUSED') {
      return new Error('The server refused the connection');
    }
    if (options.total_retry_time > 1000 * 60 * 60) {
      return new Error('Retry time exhausted');
    }
    if (options.times_connected > 10) {
      return undefined;
    }
    return Math.max(options.attempt * 100, 3000);
  },
});
```
**Environment:**
 - **Node.js Version**: 16.13.0
 - **Redis Server Version**: 5.0.7
 - **Node Redis Version**: 4.0.0
 - **Platform**: Ubuntu 18.04

**Comment by jayeclark** [comment]
@Fexyler I just encountered this today myself. It's not a bug but is instead how V4 works. You need to manually connect now after creating the client (using `client.connect()`) before running any redis commands.  Also, the config object is different now (most of the config options now go under socket and how you define reconnect strategy is also quite different.) 

A large amount has changed between the versions so be prepared for a major refactor if upgrading!

[Details and new docs here.](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md)

**Comment by Fexyler** [comment]
Okay I will check the document that you sent, thank you for your response!

**Comment by happysmash27** [comment]
@jayeclark Where would I input client.connect()? I am debugging someone else's software and it is not clear from the documentation.

**Comment by muudi10** [comment]
> @jayeclark Where would I input client.connect()? I am debugging someone else's software and it is not clear from the documentation.

right after where the client is declared.

**Comment by thduik** [comment]
I had the same error message when using redis as express-session store. It only happened when i used chrome.
The cause of the bug was because i disabled chrome web security (disable-web-security). Enabling it again fixed the problem.
