### ISSUE TITLE
RedisSocketOptions interface is incomplete

### ISSUE THREAD

**Issue by BPerry24** [redis/node-redis#1784]
Per [Client Configuration Options](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#tls) documentation, `createClient({ socket: { ... } })` should accept options found in `tls.connect`, and in-fact it does. However, when using typescript I am unable to pass certain `tls.connect` options (`checkServerIdentity` in my specific case) without type-asserting `as any`.

In general, I think it would be really useful to expose the necessary types and interfaces from the package, so that those of us using typescript don't have to have to infer type using things like `type client = ReturnType<typeof createClient>;` or have import paths like `import { RedisClientOptions } from '@node-redis/client/dist/lib/client/index';`.

**Environment:**
 - **Node.js Version**: 16.1.0 AND 16.6.1-alpine3.14 (docker)
 - **Redis Server Version**: 6.0.5
 - **Node Redis Version**: 4.0.0
 - **Platform**: Mac OS & Alpine Linux (docker)
<img width="854" alt="Screen Shot 2021-12-14 at 12 53 55 PM" src="https://user-images.githubusercontent.com/36909585/146053231-7d761745-2839-4e9f-9acd-bff512d0854c.png">

**Comment by leibale** [comment]
Already fixed in `redis@4.0.1`/`@node-redis/client@1.0.1`

**Comment by BPerry24** [comment]
@leibale Thank you
