### ISSUE TITLE
Node Modules Compile Error

### ISSUE THREAD

**Issue by goktugyil** [redis/node-redis#1787]
I'm getting compile errors as soon as I include `import { createClient } from 'redis';` and I build `tsc`.  And not just a few, getting 223 errors. 

This doesn't happen if I include via `const redis = require('redis')` which is not the recommended way.

The weird thing is tsconfig has `node_modules` excluded. And this never happened in a nother library before. 

<img width="1071" alt="Screen Shot 2021-12-15 at 15 40 34" src="https://user-images.githubusercontent.com/5816878/146261763-554c5222-17c9-46c9-95b5-5c1d9bad3246.png">

**Environment:**
 - **Node.js Version**: 12
 - **Redis Server Version**: redis:5.0.3-alpine (Not relevant. Will start using redis 6 after installing this)
 - **Node Redis Version**: 4.0.1
 - **Platform**: Mac OS 12.1
 - **Typescript**: 3.9.3

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2019",
    "sourceMap": true,
    "inlineSources": true,
    "strictNullChecks": true,
    "removeComments": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "skipLibCheck": true,
    "types": [
      "node",
      "mocha",
      "chai"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
  },
  "exclude": [
    "./node_modules"
  ]
}
```

**Comment by leibale** [comment]
Which version of TypeScript are you using (see #1781)?

**Comment by goktugyil** [comment]
> Which version of TypeScript are you using (see #1781)?

^3.9.9

**Comment by goktugyil** [comment]
Ok so I need to upgrade Typescript to v4 before installing this. Thanks
