### ISSUE TITLE
It is not a bug, but what is alternative way to access to redis-server run by docker

### ISSUE THREAD

**Issue by jaewonhimnae** [redis/node-redis#1790]
Hello
I used to access to Redis Server by using the property "host" 

  const client = createClient({
    host: "redis-server",
    port: 6380
  });

like this.  

but I fount out that host property dissapeared in version 4 

in my docker-compose.yml 

version: "3"
services:
  redis-server:
    image: "redis"
    
 Can you let me know what is alternative way to access to redis-server ? 
 
 Thanks

**Environment:**
 - **Node.js Version**: 10 
 - **Node Redis Version**: 4.0.1
 - **Platform**: Mac OS

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/docs/client-configuration.md
```javascript
const client = createClient({
  socket: {
    host: "redis-server",
    port: 6380    
  }
});
```

**Comment by vipulw2011** [comment]
@jaewonhimnae We can use any of these approaches to connect, I want to learn the difference from implementation team though. 

First : 
```
const client= createClient({
  socket: {
    host: envConfig.REDIS_HOST,
    port: envConfig.REDIS_PORT
  },
  database: envConfig.REDIS_DATABASE
});

client.connect();
```

Second : 

```
const client = createClient({
  url: `redis://${envConfig.REDIS_HOST}:${envConfig.REDIS_PORT}/${envConfig.REDIS_DATABASE}`
});

client.connect();
```

I referred to this migration docs from redis 3 to 4
1. https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md
2. https://github.com/redis/node-redis/blob/master/docs/client-configuration.md

Hope this helps ! :)

**Comment by vipulwairagade** [comment]
@jaewonhimnae  We can use any of these approaches to connect, I want to learn the difference from implementation team though. 

First : 
```
const client= createClient({
  socket: {
    host: envConfig.REDIS_HOST,
    port: envConfig.REDIS_PORT
  },
  database: envConfig.REDIS_DATABASE
});

client.connect();
```

Second : 

```
const client = createClient({
  url: `redis://${envConfig.REDIS_HOST}:${envConfig.REDIS_PORT}/${envConfig.REDIS_DATABASE}`
});

client.connect();
```

I referred to this migration docs from redis 3 to 4
1. https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md
2. https://github.com/redis/node-redis/blob/master/docs/client-configuration.md

Hope this helps ! :)
