### ISSUE TITLE
Redis Typeerror on Build

### ISSUE THREAD

**Issue by stanley355** [redis/node-redis#1791]
Hi, I updated Node redis from `3.1.2` to `4.0.1`, in my other Next.js project I successfully updated it without having any issue (on 18 Des 2021). However, in the currect project (Next.js too) which I was just updated the Node redis, it shows error everytime I run `yarn build`. The error was specifically on `Node modules` folder:
![image](https://user-images.githubusercontent.com/53996155/146739809-69cf97e5-fc0b-46df-90af-93f954aa1245.png)

However, when running it on local (e.g. yarn dev), it was running smoothly, anybody encounters similar issue?

**Environment:**
 - **Node.js Version**:10.2.3
 - **Redis Server Version**: 5.0.7
 - **Node Redis Version**: 4.0.1
 - **Platform**: Linux Ubuntu 20

**Comment by leibale** [comment]
Which version of TypeScript are you using (see #1781)?

**Comment by stanley355** [comment]
> Which version of TypeScript are you using (see #1781)?

@leibale finally found the issue, I didn't add the typescript dependencies, thanks
