### ISSUE TITLE
TypeError: Invalid pathname

### ISSUE THREAD

**Issue by stanley355** [redis/node-redis#1793]
Hi I'm building Next.js project with Node-redis and has just updated it from 3.1.2 to 4.0.1. The build already works on my locale, however when running the build on Github action it shows the following error: 

![image](https://user-images.githubusercontent.com/53996155/146879780-f18347de-0f57-48fc-9f45-04046dcff4d5.png)

And my `createClient({url:... })` looks like this `redis://:@${process.env.REDIS_HOST}:6379/${process.env.REDIS_DB}`, I can ensure the `url` is correct as the build runs on my locale.

My questions will be:
- If we don't have any required `username` or `pass`, should we write the `:`  between `username` and password, or there are certain syntax for the url?
- Was my issue caused by difference in env?

Does anybody encounters similar issue?

**Environment:**
 - **Node.js Version**: 14.0
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.1
 - **Platform**: Ubuntu 20.04.3

**Comment by leibale** [comment]
- In case there is no username and password - just remove that auth part (`redis://${process.env.REDIS_HOST}:6379/${process.env.REDIS_DB}`).
- The "invalid pathname" error means that the DB part is not a number (https://github.com/redis/node-redis/blob/master/packages/client/lib/client/index.ts#L135) - check the "process.env.REDIS_DB" value in production

**Comment by stanley355** [comment]
Thanks @leibale , how bout we add the docs for the case if there's no username and password?

**Comment by leibale** [comment]
@stanley355 both `redis://:@${process.env.REDIS_HOST}:6379/${process.env.REDIS_DB}` and `redis://:@${process.env.REDIS_HOST}:6379/${process.env.REDIS_DB}` should work
