### ISSUE TITLE
Question on handling loss of connectivity

### ISSUE THREAD

**Issue by horrendo** [redis/node-redis#1799]
I'm trying to work out how to deal with loss of connectivity with a redis server. From what I can see, as soon as loss of connectivity is detected, the client will automatically attempt to re-establish the connection. I put logging on the different event handlers and I could see the following:

error, followed by 5 cycles of:

reconnecting (immediately after an error, apart from the first error)
connect (after approx 2-3 ms)
ready (immediately after connect)
error (approx 2-3 ms after ready)

followed by 'n' cycles of:

reconnecting (increasing delays up to approx 50 ms)
error (approx 2-3 ms after reconnecting)

followed by (once connectivity can be re-established):

reconnecting
connect (after approx 2 ms)
ready (immediately after connect)

From what I can tell, an `await client.get` or `await client.set` that is submitted during a period of 'no connectivity' will block until connectivity has been re-established. I tried a `try .. catch` but the `catch` is not triggered. Maybe if loss of connectivity happened immediately after the call it would throw an exception, but I was not able to determine this.

In my case, the redis caching is a 'nice to have' to avoid a database lookup, but if the server is not available, I'd like a 'get' or 'set' to return `null` immediately and proceed as if there was no caching.

Using the events, I can sort of work out whether I have connectivity and should therefore go ahead with the `set` or `get`, but there still seems to be opportunity for this to not work. For example, if I set the internal state to 'ok' when a 'ready' event is fired, and 'not ok' when an 'error' event is fired, there still seems to be 2-3 ms before the 'error' is fired if there is still no connectivity. If I was unlucky enough to submit a 'set' or 'get' in the interim, it seems that would block until connectivity could be re-established.

I'm new to redis, so maybe I'm going about this all wrong. I assume this is a common scenario, so could someone please enlighten me as to the 'correct' solution. I looked in the docs but if I missed something please point me at it and accept my apologies.

Thanks !!

**Environment:**
 - **Node.js Version**: v14.17.6 
 - **Redis Server Version**: docker redis:6.2-alpine 
 - **Node Redis Version**: 4.0.1 
 - **Platform**: Mac OS 11.6.2

**Comment by carlosmondra** [comment]
Hi! I had the same issue. I noticed that this will happen while the client tries to reconnect. You can change the [reconnectStrategy function](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) which tries to reconnect forever preventing your function to go inside the catch block (I'm not sure if this behavior is a bug or if it's intended). What you want to do is modify it, so that at some point the reconnectStrategy function returns an Error. Once you do that, your function will go inside the catch block.

Please let me know if I'm missing something.

**Comment by horrendo** [comment]
Thanks @carlosmondra. That looks like what I need. I really appreciate you taking the time to respond.
