### ISSUE TITLE
Bug in hGetAll (4.0.1) returning mixed fields or Incorrect documentation, or both. 

### ISSUE THREAD

**Issue by metawrap-dev** [redis/node-redis#1800]
I am having problems with `hGetAll`.

When after I `hSet` with a mix of string, number and Buffer, when subsequently call `hGetAll`, the buffer field comes back corrupted in two ways. 

1. `typeof` reports it as a string but logging it, results in binary escape horror. 
2. Treating it as a binary, it does not match what was saved. 

Now, when I attempt to use this example code from README.md

```
await client.hSet('key', 'field', Buffer.from('value')); // 'OK'
await client.hGetAll(
  commandOptions({ returnBuffers: true }),
  'key'
); // { field: <Buffer 76 61 6c 75 65> }
```

I get the following compilation error.

```
src/Redis/RedisRepository.ts:65:73 - error TS2345: Argument of type '{ returnBuffers: boolean; }' is not assignable to parameter of type 'ClientCommandOptions'.
  Object literal may only specify known properties, and 'returnBuffers' does not exist in type 'ClientCommandOptions'.

65         const fields = await this.Redis.Client.hGetAll(commandOptions({ returnBuffers: true }),key);
```

**Environment:**
 - **Node.js Version**: v16.13.0
 - **Redis Server Version**: Redis server v=6.2.6 sha=00000000:0 malloc=libc bits=64 build=ffd424e92d4892ad
 - **Node Redis Version**: redis@4.0.1
 - **Platform**: Mac OS 11.6.1

**Comment by leibale** [comment]
I've added the `returnBuffers` option in a0de7967f98068790cd09c909bbbb7e7d6deefe8, which wasn't released yet...

**Comment by metawrap-dev** [comment]
Thank you! Will that change also resolve the type mismatch/corruption? What was going on there? Bad low-level marshaling?
