### ISSUE TITLE
xAdd should support value with other types besides string type (for example: number type)

### ISSUE THREAD

**Issue by freemanh** [redis/node-redis#1808]
Currently the message parameter in xAdd method only support string value type, but in Redis Streams spec, there is no constraints like this.

if you coding like this:
`await redis.xAdd(doc.sendTo, '*', {'v1': 0})`
then VSCode will complain like below:
> Type 'number' is not assignable to type 'string'.ts(2345)

if you try to run this code, there will be a runtime exception complain the same issue.

**Environment:**
 - **Node.js Version**: v14.18.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.1
 - **Platform**: MacOS

**Comment by simonprickett** [comment]
Inside the stream the values will all be stored as strings so it may be hard to determine this other than relying on coercion which may or may not be what you want. 

```bash
127.0.0.1:6379> xadd demostream * somevalue 1
"1642090783565-0"
127.0.0.1:6379> xread streams demostream 0
1) 1) "demostream"
   2) 1) 1) "1642090783565-0"
         2) 1) "somevalue"
            2) "1"
```

**Comment by freemanh** [comment]
Thanks for the explanation about how Redis store stream values and it make sense to me. 
But it is still a little inconvenient to transform data type when putting values in cases you can just put the original values.
