### ISSUE TITLE
Question: Which actual node/npm version is needed for v4?

### ISSUE THREAD

**Issue by bvgusak** [redis/node-redis#1812]
It looks like v4 should work for Node 12 according to https://github.com/redis/node-redis/blob/master/packages/client/CHANGELOG.md#breaking-changes.

Still in `package.json` v4 expects `"npm": ">=7":
`https://github.com/redis/node-redis/blob/2203be5fbd4883f69b9a52f7d7c44b444f361201/package.json#L47

Since `node v12` is compatible wih `npm v6` I get following warning after running `npm install`:
```
npm WARN notsup Unsupported engine for redis@4.0.1: wanted: {"npm":">=7"} (current: {"node":"12.22.7","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: redis@4.0.1
```

Is it okay to use `npm v6` and should this warning be simply ignored?

**Environment:**
 - **Node.js Version**: 12.22.7
 - **Node Redis Version**: 4.0.1
 - **Platform**: Mac OS 11.5.2

**Comment by leibale** [comment]
In "development mode" we are using npm workspaces, which were introduced in npm 7, but in "production mode", npm 6 should work. I'm not sure if there is an option to define an engine for dev mode only, will check..
