### ISSUE TITLE
Substitute for `connected`, `command_queue_length`, `offline_queue_length` in v4

### ISSUE THREAD

**Issue by khangly** [redis/node-redis#1817]
I just updated to v4 and realized `connected`, `command_queue_length`, and `offline_queue_length` are missing in the client object. Is there any substitution available?

**Comment by leibale** [comment]
[`commandsQueueMaxLength`](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) and `client.isOpen`:
```javascript
const client = createClient({
  commandsQueueMaxLength: 1000
});

console.log(client.isOpen); // false
await client.connect();
console.log(client.isOpen); // true
```

**Comment by khangly** [comment]
Thank you!
