### ISSUE TITLE
v4: EXISTS should resolve to number instead of boolean

### ISSUE THREAD

**Issue by OxleyS** [redis/node-redis#1819]
The [raw Redis EXISTS command](https://redis.io/commands/exists) returns the number of keys, out of the ones passed, that exist in the database. The v4 implementation of `client.exists()`, however, returns a `Promise<boolean>`, only returning `true` if all the passed keys exist.

While I understand making it boolean improves the ergonomics in many cases, this shuts out the possibility of using the command to see if _any_ key of a list exists. (As an aside, it's also a breaking change that should have been mentioned in the migration guide.) It should probably be made to return a `number` again.

**Comment by leibale** [comment]
@OxleyS until we'll release the fix you can use:
```javascript
const reply = await client.sendCommand(['EXISTS', 'key']);
```

**Comment by akelmj** [comment]
> 
Not norking , return undefined

`const reply = await client.sendCommand(['EXISTS', 'category:111']);`

and from redisinsight:

![image](https://user-images.githubusercontent.com/8736967/189533938-c1ab3f01-0b87-4c46-bbf3-cdb9f7ca653f.png)
