### ISSUE TITLE
Broken dependency? @node-redis/bloom

### ISSUE THREAD

**Issue by pablitovicente** [redis/node-redis#1828]
I'm trying to run the 1st example from the docs and I'm getting the following error:

> internal/modules/cjs/loader.js:328
>       throw err;
>       ^
> 
> Error: Cannot find module '/app/node_modules/@node-redis/bloom/dist/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:320:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/app/node_modules/redis/dist/index.js:15:17)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/app/node_modules/@node-redis/bloom/package.json',
>   requestPath: '@node-redis/bloom'

Sample code I'm using is:

> const { createClient } = require('redis');
> 
> (async () => {
>   const client = createClient()
> 
>   client.on('error', (err) => console.log('Redis Client Error', err))
> 
>   await client.connect()
> 
>   await client.set('key', 'value')
>   const value = await client.get('key')
>   console.log(value)
> })()
> 

It seems `node_modules/@node-redis/bloom/dist` is missing, perhaps broken build/publishing?

**Environment:**
 - **Node.js Version**: 14.17.6
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.2
 - **Platform**: Manjaro

**Comment by leibale** [comment]
Bloom was mistakenly published without the actual files, `npm update` should solve it
