### ISSUE TITLE
Production Best Practices - One client per request?

### ISSUE THREAD

**Issue by JLaferri** [redis/node-redis#1844]
There doesn't seem to be anything in the readme about this. When using a redis client library in go, I would make a new client for each request that comes in. What is the best practice for this library?

The quick start example makes it seem like having a single persistent client is correct. Which is better? Does it matter? Is it worth adding to the readme?

Thanks.

**Comment by JLaferri** [comment]
Hmm yeah this should have the documentation label probably. I don't know how to change it.

**Comment by leibale** [comment]
In most cases you should use a single client. See the [Isolated Execution guide](https://github.com/redis/node-redis/blob/master/docs/isolated-execution.md).
