### ISSUE TITLE
Cluster connection quit

### ISSUE THREAD

**Issue by Varagos** [redis/node-redis#1864]
It seems that Cluster client does not support graceful quit method like regular client instance. Forcible disconnect is working fine.  Are we supposed to use the latter to close the connection?  

**Environment:**
 - **Node.js Version**:  16.13.1
 - **Node Redis Version**:  4.0.2

```
Property 'quit' does not exist on type 'RedisClusterType...
```

**Comment by leibale** [comment]
:man_facepalming:
