### ISSUE TITLE
cluster mode doesnot support legacyMode?

### ISSUE THREAD

**Issue by mrkrishnsharma** [redis/node-redis#1873]
cluster mode doesnot support legacyMode?

i want to use clustermode, with call backs. is it possible? because i could not get it to work?

**Comment by leibale** [comment]
v3 didn't support clusters at all... but you can use node built-in [`util.callbackify`](https://nodejs.org/api/util.html#utilcallbackifyoriginal)

**Comment by lexdubyna** [comment]
In fact, when I am trying to do
```js
util.callbackify(client.get)('key', function (err, reply) {
  some_other_function(err, reply)
}
```
I am getting this error:
```
TypeError: Cannot read property 'sendCommand' of undefined
at commandsExecutor (/usr/local/src/node_modules/@redis/client/dist/lib/cluster/index.js:126:75)
at BaseClass.<computed> (/usr/local/src/node_modules/@redis/client/dist/lib/commander.js:8:29)
at Callbackified (util.js:210:5)
```
coming from this line: https://github.com/redis/node-redis/blob/master/packages/client/lib/cluster/index.ts#L158

**Comment by leibale** [comment]
@lexdubyna 
```javascript
const getCallback = util.callbackify(client.get.bind(client));

getCallback('key', (err, reply) => {
  console.log(err, reply);
});
```

**Comment by lexdubyna** [comment]
@leibale Thank you very much!
Maybe this could be added somewhere in the docs?

**Comment by leibale** [comment]
@lexdubyna TBH I think it should be in `util.callbackify` docs, but since it's not there (I think), maybe we should...

**Comment by lexdubyna** [comment]
@leibale I'm really sorry to bring you back to this issue, but how is it possible to `callbackify` something like this?
```javascript
await client.multi()
  .sAdd(...)
  .expire(...)
  .set(...)
  .exec()
```

**Comment by leibale** [comment]
@lexdubyna 
```
cosnt multi = client.multi()
  .sAdd(...)
  .expire(...)
  .set(...);
util.callbackify(client.exec.bind(multi))((err, replies) => {
  // ...
});
```
can you please share why you need the callback API?

**Comment by lexdubyna** [comment]
@leibale Sorry for the late reply. The reason is I have to make changes to an old legacy callback project: Redis needs to be in cluster mode now.
