### ISSUE TITLE
Not able to connect to redis-labs cloud redis server

### ISSUE THREAD

**Issue by AmreshSinha** [redis/node-redis#1892]
**Environment:**
 - **Node.js Version**: v16.13.2
 - **Redis Server Version**: 6.2.3
 - **Node Redis Version**: redis@4.0.3
 - **Platform**: OS: Manjaro Linux x86_64

**Code:**
```
const redis = require("redis");
require("dotenv").config();

(async () => {
  const client = redis.createClient({
    socket: {
      host: process.env.REDIS_URI,
      port: process.env.REDIS_PORT,
    },
    password: process.env.REDIS_PASSWORD,
  });

  client.on("error", (err) => console.log("Redis Client Error", err));

  await client.connect();

  await client.set("key", "value");
  const value = await client.get("key");
})();

```

All code is taken from docs and Client Configuration docs. On running, it doesn't console out anything. Database doesn't gets updated either.

Any help will be appreciated!
Thanks!

**Comment by Didas-git** [comment]
Try to use `url` instead, works just fine for me.
Idk how you have the config but this should work.
```js
redis.createClient({ url: `redis://default:${process.env.REDIS_PASSWORD}@${process.env.REDIS_URI}:${process.env.REDIS_PORT}` })
```

**Comment by AmreshSinha** [comment]
> Try to use `url` instead, works just fine for me. Idk how you have the config but this should work.
> 
> ```js
> redis.createClient({ url: `redis://default:${process.env.REDIS_PASSWORD}@${process.env.REDIS_URI}:${process.env.REDIS_PORT}` })
> ```

Thanks! It worked! But I am still surprised that why it didn't worked earlier when I provided host, port and password separately.

I will use URL from now! Thanks mate!

**Comment by Didas-git** [comment]
> > Try to use `url` instead, works just fine for me. Idk how you have the config but this should work.
> > ```js
> > redis.createClient({ url: `redis://default:${process.env.REDIS_PASSWORD}@${process.env.REDIS_URI}:${process.env.REDIS_PORT}` })
> > ```
> 
> Thanks! It worked! But I am still surprised that why it didn't worked earlier when I provided host, port and password separately.
> 
> I will use URL from now! Thanks mate!

You are wellcome, but tbh im not sure either, the way i found on the docs was using `url` and have been using since.
