### ISSUE TITLE
`RedisClient` is not exported and I can not import  use its type definition in my code 

### ISSUE THREAD

**Issue by ehsanagh** [redis/node-redis#1895]
I can't import like this, `import { RedisClient } from '@node-redis/client'`;
by `RedisClient` I mean the type definition for client object not the object.
I wanna use like this ` constructor(redis: RedisClient) { ... }`

**Environment:**
 - **Node.js Version**: V14.18
 - **Redis Server Version**: Aws service
 - **Node Redis Version**: 1.0.3
 - **Platform**: Mac

**Comment by Didas-git** [comment]
> I can't import like this, `import { RedisClient } from '@node-redis/client'`; by `RedisClient` I mean the type definition for client object not the object. I wanna use like this ` constructor(redis: RedisClient) { ... }`
> 
> **Environment:**
> 
> * **Node.js Version**: V14.18
> * **Redis Server Version**: Aws service
> * **Node Redis Version**: 1.0.3
> * **Platform**: Mac

Im not sure what you mean with that but if its what i think it is you can try and do this.
```ts
import { createClient } from "redis";

type RedisClient = ReturnType<typeof createClient>

class MyClass {
    constructor(redis: RedisClient) {...}
}
```

**Comment by ehsanagh** [comment]
Thank you, Exactly this is what I was looking for.
even thou I found `RedisClientOptions` and `RedisClientType` too which are useful. Thanks.
