### ISSUE TITLE
you need to run .connect() before any command ???

### ISSUE THREAD

**Issue by anselal** [redis/node-redis#1897]
Hi there,

in the new documentation for v4 you state that we need to run `client.connect()` before any command but this is misleading cause if we do so we get `Uncaught Error: Socket already opened`.

Do we really need to run `.connect()` every time before any command just to make sure we are connected but handle the exception like this ?

```js
await client.connect().catch(error => {})
```

**Comment by anselal** [comment]
Just for reference: 
https://github.com/redis/node-redis/blob/9f0f7f52159b8ca544ffaa28f8e35b0c4b565464/docs/v3-to-v4.md?plain=1#L19

**Comment by Didas-git** [comment]
> Hi there,
> 
> in the new documentation for v4 you state that we need to run `client.connect()` before any command but this is misleading cause if we do so we get `Uncaught Error: Socket already opened`.
> 
> Do we really need to run `.connect()` every time before any command just to make sure we are connected but handle the exception like this ?
> 
> ```js
> await client.connect().catch(error => {})
> ```

You just need to run `.connect()` once.
Create the client, connect the client and then you can do whatever you want.
If you want to open and close connections you can duplicate the client

**Comment by anselal** [comment]
Thnx, so the docs need to updated on that matter

**Comment by leibale** [comment]
fixed in #1902
