### ISSUE TITLE
socket.reconnectStrategy is not applied

### ISSUE THREAD

**Issue by micodix** [redis/node-redis#1985]
Hi,

I have a TypeScript application in which I am using the new `socket.reconnectStrategy` option described in https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#reconnect-strategy. 
However, this does not seem to be applied. After stopping the Redis server, the `reconnecting` event is still fired within the default delay of 500ms. But according to my configuration, this should happen after 3000ms.

My code:
```ts
(async () => {
  try {
    const client = createClient({ socket: { host: '127.0.0.1', port: 6379, connectTimeout: 3000, reconnectStrategy: (_retryAttempt: number): number | Error => 3000 } })
    client.on('connect', () => {
      console.info('Redis client is connecting to redis://127.0.0.1:6379...')
    })
    client.on('ready', () => {
      console.info('Redis client is connected')
    })
    client.on('reconnecting', () => {
      console.info('Redis client is reconnecting...')
    })
    client.on('error', error => {
      console.error(`Redis client error: ${JSON.stringify(error)}`)
    })

    await client.connect().catch(error => console.error(JSON.stringify(error)))
  } catch (error) {
    console.error(`Service start error: ${JSON.stringify(error)}`)
  }
})().catch(() => {})
```

**Environment:**
 - **Node.js Version**: 14.16.1
 - **Redis Server Version**: 6.2.0
 - **Node Redis Version**: 4.0.3
 - **Platform**: Windows 10

**Comment by micodix** [comment]
Hi leibale,

thanks for trying out.
I've just c&p and run your code example, but still no luck. The following debug output runs quickly across the console:

```sh
...
reconnectStrategy: 29.181s error
Redis client error: {}
reconnectStrategy: 29.182s reconnecting
reconnectStrategy: 29.184s connect
reconnectStrategy: 29.185s ready
reconnectStrategy: 29.197s error
Redis client error: {}
reconnectStrategy: 29.198s reconnecting
reconnectStrategy: 29.200s connect
reconnectStrategy: 29.201s ready
reconnectStrategy: 29.213s error
Redis client error: {}
reconnectStrategy: 29.215s reconnecting
reconnectStrategy: 29.216s connect
reconnectStrategy: 29.217s ready
reconnectStrategy: 29.232s error
Redis client error: {}
reconnectStrategy: 29.233s reconnecting
...
...
```

Any idea?

**Comment by leibale** [comment]
please run `npm ls redis` in the directory of the script and make sure the version is 4.0.3

**Comment by micodix** [comment]
Yes, it's 4.0.3

![image](https://user-images.githubusercontent.com/80091840/154144962-3a3074d6-cc47-4e63-846e-cc36f54b3840.png)

**Comment by leibale** [comment]
@micodix "it works on my machine" :P 
wanna debug it together?

**Comment by tugtugtug** [comment]
I have the same issue.
When the socket closes unexpectedly (which happens to be the case if the server no longer listens on the port), https://github.com/redis/node-redis/blob/741aff0c30028c852771fb43c520093b7a23a164/packages/client/lib/client/socket.ts#L182 fires, 
and socket.#connect gets called immediately, https://github.com/redis/node-redis/blob/741aff0c30028c852771fb43c520093b7a23a164/packages/client/lib/client/socket.ts#L214,
then socket.#retryConnection gets called with retries reset to 0, https://github.com/redis/node-redis/blob/741aff0c30028c852771fb43c520093b7a23a164/packages/client/lib/client/socket.ts#L100,
then socket.#createSocket gets called to repeat the error again.
This is running into a constant loop, and in my case starved my entire node, and I had to kill the node to get it out of the bad condition.
What bothers me is most was that the server was definitely gone, and yet, the socket fired, 'connect' and 'ready', and createSocket seemed to have succeeded after the connectEvent fired.
Anyway, this is a showstopper for us to migrate to v4.

**Comment by nicktalb** [comment]
We've been encountering similar problems and on investigation I have found that:
1) ✅  If Redis is not running when the client service is started, the `reconnectStrategy` triggers and keeps trying to connect. If I then start the Redis service the client service connects successfully.
2) ❌ If Redis goes down while the client service is already running and connected to Redis, it receives `socket closed unexpectedly` - I then quickly see the following sequence of events:
  - `error` - `Socket closed unexpectedly`
  - `reconnecting`
  - `connect`
  - `error` - `Socket closed unexpectedly`
  - `reconnecting`
  - `end`

If the client service tries to use the connection after this an error `ClientClosedError: The client is closed` is triggered. It never reconnects automatically. I assume this is not expected behiour.

**Comment by rpong** [comment]
@leibale i just tested 4.1.0 and it seems this issue still persists, reconnecting still doesn't work like it used to like in v3. after "Socket closed unexpectedly", it just doesn't reconnect without restarting the client application. We simulate this by restarting redis (docker).

**Comment by leibale** [comment]
@rpong this does not reproduce the issue (I ran `docker restart` a couple of times while this code is running)

```javascript
import { createClient } from '@redis/client';

const client = createClient();

client.on('error', err => console.error('client err', err));

await client.connect();

setInterval(async () => {
  try {
    console.log(await client.ping());
  } catch (err) {
    console.error('command error', err);
  }
}, 1000);
```

**Comment by rpong** [comment]
Thanks @leibale , it turns out we needed this before "await client.connect();"

`client.on('error', err => console.error('client err', err));`

All working now. Thank you, we can finally upgrade to v4.
