### ISSUE TITLE
dynamic NUMBER_OF_KEYS for Lua Script

### ISSUE THREAD

**Issue by namgk** [redis/node-redis#1990]
Hi there,

How do I code a lua script that has a dynamic NUMBER_OF_KEYS?

Something like mHmGet?

Here's the lua script that I've got:

    `local res = {} for i, key in ipairs(KEYS) do     res[#res+1] = redis.call("HMGET", key, ${projection.join(',')}) end  return res`

Thanks

**Comment by leibale** [comment]
You can't :man_facepalming: 

I think I'll make `script.NUMBER_OF_KEYS` optional, and then you'll be able to prepend it to args in `script.transformArguments`. WDYT?

**Comment by namgk** [comment]
Sounds good, but how do I define/execute the script on the fly, not just
when creating the redis client?

Thanks

**Comment by leibale** [comment]
You cannot define a script on the fly, but you can always use `client.executeScript`

**Comment by namgk** [comment]
So can I combine client.executeScript and script.transformArguments?
