### ISSUE TITLE
ERR unknown command SELECT

### ISSUE THREAD

**Issue by alpha-r2net** [redis/node-redis#1994]
I'm using today with "ioredis" library
in ioredis my configuration connection is

```
{
        sentinels: [{ host: '<ip>', port: <port>},
            { host: '<ip>', port: <port> },
            { host: '<ip>', port: <port> }],
        name: '<name>',
        password: '<password>',
        sentinelRetryStrategy: function (times) {
            return Math.min(times * 10, 1000)
        },
        db: 2
    }
```
and this is working for me.
but the library make me support new command in code.
they not support it naturally when I just connect to redis.
such as set (members) some of the commads need to sign for them.
make it so harder then to use redis library

now I want to use redis and this configuration is from yours doc

```
{
        rootNodes: [
            {
                url: `redis://<ip>:<port>`,
            },
            {
                url: `redis://<ip>:<port>`,
            },
            {
                url: `redis://<ip>:<port>`,
            }
        ],
        defaults: {
            username: REDIS_USERNAME,
            password: REDIS_PASSWORD,
            database: 2
        }

    }
```
and it not working for me.
the error is throw that the bug error title
only database is do, is connecting to database 2 and not for default is 0

**Environment:**
 - **Node.js Version**:  16.14.0
 - **Redis Server Version**: 5.0.7
 - **Node Redis Version**:  4.0.3
 - **Platform**: Windows 10

**Comment by leibale** [comment]
Sentinels and clusters are not the same (https://medium.com/hepsiburadatech/redis-solutions-standalone-vs-sentinel-vs-cluster-f46e703307a9), and unfortunately, node-redis does not (yet) support sentinels.
