### ISSUE TITLE
JSDocs?

### ISSUE THREAD

**Issue by supertiger1234** [redis/node-redis#2004]
It would be really nice if every redis command provided a description inside vs code. 

If i knew how to do this, I would definitely send a PR.

Example:
![image](https://user-images.githubusercontent.com/8193841/155313070-8e069128-b985-467b-ab01-18be7593891f.png)

PS: I don't know why this is marked as a bug even though i selected feature request.

**Comment by Didas-git** [comment]
Since the library is made in typescript its not pratical to do comments like that specially because typescript was made to avoid this.
I would rly recommend getting used to ts types bcz they serve as documentation in a lot of cases

**Comment by supertiger1234** [comment]
ah, i got it. I personally think it looks cleaner in the non ts way, but ill try. thanks.
