### ISSUE TITLE
Why is #private used?

### ISSUE THREAD

**Issue by euberdeveloper** [redis/node-redis#2006]
I see that `#private` is used, even if the code is written in Typescript (ts already has a `private` keyword). It is true that typescript privates have no reflections in the resulting javascript code, but at least they support es5. What should I do if I wanted to use es5?

**Environment:**
 - **Node.js Version**: v16.3.0
 - **Node Redis Version**:  4.0.4
 - **Platform**: Ubuntu 20

**Comment by leibale** [comment]
["Private class features" available since node 12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#browser_compatibility), which is [the oldest "active" node version](https://nodejs.org/en/about/releases/). What are you trying to do?

**Comment by euberdeveloper** [comment]
The problem is not when I execute the ES5 code, but when I transpile it with Typescript targeting ES5

```Private identifiers are only available when targeting ECMAScript 2015 and higher```

**Comment by euberdeveloper** [comment]
The only way I've found to avoid this problem is setting `skipLibCheck` as false. Otherwise I had to change the target to ES6

**Comment by Didas-git** [comment]
I dont get what you mean, the issue should be on your code since the version on npm is already compiled and it shouldnt error.
Maybe with more information we are able to find something (?)

**Comment by euberdeveloper** [comment]
I think that just by installing/using the library and trying to transpile with typescript (target es5, non-skip-lib), the issue would appear.

**Comment by Didas-git** [comment]
> I think that just by installing/using the library and trying to transpile with typescript (target es5, non-skip-lib), the issue would appear (during transpilation, not runtime).

I will take a look then, but i dont see why you would skip library checkings

**Comment by euberdeveloper** [comment]
But I thin that the only way is to use skipLibCheck or Babel with Typescript. The reason why your code transpiles is because you have es2019 as target.

So the only thing I would do on your side is writing in the migration guide that for typescript es5 as target is not supported because of the # fields and that the only way to keep it work is to add the skipLibCheck

**Comment by euberdeveloper** [comment]
> > I think that just by installing/using the library and trying to transpile with typescript (target es5, non-skip-lib), the issue would appear (during transpilation, not runtime).
> 
> I will take a look then, but i dont see why you would skip library checkings

It is because in that way there is not a typescript check in the dependencies (i.e. node_modules)

**Comment by Didas-git** [comment]
> But I thin that the only way is to use skipLibCheck or Babel with Typescript. The reason why your code transpiles is because you have es2019 as target.
> 
> So the only thing I would do on your side is writing in the migration guide that for typescript es5 as target is not supported because of the # fields and that the only way to keep it work is to add the skipLibCheck

I actually use es3 as target to test and if it passes i try esnext but i will try es5 as well this time

**Comment by euberdeveloper** [comment]
This is my tsconfig

```json
{
    "compilerOptions": {
        "strict": true,
        "target": "ES5",
        "lib": [
            "ES2021"
        ],
        "downlevelIteration": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "./*"
            ]
        },
        "outDir": "../dist/server"
    }
}
```

**Comment by Didas-git** [comment]
After testing it turns out to be true but this wont be fixed, i dont get why you are trying to target something lower than ES6 but I dont see a way that this could be fixed.
If private is used its for a reason (and an obvious one) so i think you are better off switching to minimum ES6 specially because of promises and other things

**Comment by euberdeveloper** [comment]
Yes, if not run on web it makes more sense to change the target to something newer and I also agree that there is no point in downgrading a library

Maybe the only thing that could be done is adding this note on the migration guide
