### ISSUE TITLE
Error with Typescript

### ISSUE THREAD

**Issue by euberdeveloper** [redis/node-redis#2007]
This is my tsconfig.json:
```json
{
    "compilerOptions": {
        "strict": true,
        "target": "ES6",
        "lib": [
            "ES2021"
        ],
        "moduleResolution": "node",
        "downlevelIteration": true,
        "sourceMap": true,
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "./*"
            ]
        },
        "outDir": "../dist/server"
    }
}
```

I obtain this error:

```
node_modules/@types/connect-redis/index.d.ts:22:29 - error TS2694: Namespace '"/home/euber/Github/preben/pnc-api/node_modules/redis/dist/index"' has no exported member 'RedisClient'.

22         type Client = redis.RedisClient | ioRedis.Redis | ioRedis.Cluster;
                               ~~~~~~~~~~~
```

EDIT: I see now that it is connected with connect-redis, can anyone here still answer the issue?

**Environment:**
 - **Node.js Version**: v16.3.0
 - **Node Redis Version**:  4.0.4
 - **Platform**: Ubuntu 20

**Comment by Didas-git** [comment]
Try to use `RedisClientType` instead.
It is a generic but redis now also exports the modules types and script types correctly (or at least should)

**Comment by euberdeveloper** [comment]
Ok Thanks. This is actually code of one of my dependencies (@types/connect-redis), so I will open an issue in their repo
