### ISSUE TITLE
Add RedisCommandArgument as an allowed parameter for XADD message

### ISSUE THREAD

**Issue by rmeloca** [redis/node-redis#2019]
The command LPUSH allows us to receive a **RedisCommandArgument**, which may be a string or a buffer.
`transformArguments(key: RedisCommandArgument, elements: RedisCommandArgument | Array): RedisCommandArguments;`
This is great for us to write something like this `REDIS_CLIENT.LPUSH('my-key', JSON.stringify(myComplexObject))`.

On the other hand, for XADD, it is required a **Record<string, RedisCommandArgument>**
`transformArguments(key, id, message: Record<string, RedisCommandArgument>, options?): RedisCommandArguments;`
This is quite sad because this dos not allow us to send a string to the stream.
Therefore, instead of writing this `REDIS_CLIENT.XADD('my-stream', '*', JSON.stringify(myComplexObject))`, I must write `REDIS_CLIENT.XADD('my-stream', '*', {message: JSON.stringify(myComplexObject)})` for correct sending and parsing of the message.
This is quite bad because when reading a message from the stream instead of simply having `{id: "1646190013763-0", message: "the-jsonified-complex-object-i-sended"}`, I have to have `{id: "1646190013763-0", message: {message: "the-jsonified-complex-object-i-sended"}}`.
This also creates memory bloat that would not be necessary, IMO.

My proposal is to change the type of the parameter `message` of the function transformArguments within XADD file from `message: Record<string, RedisCommandArgument>` to `message: Record<string, RedisCommandArgument> | RedisCommandArgument`
Verification regarding the type of message received and proper treatment will be needed.

Just for the sake of linking: #1808

**Comment by akrsmv** [comment]
@rmeloca what solution you went with? 

I have similar problem where i have to insert a stringified json that contains number fields, and the library will not let me. Thus I have to do :
```
.xAdd('mystream', '*', 
    JSON.parse(JSON.stringify(
        JSON.parse(jsonline, (key, value) => value.toString()))))
```
just to convert all number values to strings, before the `.xadd` method let me in. Seems redundant operations over whole jsons, while the library can just
