### ISSUE TITLE
BLOCK is broken for XREAD and XREAGROUP

### ISSUE THREAD

**Issue by rmeloca** [redis/node-redis#2021]
When timeout is `0` => it never receives a message
When timeout is `50000` => it waits until the timeout is done to fetch the added message, instead of immediately unblocking when a message is added.

I've tested `lpop` with timeout `0` and its working fine,
however, it never receives new messages added to the stream when block is set to 0 either for `XREAD` and `XREADGROUP`.
I've tested it through the parser `REDIS_CLIENT.xReadGroup()` as well as using `REDIS_CLIENT.sendCommand()`
Note: using `commandOptions({isolated: true})`

**Environment:**
 - **Node.js Version**: v16.13.0
 - **Redis Server Version**: redis-cli 6.2.6
 - **Node Redis Version**: "redis": "^4.0.4",
 - **Platform**: Fedora 35

**Comment by leibale** [comment]
@rmeloca can you please share a code that reproduces the issue?

**Comment by rmeloca** [comment]
I am sorry. I've found that the issue I was having was because I was sharing the same connection for multiple blocking XREAD operations. Closing this.

**Comment by rhodgkins** [comment]
@rmeloca what did you do to fix this exactly?

>I was sharing the same client connection

>`commandOptions({isolated: true})`

as I understand this (new connection per command) is the same as a new client per read?

**Comment by rmeloca** [comment]
@rhodgkins 
Instead of having like this:
``` javascript
const connection = await createClient({ url: 'redis://localhost:6379', password: 'secret' }).connect()
async getMessages(stream: string) {
  while (true)
    const messagesOfStream = await connection.xReadGroup(commandOptions({ isolated: true }), 'service-1', 'replica-1', { key: stream, id: '>' }, { COUNT: 1, BLOCK: 0 })
}
getMessages('stream1') // asynchronously running
getMessages('stream2') // asynchronously running
```
I've simply changed to have two connections, like this:
``` javascript
async getMessages(stream: string) {
  const connection = await createClient({ url: 'redis://localhost:6379', password: 'secret' }).connect()
  while (true)
    const messagesOfStream = await connection.xReadGroup(commandOptions({ isolated: true }), 'service-1', 'replica-1', { key: stream, id: '>' }, { COUNT: 1, BLOCK: 0 })
}
getMessages('stream1') // asynchronously running
getMessages('stream2') // asynchronously running
```
In the first code I am blocked reading from stream1, which prevents me to read from stream2, even it get new messages before stream2.
In the second code I am able to read from both streams simultaneously. Anyone that get new messages first will processed first.
