### ISSUE TITLE
FT.SEARCH RETURNS support identifier and property

### ISSUE THREAD

**Issue by dannyk03** [redis/node-redis#2023]
From documentation of FT.SEARCH
> RETURN {num} {identifier} AS {property} ... : Use this keyword to limit which attributes from the document are returned. num is the number of attributes following the keyword. If num is 0, it acts like NOCONTENT . identifier is either an attribute name (for hashes and JSON) or a JSON Path expression for (JSON). property is an optional name used in the result. If not provided, the identifier is used in the result.

However, source of node-redis has typing for RETURNS like
```
RETURN?: string | Array<string>;
```

It accepts the list of strings but we might have to provide the identifier and property for each RETURN element.
How can we provide it to redis search options since we have no typign support?

Finally, I want to query via node-redis like
``` 
FT.SEARCH" "idx:users" "*" "RETURN" "2" "$.createdBy" AS "createdBy"
```

**Environment:**
 - **Node.js Version**: v16
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.2
 - **Platform**: Ubuntu 20.04.3

**Comment by Avital-Fine** [comment]
Hey @dannyk03! 
I think you meant to query `FT.SEARCH" "idx:users" "*" "RETURN" "3" "$.createdBy" AS "createdBy"`
So in the meantime, you can send 'AS' as part of the array and it will work :)

**Comment by dannyk03** [comment]
@Avital-Fine Thanks for your response. I have tried that. But I did not work.

And here's why - https://github.com/redis/node-redis/blob/9180b9104751ed5128a62034d1e0e1152b7414c1/packages/client/lib/commands/generic-transformers.ts#L325

RETURN is parsed via pushVerdictArgument and it's parsed as
```
FT.SEARCH" "idx:users" "*" "RETURN" "3" "$.createdBy AS createdBy"
```
instead of
```
FT.SEARCH" "idx:users" "*" "RETURN" "3" "$.createdBy" AS "createdBy"
```

**Comment by Avital-Fine** [comment]
Hey @dannyk03,
I rechecked with [RedisSearch documentation](https://oss.redis.com/redisearch/Commands/#ftsearch) and it should be 3 and not 1: 

![image](https://user-images.githubusercontent.com/98389525/156915107-29eab47a-7d36-412b-b548-633cf2f286bb.png)

So you can send 3 arguments
`transformArguments('idx:users', '*', { RETURN: ['$.createdBy', 'AS', 'createdBy'] }),
`
and get 
`"FT.SEARCH" "idx:users" "*" "RETURN" "3" "$.createdBy" "AS" "createdBy"`

Let me know if it works!

**Comment by dannyk03** [comment]
@Avital-Fine
I will check in a couple of days and let you know.
But I must be wrong. It should be 3 not 1. Thanks!

**Comment by dannyk03** [comment]
@Avital-Fine This works... Thanks a lot :)
