### ISSUE TITLE
Polyfill issue with vueJs3 and Webpack5

### ISSUE THREAD

**Issue by mathieumuller** [redis/node-redis#2024]
Hi everyone, 

I am facing an issue with a fresh install of VueJs 3 with TypeScript. It seems Webpack 5 does not allow auto-polyfilling anymore 
and a lot of your dependencies cannot be resolved. 

- I cannot apply the suggested workaround in webpack.config.js as this file does not exist in my project. 
- Installing dependencies in my project and defining missing paths in tsconfig.json does not seem to work either.

Is there any workaround for my case or is it just impossible for now to use with VueJs3?

Thanks in advance

**Environment:**
 - **Node.js Version**:  16
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.4
 - **Platform**: Bullseye

```
ERROR in ./node_modules/@node-redis/client/dist/lib/lua-script.js 8:17-34

Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/@node-redis/client/dist/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
```

**Comment by leibale** [comment]
node-redis is not intended to run in the browser, what are you trying to do?

**Comment by mathieumuller** [comment]
> node-redis is not intended to run in the browser, what are you trying to do?

Ok that's what I feared , I've read that a couple of times since. I just want to store the result of an API call, so I'm creating a redis client into my Vue component to get the cached data if exists or call my endpoint with axios. It seems I'm misusing something.
