### ISSUE TITLE
ZRANGE DOESN'T CONTAIN THE WITHSCORES OPTION IN YOUR ABSTRACTION, MUST USE SENDCOMMAND INSTEAD

### ISSUE THREAD

**Issue by jyoung4242** [redis/node-redis#2031]
**Environment:**
 - **Node.js Version**: 
 - **Redis Server Version**: 
 - **Node Redis Version**: 
 - **Platform**:

**Comment by jyoung4242** [comment]
```JS
//DOESNT WORK
//seen = await client.zRange(`seen:${user}`, 0, -1, { WITHSCORES: true });
//DOES WORK
seen = await client.sendCommand(['ZRANGE', `seen:${user}`, 0, -1, 'WITHSCORES']);
```

**Comment by leibale** [comment]
Because the `WITHSCORES` argument changes the reply type (from `Array<string>` to `Array<{ score: number; value: string; }>` , it's implemented as `zRangeWithScores/ZRANGE_WITHSCORES`:

```javascript
await client.zRangeWithScores('key', 0, -1);
await client.ZRANGE_WITHSCORES('key', 0, -1);

**Comment by jyoung4242** [comment]
Thanks for quick reply
