### ISSUE TITLE
Constant Error: Socket closed unexpectedly

### ISSUE THREAD

**Issue by subos2008** [redis/node-redis#2049]
I'm constantly getting this error in my logs (every 10 seconds or so) since upgrading `node-redis` from v2.8 to the latest v4:

```
Error: Socket closed unexpectedly
    at Socket.<anonymous> (/app/node_modules/@node-redis/client/dist/lib/client/socket.js:182:118)
    at Object.onceWrapper (node:events:640:26)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12)
```

**Environment:**
 - **Node.js Version**: 16
 - **Redis Server Version**: 5.0.6
 - **Node Redis Version**:
 - "redis-v4@npm:redis@^4":
  version "4.0.4"
  resolved "https://registry.yarnpkg.com/redis/-/redis-4.0.4.tgz#b567f82f59086df38433982f7f424b48e924ec7a"
  integrity sha512-KaM1OAj/nGrSeybmmOWSMY0LXTGT6FVWgUZZrd2MYzXKJ+VGtqVaciGQeNMfZiQX+kDM8Ke4uttb54m2rm6V0A==
  dependencies:
    "@node-redis/bloom" "1.0.1"
    "@node-redis/client" "1.0.4"
    "@node-redis/graph" "1.0.0"
    "@node-redis/json" "1.0.2"
    "@node-redis/search" "1.0.3"
    "@node-redis/time-series" "1.0.2"
 - **Platform**: node:16 docker image

I've looked around but I'm still unsure why this might be. Is this a keepAlive thing? Docs for recent redis server versions seem to indicate connections are left open forever by default.

There were no changes in the server, only the client node-redis lib upgrade.

I'm seeing this error in client.on('error') - which I was trying to use to set microservice health checks to kill off services that lost their connection to redis.

Maybe a factor: I'm using an npm alias to have node-v4 installed in tandem with the original v2.8 client library 

Everything seems functionally to work - I'm just getting my logs spammed and my healthcheck has had to be disabled.

Any help / clues? I can't see anyone else reporting similar issues

**Comment by leibale** [comment]
Does your redis server seats behind some kind of proxy/tunnel?

**Comment by LucidThought** [comment]
I'm seeing this issue as well (sort of). I'm using redis@4.04 as pub/sub channels for a socket.io server (using the @socket.io/redis-adapter package). I don't see it so often as 10 seconds, but at least several times per day. I need to determine the cause of these disconnection events, as they're causing problems with how I need the rest of my code to behave.

**Comment by subos2008** [comment]
> Does your redis server seats behind some kind of proxy/tunnel?

Yes, behind haproxy. And indeed looking closer the connections get closed every 30s which is what the `timeout.client` setting was in the proxy. Almost certainly that's the issue. From my side I tried increasing that timeout but behaviour hasn't changed. But, that's my problem :)

Thanks @leibale

**Comment by goktugyil** [comment]
How did you solve it?
