### ISSUE TITLE
Search Options ignored in query

### ISSUE THREAD

**Issue by mike-niemand** [redis/node-redis#2055]
Hi All,

I'm trying to pass LIMIT options on a search as follows:

`await client.ft.SEARCH("index", "*", "LIMIT 0 1").then((data) => {
    console.log(data)
});`

But LIMIT is ignored. Is this because I'm using a wildcard?

**Comment by mike-niemand** [comment]
Hmmm as per documentation for wildcard:  _This cannot be combined with any other filters, field modifiers or anything inside the query._

<bangs head against wall>

**Comment by leibale** [comment]
```javascript
console.log(
  await client.ft.search('index', '*', {
    LIMIT: {
      from: 0,
      to: 1
    }
  })
);

```

**Comment by mike-niemand** [comment]
Thanks for replying

> ```js
> console.log(
>   await client.ft.search('index', '*', {
>     LIMIT: {
>       from: 0,
>       to: 1
>     }
>   })
> );
> ```

Sadly throws: 

`TypeError: Cannot read properties of undefined (reading 'toString')
    at pushSearchOptions (xxxxx\node_modules\@node-redis\search\dist\commands\index.js:295:78)`

**Comment by leibale** [comment]
It works on my machine... Which version of `redis`/`@node-redis/client`/`@node-redis/search` version are you using?

**Comment by mike-niemand** [comment]
> ```js
> {
>     LIMIT: {
>       from: 0,
>       to: 1
>     }
> ```

Sorry for the belated reply.

Redis server v=6.2.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=9c9e426e2f96cc51
"redis": "^4.0.4",

**Comment by mike-niemand** [comment]
Sorted

> ```js
> console.log(
>   await client.ft.search('index', '*', {
>     LIMIT: {
>       from: 0,
>       to: 1
>     }
>   })
> );
> ```

Sorted. The second parameter is 'size' not 'to'.

Thanks so much for your reply.
