### ISSUE TITLE
redisearch

### ISSUE THREAD

**Issue by bumi001** [redis/node-redis#2056]
Hi, I am getting "ReplyError: Invalid rule type". I am using redisearch 2.0.15. Is it possible to list the dependency of what version of @node-redis/search needs what version of redisearch module?

const { createClient, SchemaFieldTypes, AggregateGroupByReducers, AggregateSteps } = require('redis');

const users_schema = async (client) => {
  try {
    await client.ft.create('idx:users', {
      '$.user_id': {
        type: SchemaFieldTypes.TAG,
        AS: 'user_id'
      },
    }, {
      ON: 'JSON',
      PREFIX: 'users'
    });
  } catch (e) {
    if (e.message === 'Index already exists') {
      console.log('Index exists already, skipped creation.');
    } else {
      // Something went wrong, perhaps RediSearch isn't installed...
      console.error(`users_schema: ${e}`);
      process.exit(1);
    }
  }
}

**Comment by leibale** [comment]
Do you have RedisJSON installed? ([`MODULE LIST`](https://redis.io/commands/module-list/))

**Comment by bumi001** [comment]
Yes. I do have RedisJSON installed. I ran client.info() using node-redis.
The following is a partial output:

  '# Modules\r\n' +

'module:name=search,ver=20015,api=1,filters=0,usedby=[],using=[],options=[]\r\n'
+

'module:name=ReJSON,ver=20006,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]\r\n'
+
  '\r\n' +

**Comment by bumi001** [comment]
After updating to redisearch-2.2.5, I don't have this problem anymore.
