### ISSUE TITLE
Instrumenting the v4 Redis client

### ISSUE THREAD

**Issue by garbados** [redis/node-redis#2061]
Hi! I'm a developer with New Relic. In order to support our customers using Redis, we are trying to instrument `node-redis` in order to effectively report application telemetry. Unfortunately we have encountered some issues with the v4 client code. Specifically, we cannot correlate commands passed through the `commandsQueue` with the client that initiated them. This prevents us from associating commands with their originating client. As an example of this problem, this means that we cannot indicate to a customer which of their Redis servers is failing when we observe failing commands.

Is there a way to correlate, from the command queue, which client passed the command along?

**Comment by garbados** [comment]
We have identified at least one way to fix this, but it requires a change to the node-redis codebase. If the private [#sendCommand](https://github.com/redis/node-redis/blob/master/packages/client/lib/client/index.ts#L381-L398) method, through which all of a client's commands pass, were made into a public method that our agent software can access and instrument, then we could correlate commands with the client that initiated them. We recognize this may be undesirable, but I thought I'd bring it up as a possibility.

**Comment by prakis** [comment]
I think even the arguments format for the sendCommand is changed from V3 to V4.

**Comment by garbados** [comment]
We were able to resolve the issue by instrumenting every command individually. Although we have some concerns about this approach, it solves the problem, so I'm closing this issue.
