### ISSUE TITLE
Cannot subscribe to Cluster client

### ISSUE THREAD

**Issue by nirlo** [redis/node-redis#2065]
I've been looking to use the cluster client, but there seems to be a lot of missing functionality.

The cluster connection only seems to be able to run sever commands and does not have the functionality of the normal redis client.

Although we can individually connect to a node in the cluster, it would be better if the the subscription round robins to the different nodes in the cluster as a part of the library.

**Comment by leibale** [comment]
"subscription round robins to the different nodes in the cluster" will be possible only with "[Sharded Pub/Sub](https://redis.io/docs/manual/pubsub/#sharded-pubsub)" (which  is not yet supported in this client)

**Comment by richardwu** [comment]
I ended up using `ioredis` which does support `subscribe/psubscribe` for clusters.

**Comment by almandsky** [comment]
Any update on this?  I may need to switch to `ioredis` as well due to the same reason.

**Comment by gmerciel** [comment]
Same thing, "subscribe" method is not available for RedisCluster. At least this could be put as a warning on the docs... so we take it into consideration when we select which library to use...

**Comment by jlippold** [comment]
I know this issue was marked as completed, but does anyone have a working example with socket io and cluster mode in aws elasticache?
