### ISSUE TITLE
Property 'on' does not exist on type 'RedisClientType'

### ISSUE THREAD

**Issue by ngr900** [redis/node-redis#2067]
I'm following the "Basic Example" from the README:

```ts
import { createClient } from 'redis';
(async () => {
  const client = createClient();

  client.on('error', (err) => console.log('Redis Client Error', err));

  await client.connect();

  await client.set('key', 'value');
  const value = await client.get('key');
})();
```
This results in the following TypeScript error:
```
Property 'on' does not exist on type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("..."); configGet: typeof import("..."); ... 15 more ...; slowLog: typeof import("...'.ts(2339)
```
The property is there:
```ts
console.log((client as any).on); // logs: [Function: addListener]
```
It just appears to not be included in the type.

**Environment:**
 - **Node.js Version**: v14.17.5
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: redis@4.0.6
 - **Platform**: Windows 11 22000.556 + WSL Ubuntu 20.04

**Comment by ngr900** [comment]
Alright, sorry for the fuss, I just had to install `@types/node`. Couldn't they be included in the dependencies?

**Comment by leibale** [comment]
@ngr900 `@types/node` is a dev dependency of [`@node-redis/client`](https://github.com/redis/node-redis/blob/master/packages/client/package.json#L25)...
