### ISSUE TITLE
LegacyMode multi commands do not parse array arguments

### ISSUE THREAD

**Issue by JPricey** [redis/node-redis#2071]
For a v4 redis client in legacy mode, this command:
`redis.multi().sadd('a', ['b', 'c']).exec()`
adds the element `"['b', 'c']"` to the set `a`.

The expected behaviour is to add two separate elements, `b` and `c` to the set `a`.

A proposed fix is here:
https://github.com/redis/node-redis/pull/2064

**Environment:**
 - **Node.js Version**: v12.20.1 (I don't expect this to matter)
 - **Redis Server Version**: 6.2.5 (I don't expect this to matter)
 - **Node Redis Version**: 4.0.4
 - **Platform**: Mac OS 11.6

**Comment by leibale** [comment]
fixed in #2064
