### ISSUE TITLE
Add common Lua scripts as "Extras" for the lib 

### ISSUE THREAD

**Issue by MatanYemini** [redis/node-redis#2075]
Hi!

I have found myself writing Lua scripts for common purposes like:

-  using "EXPIRE" for multiple keys
-  doing "HGETALL" / "HGET" / their relatives from several keys (or keys-fields if HGET) 
-  doing "HSET" / his relatives  for several keys

and many more...

I know about auto-pipelining, but I am not sure that one tick is enough for cases where a lot of keys are involved.

I don't mind implementing it! just wanted to get your opinion. (we can design it later once approved)

Thanks!

**Comment by leibale** [comment]
I don't think that the client library is the right place to add those scripts...
@guyroyse @simonprickett WDUT?

**Comment by simonprickett** [comment]
@leibale agree, maybe there should be some other repo of commonly useful scripts that are client/language independent so just contains Lua files?

**Comment by MatanYemini** [comment]
@simonprickett IMHO, it might be nice to have it in a separate repo/lib as long it can be easily integrated here.

**Comment by MatanYemini** [comment]
Any thoughts on this? 🙃

**Comment by simonprickett** [comment]
I like the idea of having a common Lua script repo that's client independent.
