### ISSUE TITLE
There are some bugs in using legacy mode in redis. I can only be called through callback

### ISSUE THREAD

**Issue by zero2one3** [redis/node-redis#2085]
**Environment:**
 - **Node.js Version**:  14.18.2
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.6
 - **Platform**: Mac OS 11.2.3

# Use Case

I use legacy mode in redis

```ts
const redisClient = createClient({
  legacyMode: true,
});
```

I can't get data, but i can get data through callback.

```ts
// set
redisClient.set('example', '01')

const data = await redisClient.get('example')
// data is undefined

redisClient.get('example', (err, data) => {
    console.log(data)  
    //  data is '01'
})
```

Is there something wrong with the way I use it？

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md#legacy-mode

```javascript
const client = createClient({
    legacyMode: true
});

// legacy mode
client.set('key', 'value', 'NX', (err, reply) => {
    // ...
});

// version 4 interface is still accessible
await client.v4.set('key', 'value', {
    NX: true
});
```

**Comment by nleborgne** [comment]
I am also experiencing this issue. I can't get the value of the redis key using get but I can get it through a callback
