### ISSUE TITLE
Preventing Reconnection (or retries)

### ISSUE THREAD

**Issue by st11x** [redis/node-redis#2095]
Hi,

I want to prevent any retries if it cannot connect to Redis for any reasons, so  I have my code set up like this:

```
    let client = createClient({
        url: process.env.REDIS_URL,
        socket: {
            reconnectStrategy: (retries) => Error("Don't retry"),
        },
    });

    client.on("error", (err) => console.log(`Cannot connect to redist at ${process.env.REDIS_URL}`));

    await client.connect().catch((err) => "proceed");
```

This doesn't work. If Redis was down, the error event handler gets fired rapidly in an endless loop and maxes out the CPU. 
 
Thanks
  Matt

**Environment:**
 - **Node.js Version**: 16.14.0
 - **Redis Server Version**: 7.0-rc2 (docker)
 - **Node Redis Version**: 4.0.4
 - **Platform**: Ubuntu 20.04.3 and  Windows 10

**Comment by leibale** [comment]
@st11x seems like it fixed in 4.1.0, wanna try it?
