### ISSUE TITLE
search sort does not handle DESC direction ?

### ISSUE THREAD

**Issue by RupertBarrow** [redis/node-redis#2097]
The spec here
https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/SORT.spec.ts
does not mention sort direction 'DESC', only 'ASC'.

Lines 55-62 seem to indicate that only 'DIRECTION' 'ASC' is transformed into 'SORT' 'key' 'ASC', but 'DIRECTION' 'DESC' will not be managed.

**Environment:**
 - **Node.js Version**: 14.18.1
 - **Redis Server Version**: 6.2.0-v1 (via Redis Stack and "brew services")
 - **Node Redis Version**: 4.0.6
 - **Platform**: macOS 11.6.5

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/generic-transformers.ts#L501

```javascript
transformArguments('key', {
    DIRECTION: 'DESC'
});
// ['SORT', 'key', 'DESC']
);
```

**Comment by RupertBarrow** [comment]
My Javascript which is worlink : 

```
let searchResultsLines = await this.redisClient.ft.search('lines', q, {
        LIMIT : {
          from: query.nblines_from,
          size: query.nblines_size
        },
        SORTBY: {
          BY: 'dt',
          DIRECTION: 'DESC'
        }
      })
```

which produces : 
```
!@# [
  'FT.SEARCH', 'lines',
  '%guer%',    'SORTBY',
  'dt',        'DESC',
  'LIMIT',     '0',
  '50'
]
```
