### ISSUE TITLE
Why `undefined` is missing from RedisJSON interface?

### ISSUE THREAD

**Issue by neokkk** [redis/node-redis#2122]
I want to use redis for on-live chat rooms storage.
My room interface has createdAt, updatedAt, deletedAt like any other.
createdAt is always existed, but others may not be. (optional)
I cannot insert my room info into redis without any filtering(removing undefined).
Is there any reason for absence of undefined at RedisJSON?
If not, could you please modify it so that undefined can also be used?

```ts
const { id, ...rest } = room; // typeof Room

// ts error
// Index signature for type 'string' is missing in type '{ ...createdAt: Date; deletedAt?: Date | undefined; updatedAt?: Date | undefined; }'.ts(2345)
this.redisClient.json.set(id, '.', rest);

// ok
this.redisClient.json.set(id, '.', Object.fromEntries(
  Object.entries(rest).filter(([, v]) => Boolean(v)))
);
```

**Environment:**
* **Node.js Version**: v16.14.1
* **Node Redis Version**: 4.0.6
* **Platform**: Mac OS 12.3.1

**Comment by leibale** [comment]
RedisJSON (the module) does not support `undefined`

```
> JSON.SET myDoc $ '{"field": undefined}'
(error) expected value at line 1 column 11
```
