### ISSUE TITLE
mGet, mSet not accepting numbers

### ISSUE THREAD

**Issue by RagunanndhanS** [redis/node-redis#2149]
**Environment:**
 - **Node.js Version**: 16.13.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**:4.1.0

**Comment by leibale** [comment]
["Redis Hashes are maps between **string** fields and **string** values"
](https://redis.io/docs/manual/data-types/#hashes)

BTW, [RedisJSON](https://redis.io/docs/stack/json/) can do that, and a lot more.
