### ISSUE TITLE
Callback Support

### ISSUE THREAD

**Issue by SonsofKings** [redis/node-redis#2150]
Hello, my work heavily relies on redis, but also has a hard no promises rule. Is there any way to enable callback support on this anymore? Is there a path to providing callback support in the future?

**Comment by SonsofKings** [comment]
I didn't mean to label this as a bug, I thought this was being put in as a feature request.

**Comment by leibale** [comment]
@SonsofKings you can enable `legacyMode` (but that will be removed in the next major version), or use [`util.callbackify`](https://nodejs.org/api/util.html#utilcallbackifyoriginal)
