### ISSUE TITLE
v4 has no equivalent functionality to client.connected.

### ISSUE THREAD

**Issue by OliverGrayDG** [redis/node-redis#2152]
This was mentioned in issue [1845](https://github.com/redis/node-redis/issues/1845), but the answer is not satisfactory.

Version 3.1.2 (and earlier) had a `connected` property on the `RedisClient` object, that could be used to determine whether the client was currently connected to Redis. This was useful, for example, to check whether a connection was present before trying to issue a command to redis.

The solution suggested in [1845](https://github.com/redis/node-redis/issues/1845), to use `await client.clientInfo()`, doesn't cover all use cases. If redis is not connected when this command is run, it will hang until a connection attempt is made just like any other command. Checking the `connected` property was an immediate sychronous operation.

It appears that functionality idential to that provided by `client.connected` has been lost in v4. Will this be addressed?

**Environment:**
 - **Node.js Version**: v16.15.0
 - **Redis Server Version**: 6.2.3
 - **Node Redis Version**: 4.1.0
 - **Platform**: N/A

**Comment by leibale** [comment]
checkout `client.isOpen` and `client.isReady`

**Comment by Sn0wCrack** [comment]
I'm currently facing the same issue as Oliver.

It looks like isReady can be accessed, however, it appears that the exported TypeScript definitions do not correctly expose the property/accessor/method on whatever it is that the createClient function returns.

Adding a `// @ts-ignore` line above usage of isReady will allow it to compile and will return the expected true or false based on if the socket has been successfully created yet or not.

Could this issue be re-opened to have this exported in the definition files?

**Comment by leibale** [comment]
@Sn0wCrack it'll be released in the next version
https://github.com/redis/node-redis/blob/master/packages/client/lib/client/index.ts#L169

**Comment by Sn0wCrack** [comment]
Thanks for the update 😄
