### ISSUE TITLE
MIGRATE command doesn't work with multiple keys

### ISSUE THREAD

**Issue by StefanCenusa** [redis/node-redis#2163]
Hello,

I'm trying to migrate multiple keys using `client.migrate` and I am getting the following error:
```
[ErrorReply: ERR When using MIGRATE KEYS option, the key argument must be set to the empty string]
```
when using `migrate` like this:
```
    await RedisManager.client.migrate(RemoteRedis.host, RemoteRedis.port, clientIdsKeys, 0, 10000);
```

However, if I try using `client.sendCommand` it works:

```
    const command = ['MIGRATE', RemoteRedis.host, RemoteRedis.port.toString(), "", "0", "10000", "KEYS", ...clientIdsKeys];
    await RedisManager.client.sendCommand(command);
```

I suspect the issue resides in[ `transformArguments` function ](https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/MIGRATE.ts#L22) where an empty string of this form `'""'` is added to arguments when `key` parameter is an Array.

I think that if only an empty string of this form is added `""` as I do it when using `client.sendCommand` the command would return success.

**Environment:**
 - **Node.js Version**: 16.15.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.1.0

**Comment by leibale** [comment]
You are 100% right, it should be `args.push('')` (and not `args,push('""')`). Wanna create a PR?

**Comment by StefanCenusa** [comment]
@leibale yes, I can do that.
