### ISSUE TITLE
Detect client version at runtime.

### ISSUE THREAD

**Issue by avin-kavish** [redis/node-redis#2164]
I am writing a library that has redis as a peer dependency. I have a requirement to detect the version of a redis client passed to my library at runtime, is that possible?

**Comment by leibale** [comment]
You can `require('redis/package.json').version`

**Comment by avin-kavish** [comment]
The check would ideally be on the instance itself. They could also pass in `ioredis`.

(Btw, your automation marked this issue as a bug, even though I selected the feature request option.)

**Comment by leibale** [comment]
@avin-kavish `send_command` exists only in v3

**Comment by avin-kavish** [comment]
Appreciate it!
