### ISSUE TITLE
inclusive zrange

### ISSUE THREAD

**Issue by polearnik** [redis/node-redis#2178]
How I can make  exclusive range with `zrange`?  
I try 
```
await redis.zRange('ticks:' + pair, '(123', end) 
```
but it end with error
In file /commands/zrange.js I see that argument for min and max should be numbers

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/ZRANGE.ts#L19
`min` and `max` type is `RedisCommandArgument | number`, and `RedisCommandArgument` is `string | Buffer`
`await redis.zRange('key', '(123', '(456')` should work
