### ISSUE TITLE
Can nodejs redis error occur because of crawler?

### ISSUE THREAD

**Issue by BS-CURTIS** [redis/node-redis#2179]
**Environment:**
 - **Node.js Version**: v17.6.0
 - **Node Redis Version**: 4.0.6
 - **Platform**: Amazon Linux AMI VERSION="2018.03"
 - ** nestjs:8.0.0

Is there an error if the crawler connects repeatedly?

My code is as follows,

    private setRedisClient() {
            this.client = createClient({
                url: `redis://${process.env.REDIS_URL}:${process.env.REDIS_PORT}`,
                isolationPoolOptions: {
                    max: 10,
                    min: 0,
                    maxWaitingClients: 10,
                    fifo: true,
                    autostart: true,
                    idleTimeoutMillis: 30000,
                },
            });
    
            this.client.on('error', (e: any) => {
                throw e;
            });
        }

      public async getAll(key: string): Promise<any> {
        try {
            this.setRedisClient();
            await this.client.connect();
            const res = await this.client.hGetAll(key);
            await this.client.quit();
            return res;
        } catch (error) {
            console.log(error);
            return undefined;
        }
    }

Repeated refreshing of a page results in an error.

      ClientClosedError: The client is closed
          at RedisSocket.quit (/home/ec2-user/buyer-service/node_modules/@redis/client/dist/lib/client/socket.js:72:19)
          at Commander.QUIT (/home/ec2-user/buyer-service/node_modules/@redis/client/dist/lib/client/index.js:222:71)
          at RedisClient.getAll (/home/ec2-user/buyer-service/dist/infra/cache/redis/cache.redis.client.js:31:31)

I am not good at speaking English.

I ask for your help me.

**Comment by leibale** [comment]
There is no reason to `connect()` and `quit()` for every request - you should `connect()` when the server starts and `quit()` when you wanna close the server.

```javascript
const client = createClient({
  // ...
});

client.on('error', err => console.error('Redis Client Error', err));

await client.connect();

function getAll(key: string) {
    return client.hGetAll(key);
}
```

**Comment by BS-CURTIS** [comment]
Don't connected clients overflow without shutting down each time a request ends?
Is the connection automatically disconnected?

**Comment by leibale** [comment]
There is no reason to create a client per request - you should use one global client

**Comment by BS-CURTIS** [comment]
amazing

i did't know that..

thanks a lot!
