### ISSUE TITLE
Duplicate concurrent socket reconnects after connection is lost

### ISSUE THREAD

**Issue by TVrijdag** [redis/node-redis#2186]
Hi there, I've encountered an issue with the reconnect behaviour whenever a client (with active subscription(s)) loses its connection with the server. For instance, when the server shuts down manually.

I've managed to trace it back to [`#onSocketError`](https://github.com/redis/node-redis/blob/23b65133c9610c44f336199a1ea73e77a9b73bc7/packages/client/lib/client/socket.ts#L184) which may try to reconnect  more than once if called again when `#createSocket` succeeded while reconnecting. Once the duplicate sockets successfully connect again the client becomes unstable and behaves unreliable.

Validating whether `#isReady` is true before calling `#connect` in `onSocketError` seems to fix the problem, but I'm not sure whether this is a proper change as I'm not familiar with the codebase.

**Environment:**
 - **Node.js Version**: v17.9.0
 - **Redis Server Version**: v7.0.2
 - **Node Redis Version**: v4.2.0
 - **Platform**: Windows 11

**Comment by MatanYemini** [comment]
Unless you will share a bit more details about the creating connection part that you have (code / flow) it would be hard to help.

But in general, I would recommend using the common events for determining the client's connectivity status.
and once you have the ready event being called, use connect (wrap as a promise if you want and wait for it to resolve)

If you can share more details I will try to help pinpoint the issue. But maybe someone got it 🤷🏾

**Comment by TVrijdag** [comment]
Hey @MatanYemini, sorry for the late reaction! 

I've created a [small example](https://gist.github.com/TVrijdag/7e4f70b3f934f0ca965fc2165bd5bc1c) of the problem with the latest version of this module. Hopefully this helps to pinpoint the issue. 

The logs are from a single client which tries to reconnect with the server more than once and at the same time. The client needs to have at least one active subscription before the server shuts down. Once the server is back online the client successfully reconnects with more than one socket as can be observed from both server and client logs. The problem could also occur if the client only connects to a server that requires a password, thus without performing any action other than connect.

**Comment by TVrijdag** [comment]
This has been fixed by PR #2480
