### ISSUE TITLE
Features available in redisgraph.js is not in @redis/graph

### ISSUE THREAD

**Issue by phxgbl** [redis/node-redis#2189]
@leibale I was using redisgraph.js. Yesterday found a deprecation notice asking to move to @redis/graph. I couldn't find any migration guide for the same. I was relying mostly on Parameterized queries but cannot find the same in @redis/graph. Is that implemented?

**Comment by glen-s-abraham** [comment]
@leibale Also found no functionality to map replies to an object in proper formatting.
