### ISSUE TITLE
net.connect is not a function

### ISSUE THREAD

**Issue by glIrving** [redis/node-redis#2190]
import { createClient } from "redis";
const client = createClient();
await client.connect();
**Environment:**
 - **Node.js Version**: v16.13.2
 - **Redis Server Version**: v3.2.100
 - **Node Redis Version**: v4.2.0
 - **Platform**:  Windows 10

**Comment by grilhami** [comment]
Have you tried without the `await`?

**Comment by glIrving** [comment]
> Have you tried without the `await`?

no ，and now when i import the redis  in Express.js  it works

**Comment by leibale** [comment]
Are you trying to import the client in the browser? because thats not supported..

**Comment by glIrving** [comment]
> Are you trying to import the client in the browser? because thats not supported..

i use  the command 'npm i redis '  in my web-project

**Comment by leibale** [comment]
Node-Redis is not intended to run in the browser.
