### ISSUE TITLE
[Help Facing issue] Redis Nodejs Pub/Sub is not working as expected for different selected db

### ISSUE THREAD

**Issue by vis2021t** [redis/node-redis#2199]
I am using Nodejs and "redis" for a pub sub to hear for expired Events.

In default its working just fine but when I switch to a different selected db it just does not get subscribe but I am seeing the setex working properly

Here is my code:-

```
const redis = require("redis");

const pub = redis.createClient({ url: process.env.REDIS_URL });
pub.connect();
pub.configSet("notify-keyspace-events", "Ex");
pub.select(4).then(() => {
   pub.setEx('mm', 5, "lopl")

})


const sub = pub.duplicate();
sub.connect()
sub.select(4).then(() => {
   sub.subscribe("__keyevent@0__:expired", (key) => {
      console.log("key=> ", key)
   })
})

```

**Comment by leibale** [comment]
The format is `__keyevent@{db}__:{event}`, this should work:
```javascript
sub.subscribe('__keyevent@4__:expired', key => console.log(key, 'expired'));
```

BTW, you don't have to use the `SELECT` command on the subscriber

**Comment by vis2021t** [comment]
> The format is `__keyevent@{db}__:{event}`, this should work:
> 
> ```js
> sub.subscribe('__keyevent@4__:expired', key => console.log(key, 'expired'));
> ```
> 
> BTW, you don't have to use the `SELECT` command on the subscriber

Thanks a Lott aaa lottt dude u saved my life lmao
