### ISSUE TITLE
"Invalid protocol" when trying to connect to Elasticache Redis in Node.js

### ISSUE THREAD

**Issue by cmgchess** [redis/node-redis#2201]
Hello

I'm trying to connect an ElastiCache Redis to an Express server deployed on ECS.

I get the **Primary Endpoint** from ElastiCache as `blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com:6379`

In my server I try to connect like this

```javascript
const { createClient } = require("redis");
const pubClient = createClient({ url: 'blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com:6379' });
```
But when I check the ECS logs I see

```bash
/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:124
throw new TypeError('Invalid protocol');
^
TypeError: Invalid protocol
at Function.parseURL (/usr/src/app/node_modules/@redis/client/dist/lib/c...
```
Any help on what I might be missing
Thanks

**Comment by leibale** [comment]
this should fix it
```javascript
const pubClient = createClient({ url: 'redis://blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com:6379' });
```

**Comment by cmgchess** [comment]
Thanks!

Now I'm getting a `Redis error ConnectionTimeoutError....` exactly similar to https://github.com/redis/node-redis/issues/1656. after looking at the stack trace
but anyway this should mean I connected to Redis at least once?

**Comment by leibale** [comment]
Have you tried connecting using `redis-cli`?

**Comment by cmgchess** [comment]
i tried with that too 
`C:\WINDOWS\system32>redis-cli -h blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com -p 6379`

and got 
`Could not connect to Redis at blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com:6379: Unknown error not connected>`

even whitelisted my IP in inbound rules of security group  
and then found [this](https://serverfault.com/questions/738923/connect-remotely-to-elasticache-redis)  
i'll try some other things as well

**Comment by cmgchess** [comment]
However I managed to connect to it from an AWS EC2 using EC2 Instance Connect.

**Comment by cmgchess** [comment]
I guess this is how it behaves and I cannot access elasticache from a local machine without SSH. Anyway it works fine inside the cloud. 
closing this
Thanks for helping me out!

**Comment by spm999** [comment]
> this should fix it
> 
> ```js
> const pubClient = createClient({ url: 'redis://blablabla.mccjet.ng.0001.euc1.cache.amazonaws.com:6379' });
> ```

solved my problem, thanks
