### ISSUE TITLE
[ I seriously dont know what category thing it is] Something feels wrong here

### ISSUE THREAD

**Issue by vis2021t** [redis/node-redis#2203]
I have 2 function for 2 redis activities being called like:-

functiontz()
functionty()

functiontz is asking from a server a token and set token to redis db

Then functiontz can be called anytime as it is a socket based different call using redis info

Either I use to a promise to wait yes 

but I am seeing conflicts in redis-cli monitor

which leads to the functionty not selecting right db

And yea functionty can be called anytime but only after tz is finished so is promise will be ok? + Is this a bug conflict?

**Comment by leibale** [comment]
I don't think I got it, share some more details please?
