### ISSUE TITLE
`eval` and `sendCommands` methods return an error with any arguments

### ISSUE THREAD

**Issue by dfenerski** [redis/node-redis#2206]
If I am missing something, which is highly likely, this is not a bug report, for which I am sorry.

However there seems to be no way to invoke neither `eval`, nor a `sendCommands`  methods.

I've literally ran `await client.sendCommand(['HGETALL', 'key']); ` from the npm docs and was greeted  by 
![image](https://user-images.githubusercontent.com/48520530/180067872-c274e1a7-cb3d-4ceb-abff-37250f41db35.png)

My main goal is to however do a basic `eval` to delete multiple keys by pattern. I tried  
<pre>
        cacheClient.EVAL(
            `return redis.call('del', 'defaultKey', unpack(redis.call('keys', ARGV[1])))`,
            {
                arguments: ['someKey'],
            },
        );
</pre>
However with any combination of values for the `arguments`, or `keys` arrays I get the error message 
![image](https://user-images.githubusercontent.com/48520530/180068133-313679f9-af3e-4257-ba48-160c74c12e4b.png)
I get it even if I run very basic commands like eval(`return val`)!

Am I missing something or doing something wrong? Any help is highly appreciated!

**Comment by leibale** [comment]
Which version of node-redis are you using? (`npm ls redis`)

**Comment by dfenerski** [comment]
Well it seems I have both 3 and 4 
![image](https://user-images.githubusercontent.com/48520530/180158146-a82f4575-b9dd-432c-9f19-5cff25842260.png)

I would prefer to use v4, but `cache-manager-redis-store`'s latest version is 2, with an internal dep to v3. Could this be the conflict?

**Comment by ebuxk** [comment]
Using redis@4.2.0. I also seem to be having this issue using eval and evalSha. Haven't tested anything else.
eval does not seem to be passing the parameters properly.
```
r1 = await client.eval('return KEYS[1]', 1, 'test-key', 'test-arg');
r2 = await client.eval('return ARGV[1]', 1, 'test-key', 'test-arg');
// r1 and r2 are both null at this point
```

**Comment by leibale** [comment]
@dfenerski @ebuxk 
```javascript
// v4:
console.log(
  await v4Client.eval('return KEYS[1]', { keys: ['key'] }), // 'key'
  await v4Client.eval('return ARGV[1]', { arguments: ['argument'] }) // 'argument'
);

// v3:
v3Client.eval('return KEYS[1]', '1', 'key', (err, reply) => {
  console.log(reply); // 'key'
});
v3Client.eval('return KEYS[1]', '0', 'argument', (err, reply) => {
  console.log(reply); // 'argument'
});
```

**Comment by ebuxk** [comment]
That syntax worked for me with a v4 client. Thanks!

**Comment by leibale** [comment]
@ebuxk BTW, you can defined lua scripts in `createClient`/`createCluster` to make it a little bit more efficient, [see here](https://github.com/redis/node-redis#lua-scripts)

**Comment by dfenerski** [comment]
@leibale the issue still persists on my side!
![image](https://user-images.githubusercontent.com/48520530/181879865-21840f5b-12ea-4f6a-8a13-7cde2ea96394.png)
given 
![image](https://user-images.githubusercontent.com/48520530/181879882-ac4df50d-bbde-4392-a5f7-b5484dd9097d.png)

**Comment by leibale** [comment]
@dfenerski this error message is coming from a v3 client, try to use the v3 API or use a v4 client
