### ISSUE TITLE
ReplyError: MOVED on cluster configuration

### ISSUE THREAD

**Issue by chris-elmstone** [redis/node-redis#2208]
I feel like I am missing something obvious, but whenever I talk to the cluster I get the following error:

 Unhandled Rejection at: Promise Promise {
`ReplyError: MOVED 7918 <IP>
  at parseError (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:179:12)
  at parseType (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:302:14)
 This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ReplyError: MOVED 7918 <IP>
  at parseError (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:179:12)
  at parseType (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:302:14)
Unhandled Rejection at: Promise Promise {
  <rejected> ReplyError: MOVED 7918 <IP>
   at parseError (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:179:12)
   at parseType (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:302:14)
 } reason: ReplyError: MOVED 7918 <IP>
  at parseError (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:179:12)
  at parseType (/home/lynx/www/lynxcloud-api-nightly/node_modules/redis-parser/lib/parser.js:302:14)`

Everything looks like it is configured correctly, and looking at the documentation this indicates the client is not following the redirects, all IP addresses are pointing to our 2nd master node.

Any suggestion on a possible fix, as I am pretty sure this is more of a configuration issue then a node-redis issue, but unsure what else I can try, I have increased the maxCommandRedirections to 100, useReplicas to true but nothing seems to fix this issue.

I will look forward to your reply

**Comment by chris-elmstone** [comment]
No subcommand SHARDS, running CLUSTER SHARDS I get the following: ERR Unknown subcommand or wrong number of arguments for 'SHARDS'. Try CLUSTER HELP

Running CLUSTER HELP gives the following output

 1) CLUSTER <subcommand> arg arg ... arg. Subcommands are:
 2) ADDSLOTS <slot> [slot ...] -- Assign slots to current node.
 3) BUMPEPOCH -- Advance the cluster config epoch.
 4) COUNT-failure-reports <node-id> -- Return number of failure reports for <node-id>.
 5) COUNTKEYSINSLOT <slot> - Return the number of keys in <slot>.
 6) DELSLOTS <slot> [slot ...] -- Delete slots information from current node.
 7) FAILOVER [force|takeover] -- Promote current replica node to being a master.
 8) FORGET <node-id> -- Remove a node from the cluster.
 9) GETKEYSINSLOT <slot> <count> -- Return key names stored by current node in a slot.
10) FLUSHSLOTS -- Delete current node own slots information.
11) INFO - Return onformation about the cluster.
12) KEYSLOT <key> -- Return the hash slot for <key>.
13) MEET <ip> <port> [bus-port] -- Connect nodes into a working cluster.
14) MYID -- Return the node id.
15) NODES -- Return cluster configuration seen by node. Output format:
16)     <id> <ip:port> <flags> <master> <pings> <pongs> <epoch> <link> <slot> ... <slot>
17) REPLICATE <node-id> -- Configure current node as replica to <node-id>.
18) RESET [hard|soft] -- Reset current node (default: soft).
19) SET-config-epoch <epoch> - Set config epoch of current node.
20) SETSLOT <slot> (importing|migrating|stable|node <node-id>) -- Set slot state.
21) REPLICAS <node-id> -- Return <node-id> replicas.
22) SLOTS -- Return information about slots range mappings. Each range is made of:
23)     start, end, master and replicas IP addresses, ports and ids

**Comment by leibale** [comment]
`CLUSTER SHARDS` was added in redis 7, try `CLUSETR SLOTS` instead
