### ISSUE TITLE
Support TDIGEST.MERGESTORE and make compression optional on TDIGEST.CREATE

### ISSUE THREAD

**Issue by chayim** [redis/node-redis#2216]
New changes for [the RedisBloom 2.4 milestone](https://github.com/RedisBloom/RedisBloom/pull/487) mean we have API changes to make prior to the next milestone.

**Comment by filipecosta90** [comment]
The new command has been merged and documentation updated to include it. 
More info in:
https://redis.io/commands/tdigest.mergestore/
