### ISSUE TITLE
Cannot connect with Node 18

### ISSUE THREAD

**Issue by netwarp** [redis/node-redis#2220]
This is my code:

```
import { createClient } from 'redis';

const client = createClient();

client.on('error', (err) => console.log('Redis Client Error', err));

await client.connect();
```

On Nodejs 16, it's work.
On Nodejs 18, I have this error:

Redis Client Error Error: connect ECONNREFUSED ::1:6379

**Environment:**
 - **Node.js Version: 18
 - **Redis Server Version: 7.0.2
 - **Node Redis Version: 4.2.0
 - **Platform: WIndows

Thanks for your help

**Comment by netwarp** [comment]
I had to set the url
`const client = createClient({ url: 'redis://127.0.0.1:6379' })`

**Comment by sangnguyendev** [comment]
> I had to set the url `const client = createClient({ url: 'redis://127.0.0.1:6379' })`

Help full!

**Comment by akhor93** [comment]
I replaced localhost with 127.0.0.1 in my url to get it working

**Comment by matzmz** [comment]
I have encountered the same issue. Could you please provide an explanation as to why it occurs? Additionally, I've checked the host file and confirmed that localhost entries are present.

**Comment by cfacundo** [comment]
> I replaced localhost with 127.0.0.1 in my url to get it working

it's incredible that this fix actually works
