### ISSUE TITLE
JSON.MGET doesn't work?

### ISSUE THREAD

**Issue by Syirrus** [redis/node-redis#2223]
When I attempt to call client.json.mget() i get an error: TypeError: Invalid argument type.
When I use client.json.get() everything works. 

Are you guys having the same behavior with mget?

Syirrus

**Comment by leibale** [comment]
Try
```javascript
await client.json.mGet(['key1', 'key2'], '$');
```

**Comment by Syirrus** [comment]
> Try
> 
> ```js
> await client.json.mGet(['key1', 'key2'], '$');
> ```

Dude, thank you. I'm not sure why I was sleeping on the '$'.
It worked!
