### ISSUE TITLE
HSETNX returns invalid argument type error

### ISSUE THREAD

**Issue by thepasterover** [redis/node-redis#2225]
HSETNX returns invalid argument type error while HSETX works fine. HSETNX also works on redis-cli directly;

Here's the code:
```
const setHashKeyNX = async (hKey, key, value) => {
    try {
        if(!value) {
            value = ''
        } else {
            value = JSON.stringify(value)
        }
        await redis.hSetNX(hKey, key, value)
    } catch (err) {
        logger.error('Error setting data to redis'+ err);
        throw err
    }
}
```

Here's the error
`Invalid argument type`

**Environment:**
 - **Node.js Version**: v16.15.0
 - **Redis Server Version**: 7.0.4
 - **Node Redis Version**: "redis": "^4.2.0"
 - **Platform**: MacOs Monterey 12.4

**Comment by leibale** [comment]
Make sure that `hKey` and `key` are string or Buffer.
on top of that, I think that I'll add some more info in the "Invalid argument type" error.

**Comment by thepasterover** [comment]
hKey is a string named `'users_queue'` and key `'some randome number'`. It works perfectly fine with `hSet` meanwhile without any errors!

**Comment by leibale** [comment]
use `toString()` on the random number, it should solve it

**Comment by thepasterover** [comment]
Works. Thanks! Please add a more descriptive error. Appreciate the work you have done!
