### ISSUE TITLE
Redis config applying does not prevent connection timeout

### ISSUE THREAD

**Issue by on21life** [redis/node-redis#2227]
# Situation
code
![image](https://user-images.githubusercontent.com/40256435/183801811-42b41cce-7f36-41e6-9fa3-bb97f180db7c.png)
console
![image](https://user-images.githubusercontent.com/40256435/183801765-d400789a-80a9-4159-a41b-46d9952d9869.png)

# Description
In normal execution, the connection is successful.
The problem occurs when debugging.

After calling the connect method of the created redisClient , there is no problem if it pauses for 5 seconds and resumes. 
But when I pause 5 seconds on the next line and then resume it, the problem arises.

# Try
I can't figure out whether it's dropping on the server or the client, so I've increased all settings to unlimited or 10x.

-  server-side setting
103) "shutdown-timeout"
104) "10"

107) "cluster-node-timeout"
108) "5000"

167) "repl-timeout"
168) "60"

177) "timeout"
178) "0"
-  client-side setting
![image](https://user-images.githubusercontent.com/40256435/183803091-eca2e407-87e4-459a-a0dd-8baae0cf5a1a.png)

**Environment:**
 - **Node.js Version**: node -v v14.18.2
 - **Redis Server Version**: redis-server -v Redis server v=7.0.0 sha=00000000:0 malloc=libc bits=64 build=fa9ffba7836907da
 - **Node Redis Version**: ls redis└── redis@4.1.0 
 - **Platform**: sw_vers
ProductName:    macOS
ProductVersion: 12.0.1
BuildVersion:   21A559

**Comment by leibale** [comment]
`connect_timeout` is a configuration for v3, try
```javascript
createClient({
  socket: {
    connectTimeout: 100000
  }
});

**Comment by on21life** [comment]
> `connect_timeout` is a configuration for v3, try
> 
> ```js
> createClient({
>   socket: {
>     connectTimeout: 100000
>   }
> });
> ```

I tried it and it works! thank you for your answer
