### ISSUE TITLE
Types: Expose default modules

### ISSUE THREAD

**Issue by tobiasdiez** [redis/node-redis#2241]
`RedisModules` is just a generic type from `@redis/client` and not the default modules in `redis`, which should be exported as well.

This makes it possible to more easily specify the generic module argument of `RedisClientType`.

_Originally posted by @leibale in https://github.com/redis/node-redis/issues/1865#issuecomment-1222720972_

**Comment by leibale** [comment]
@tobiasdiez I totally forgot about it, but `RedisDefaultModules` is already exported (see https://github.com/redis/node-redis/blob/master/index.ts#L33). You need `modules` as well?

**Comment by tobiasdiez** [comment]
RedisDefaultModules is indeed working for my needs.
