### ISSUE TITLE
Redis Json GET command ignores args

### ISSUE THREAD

**Issue by talsabagport** [redis/node-redis#2251]
Hi,
The new version `redis@4.3.0` includes upgrade to `@redis/client`. One of the changes is the following [PR](https://github.com/redis/node-redis/pull/2160), which includes change to Redis Json `GET` command ([ac032d8#diff-aed1769467eb9d697c271e34e506bb55893f8491c91eefb4f5f1694db37b87c2R20](https://github.com/redis/node-redis/commit/ac032d82a00c98b7b1efe1e1c4a49deda8f44581#diff-aed1769467eb9d697c271e34e506bb55893f8491c91eefb4f5f1694db37b87c2R20)):
![image](https://user-images.githubusercontent.com/110089894/188315124-7366f21d-1a82-4e74-83e6-2417473e2caa.png)

However it is not part of the last version of `@redis/json` - `1.0.3` (released before the PR was merged), which is a dependency of `redis@4.3.0` (and therefore the change is missing from its `dist/`).
The impact is that Redis Json `GET` command ignores the args it gets (because `pushVerdictArguments`  function behavior was changed).
The solution probably is to release new version to `@redis/json`, and use it as a dependency for `redis@4.3.0`.

**Comment by leibale** [comment]
@talsabagport sorry about that, fixed in `redis@4.3.1`/`@redis/json@1.0.4`
