### ISSUE TITLE
Should legacyMode be 10x faster than async/await?

### ISSUE THREAD

**Issue by v-flashpoint** [redis/node-redis#2252]
Hi all,

I have a leaderboard for a live game I'm continuing to benchmark, where I'm trying to get the results for all 30,000 players, to send them their positions. I've written a bit of a benchmark as my leaderboard code seemed to be creating a bit of a bottleneck, and was surprised to find that the performance using the new async/await syntax appears to be 10x slower than using legacyMode. 

Here's the code I'm using in the benchmark. First I create a js array to match my test Redis Sorted Set, then I iterate through, getting the player's position on the main leaderboard, and the player's position on the team leaderboard, before sending them a snapshot of the players around them from the main leaderboard:

```
const { performance } = require('perf_hooks');
const rediscon = require('redis');

// legacy or new
var type = 'legacy';

if(type == 'legacy'){
    var opts = {legacyMode: true};
}

const redis = rediscon.createClient(opts);

redis.connect();

// Snipped code here creating a mock players object called ev
format: ev = {users: {un: username, tid: teamid}, teams: {tid: {tn: team name}} //

var lb = {};
var target = 30000;

async function getdata(){
    console.log('getting data');

    var start = performance.now();
    var redisstart = 0;
    if(type == 'legacy'){
        redis.time((err,reply) => {
            redisstart = reply;
            console.log(redisstart);
        });
    }
     
    var received = 0;
    for(i = n; i < target; i++){
        var user = ev.users[i];

        if(type == 'legacy'){
            redis.zRevRank('lb', (err, reply) => {
                if(err){
                    console.log(err);
                }else{
                    var playerrank = reply;

                    redis.zRevRank('tlb', ev.teams[user.tid]['tn'], (err, reply) => {
                        var teamrank = reply;
                    });
    
                    if(playerrank < 2){
                        var lbstart = 0;
                        var lbend = 4;
                    }else{
                        var lbstart = playerrank - 2;
                        var lbend = playerrank + 2;
                    }
    
                    redis.zRange('lb', lbstart, lbend, 'REV', 'WITHSCORES', (err, reply) => {
                    
                        lb[received] = reply;
                        received++;

                        if(received == target){
                            redis.time((err,reply) =>{
                                redisend = reply;
                                showstats(lb);
                            });
                        }
                    });
                }
            });
        }else{
            var playerrank = await redis.zRevRank('lb',user.un);
            
            if(user.tid){
                var teamrank = await redis.zRevRank('tlb', ev.teams[user.tid]['tn']);
            }
                
            if(playerrank < 2){
                var lbstart = 0;
                var lbend = 4;
            }else{
                var lbstart = playerrank - 2;
                var lbend = playerrank + 2;
            }
                         
            lb[i] = await redis.zRangeWithScores('lb', lbstart, lbend, {'REV': true});
        }
    }

    if(type != 'legacy'){
        var redisend = await redis.time();
        if(redisend){
            showstats(lb);
        }else{
            console.log('err');
        }
    }

    async function showstats(result){
        var end = performance.now();
        console.log('result');
        console.log( result);

        if(type == 'legacy'){
            redisstart = (parseInt(redisstart[0]) * 1000) + (parseInt(redisstart[1]) / 1000);
            redisend = (parseInt(redisend[0]) * 1000) + (parseInt(redisend[1]) / 1000);
        }

        var execution_time = redisend - redisstart; // in milliseconds
        var retrievedin = (end - start);
        console.log('Execution time: '+execution_time);
        console.log('Retrieved in '+retrievedin+' ms');
    }
}
  
getdata();

    
redis.on('error', function (er) {
    console.trace('Error'); 
    console.error(er.stack); 
});

```

When using the modern async/await syntax, this function return in 9.5s. In legacyMode with all of its callback hell, it takes .95s. 

I just wanted to ask if I'm doing something wrong with my promises, or is this just the overhead penalty you can expect for doing promises in a tight loop?

**Environment:**
 - **Node.js Version**: 14.19.0
 - **Redis Server Version**: 7.0.4
 - **Node Redis Version**: 4.0.4
 - **Platform**: Ubuntu 20.04.4

**Comment by v-flashpoint** [comment]
I should note that I also don't appear to be able to access the modern syntax when using legacyMode. Commands like 

`var time = await redis.time()`

just return "undefined", unless I disable legacyMode, which is contrary to what the migration guide suggests (https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md). As mentioned in #2085 , the only way to access the result is through a callback, making it more of a hybrid approach and requiring extensive code modification rather than just being able to use the odd legacyMode command here or there.

**Comment by v-flashpoint** [comment]
Seemingly it's just me. Turns out it's just the way I'm stacking the awaits. If I use callbacks instead (with .then()), the performance comes right back up. I don't believe it's documented, but in case anyone else is looking for performance in future, instead of e.g. 

`lb[i] = await redis.zRangeWithScores('lb', lbstart, lbend, {'REV': true});`

You can do

` redis.zRangeWithScores('lb:'+eventid, lbstart, lbend, {'REV': true}).then(async (reply, err) => {`

I haven't seen it documented that this is possible, or which way round the replies come (or even if this will return an err if one happens), but it's helped me.

**Comment by victusfate** [comment]
Friendly suggestion -> @v-flashpoint you may want to collect all your promises and then exec a Promise.all(allYourPromises). If you await individual queries it'll run serially / block which can definitely slow you down
