### ISSUE TITLE
optional COUNT for XRANGE

### ISSUE THREAD

**Issue by soundust** [redis/node-redis#2254]
I'm trying to read a single entry in a redis stream using XRANGE, however it looks like node-redis XRANGE returns the whole stream? are the optional 'COUNT' parameters not implemented in node-redis?

```javascript
import { createClient } from 'redis'

const redis_xrange = async (k) => {
    const client = createClient()
    try {
        if (!client.isOpen)
            await client.connect()
        const result = await client.XRANGE(k, '-', '+', 'COUNT', 1)
        await client.quit()
        return result
    } catch (e) {
        return {error: e.message}
    }
}

const result = await redis_xrange('my-stream')

console.log(Object.keys(result).length)
```

I realise I can use UNIX timestamp to specify a time-range to retrieve, but how do I get the last entry if the stream "posts" are posted at irregular intervals?

**Comment by leibale** [comment]
this should workd:
```
await client.XRANGE(k, '-', '+', {
  COUNT: 1
})
```

**Comment by soundust** [comment]
thanks @leibale !
I actually got it to work using the following:

`await client.sendCommand(['XRANGE', k, '+', '-', 'COUNT', '1'])`
