### ISSUE TITLE
How To Use UDS（Unix Domain Socket） To  Connect

### ISSUE THREAD

**Issue by mayuehit** [redis/node-redis#2255]
import { createClient } from "redis";

const client = createClient("/opt/sidecar/watch/server.sock");
client.on('error', err => console.log('Redis Client Error', err));
await client.connect()
const resource = {
    "instrumentInst": "glb",
    "resources": {
        "resourceTemplate": "res_caas_glb_group",
        "version": "1.0.0",
        "attributes": [
            {
                "namespace": "manager",
                "group_name": "default",
            }
        ]
    }
};
const result = client.sendCommand(["resource.put", "JSON", JSON.stringify(resource)])
console.log(result)

**_that is what I do ,and console show  Redis Client Error,So How do I use correctly_**

**Comment by leibale** [comment]
this should work:

```javascript
const client = createClient({
  socket: {
    path: '/opt/sidecar/watch/server.sock'
  }
});
```

see https://github.com/redis/node-redis/blob/master/docs/client-configuration.md
