### ISSUE TITLE
The client.isOpen is true even when the connection has failed during client.connect(), if redis server is not online.

### ISSUE THREAD

**Issue by 24x7soumya** [redis/node-redis#2257]
**Environment:**
 - **Node.js Version**: v16.11.1
 - **Redis Server Version**: Any
 - **Node Redis Version**: 4.3.1
 - **Platform**: Ubuntu 20.04.3, Windows 10

**Comment by leibale** [comment]
`client.isOpen` = is the client open (which doesn't necessarily mean the socket is open/ready).
`client.isReady` = is the current socket open and ready for use.

**Comment by 24x7soumya** [comment]
Thanks @leibale.
What is the utility of isOpen, then?

**Comment by leibale** [comment]
`isOpen` is for the client to know if the socket needs to reopen

**Comment by leibale** [comment]
@24x7soumya can I close this issue?

**Comment by 24x7soumya** [comment]
Yes @leibale .
Thanks.

**Comment by Dhruv-Garg79** [comment]
I am facing the same issue.
isOpen is true even after connection is broken, so isReady becomes false.

the problem is I can't call client.connect() or client.disconnect() when isOpen = true and isReady = false

**Comment by edkimmel** [comment]
@leibale I have seen a similar problem here.  It's my understanding that isOpen=true, isReady=false should indicate that node-redis is actively trying to connect / reconnect, but I have had some situation around socket closed unexpectedly where I am left in this state without reconnecting ever being attempted.

**Comment by EngineerReversed** [comment]
The script doesn't work in existing form.
Link: https://github.com/redis/node-redis/blob/da3face95180d5ab801716de1ff4ba97e6cbb6ab/examples/check-connection-status.js

I had to modify to this
```
// Check the connection status of the Redis client instance.
const redis = require('redis');

const client = redis.createClient();

console.log('Before client.connect()...');

// isOpen will return False here as the client's socket is not open yet.
// isReady will return False here, client is not yet ready to use.
console.log(`client.isOpen: ${client.isOpen}, client.isReady: ${client.isReady}`);

// Begin connection process...
// const connectPromise = client.connect();
const connectPromise = (async () => { await client.connect() })();

console.log('After client.connect()...');

// isOpen will return True here as the client's socket is open now.
// isReady will return False here as the promise hasn't resolved yet.
console.log(`client.isOpen: ${client.isOpen}, client.isReady: ${client.isReady}`);

// await connectPromise;
console.log('Afer connectPromise has resolved...');

// isOpen will return True here as the client's socket is open now.
// isReady will return True here, client is ready to use.
console.log(`client.isOpen: ${client.isOpen}, client.isReady: ${client.isReady}`);

(async () => { await client.quit() })();

```

However, I am getting `isReady` always set to `false`
```
Before client.connect()...
client.isOpen: false, client.isReady: false
After client.connect()...
client.isOpen: true, client.isReady: false
Afer connectPromise has resolved...
client.isOpen: true, client.isReady: false
```

Although, I am able to set a key, value pair in redis database.

Any thoughts on how to resolve this?

**Comment by leibale** [comment]
@EngineerReversed the `check-connection-status.js` assume top-level-await works in your environment (node >= 14.8.0), I guess this is why it's not working for you. To make it work you can wrap the whole script (excluding imports) with an "[async IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)".

The reason your modified version prints
```
After connectPromise has resolved...
client.isOpen: true, client.isReady: false
```
is that you commented out this line:
```javascript
await connectPromise;
```
so the `connectPromise` is indeed not resolved when the console.log is running..

**Comment by leibale** [comment]
@EngineerReversed this should work:
```javascript
// Check the connection status of the Redis client instance.
const redis = require('redis');

const client = redis.createClient({
    host: "127.0.0.1",
    port: 6379
});

client.on('error', (err) => console.log('Redis Client Error', err));
client.on('connect', () => console.log('Connected to Redis DB'));
client.on('ready', () => console.log('Ready to use Redis DB'));
client.on('end', () => console.log('Client disconnected from Redis DB'));

(async () => {
  await client.connect();

  // isOpen will return True here as the client's socket is open now.
  // isReady will return True here, client is ready to use.
  console.log(`client.isOpen: ${client.isOpen}, client.isReady: ${client.isReady}`);
})();

process.on('SIGINT', async () => {
    await client.disconnect();
    process.exit(0)
});

module.exports = client
```

**Comment by EngineerReversed** [comment]
Yes, that worked for me.

However, does that mean I can't use `client` outside of `async` based method? It would defeat the purpose since I want to use `client` across my module.
Or
Should I continue since it does not matter as I am still able to `GET` and `SET` my key and values?

**Comment by leibale** [comment]
@EngineerReversed It depends on the use case. If you have an HTTP server that cannot work without Redis (for example - all the sessions are stored in Redis) - don't call `server.listen` before `client.connect` resolves:
```javascript
// redis.js
const { createClient } = require('redis');

const client = createClient();
client.on('error', err => console.error('Redis Error Client');

module.exports.client = client;

// server.js
const { createServer } = require('node:http');
const { client } = require)('./redis');

const server = createServer();

module.exports.server = server;

(() => {
  await client.connect();
  // expose the server once the client is ready
  server.listen(process.env.PORT);
})();
```

**Comment by Adriansillo** [comment]
Looks like the problem persist 

My tests 

0. docker run -p 6379:6379  -dt --name redis redis
1. start docker redis `docker start redis`
2. start the project `npx ts-node redis_test.ts`
3. send a request `curl http://localhost:9090/image` expeted response `PONG`
4. stop the redis container `docker stop redis`
5. send a request `curl http://localhost:9090/image` expeted response `Redis client is not ready`
6. start docker redis again `docker start redis`
7. send a request `curl http://localhost:9090/image` expeted response `PONG`

Step 5 is failing, looks like it tries to reconnect and for some reason it says connection works but the redis server is down. so the connection status change to open and it does not try to reconnect again 

``` typescript
// filename redis_test.ts
import express from 'express';
import type { Request, Response } from 'express';
import { createClient } from 'redis';
import type { RedisClientType } from 'redis';


class RedisCredits {
  private redisClient: RedisClientType;

  constructor(redisUrl: string) {

    this.redisClient = createClient({
      url: redisUrl,
      pingInterval: 5000,
      socket: {
        reconnectStrategy: (retries) => {
          const delay = Math.min(retries * 1000, 15000); 
          console.log(`Attempting reconnection (Attempt ${retries}). Next retry in ${delay / 1000}s...`);
          return delay;
        },
      },
    });

    this.redisClient.on('error', (err) => {
      console.log('Redis Client Error:', err);
    });

    this.redisClient.on('reconnecting', (opts) => {
      console.log('Lost connection to redis, retrying', JSON.stringify(opts));
    });

    this.redisClient.on('connect', () => {
      console.log('Connected to Redis');
    });

    this.redisClient.connect();
  }

  public ping(): Promise<string> {
    if (!this.redisClient.isReady) {
      throw new Error('Redis client is not ready');
    }
    return this.redisClient.ping();
  }
}

const app = express();  

const redisCredits = new RedisCredits('redis://localhost:6379');
app.get('/image', async (req: Request, res: Response): Promise<void> => {
  console.info("Hello logs!", { structuredData: true });
  let browser: any = null;
  try {
    const ping = await redisCredits.ping();
    res.send(ping);
  } catch (err) {
    console.error(err);
    res.send("ERROR");
  } finally {
    browser?.close();
  }
});

app.listen(9090, (): void => console.log('Listening on PORT: 9090'));

```
