### ISSUE TITLE
How to implement RETURN AS

### ISSUE THREAD

**Issue by akelmj** [redis/node-redis#2259]
https://github.com/redis/node-redis/blob/def9f161e5d63657b5793e66d0db451020781d17/packages/search/lib/commands/SEARCH.ts#L30

options.RETURN can get array of properties , How to get it work with return AS , for example :

`FT.SEARCH 'testIdx' '@brand:(lg)' RETURN 4 sku  $._supplier.name AS supplier_name`

`Client.ft.search(`testIdx` , '@brand:(lg)', {RETURN:['sku' , '$._supplier.name AS name' ]}); `

**Comment by leibale** [comment]
this should work
```javascript
client.ft.search(testIdx, '@brand:(lg)', {RETURN:['sku' , '$._supplier.name', 'AS ', 'name' ]});
```

**Comment by akelmj** [comment]
Thanks
