### ISSUE TITLE
Missing endpoint documentation for v3.1.2 

### ISSUE THREAD

**Issue by ignaciostellino** [redis/node-redis#2261]
I am missing the documentation for endpoints like  getAll, o hgetAll o hmgetall for the node redis version 3.1.2
Is throwing invalid number of arguments or invalid data type.
**Environment:**
 - **Node.js Version**: 10.24.1
 - **Redis Server Version**: 7.0
 - **Node Redis Version**: 3.1.2
 - **Platform**: Ubuntu

**Comment by leibale** [comment]
Checkout the [v3.1.2](https://github.com/redis/node-redis/tree/v3.1.2) tag
