### ISSUE TITLE
Question: Upgrade from @node-redis/client v1.0.6

### ISSUE THREAD

**Issue by rmtuckerphx** [redis/node-redis#2263]
I'm currently using @node-redis/client v1.0.6
I just want to clarify that I should move over to @redis/client v1.3.0
Correct?

I'm currently using this library against a Redis 3.
Will this work with Redis 5?

I'm only using the basics

```
const redis = require('@node-redis/client');

const client = redis.createClient({
    socket: { host: process.env.REDIS_HOST }
});

client.on('error', (err) => {
    log.error(err)
});

await client.connect();

await client.set(key, value, {
    EX: 1200,
    NX: true
});

const value = await client.get(key);
```

**Comment by leibale** [comment]
You can upgrade and it'll still work

**Comment by rmtuckerphx** [comment]
Thank you so much!
