### ISSUE TITLE
SDIFF not returning correct response

### ISSUE THREAD

**Issue by kylefarris** [redis/node-redis#2265]
If I add values to 2 different sets via `SADD` and then try to diff them using the `SDIFF` method, the wrong result is returned. But, if I run `sendCommand(['SDIFF', 'key1', 'key2'])` it returns the correct result.

**For Example:**
```javascript
import redis from 'redis';

const client = redis.createClient();
await client.connect();

const array1 = ['a', 'b', 'c', 'd', 'e', 'f', 'g'];
const array2 = ['d', 'c', 'f', 'a'];

await client.SADD('key1', array1);
await client.SADD('key2', array2);

const badDiff = await client.SDIFF('key1', 'key2');
console.log('Bad Diff: ', badDiff);
// Bad Diff: [ 'g', 'a', 'd', 'c', 'f', 'b', 'e' ] (Incorrect!)

const goodDiff = await client.sendCommand(['SDIFF', 'key1', 'key2']);
console.log('Good Diff: ', goodDiff);
// Good Diff: [ 'g', 'b', 'e' ] (Correct!)
```

It doesn't make a lot of sense why this would be happening but its easily verifiable.

**Environment:**
 - **Node.js Version**: 18.7.0
 - **Redis Server Version**: 7.0.4
 - **Node Redis Version**: 4.3.1
 - **Platform**: MacOS 12.5.1 & AlmaLinux 8.6

**Comment by matteomattei** [comment]
The SDIFF syntax is changed... it accepts array instead of single parameters.
So you should use this:

```
const badDiff = await client.SDIFF(['key1', 'key2']);
```

**Comment by kylefarris** [comment]
I can confirm that works, thanks!

Why is this one method different than most others? Is this change documented anywhere? If not, I can probably add that to some docs somewhere.

**Comment by leibale** [comment]
its documented [here](https://redis.js.org/documentation/client/functions/lib_commands_SDIFF.transformArguments.html) (and I know we should do better work at "exposing" this, please share any ideas you have... :) ).
The reason "spread" is not supported is to allow optional arguments in the future.

**Comment by kylefarris** [comment]
Is there a specific type of command that qualifies it to take arguments like this? Like all commands that take multiple "input" arguments (not quite sure how to describe it). Just trying to think of some verbiage that would make sense and be clear to users in the docs...

I was thinking of explaining which kinds of commands need this syntax, list a few of the commands that follow this format, and then show an example of it in action.
