### ISSUE TITLE
ts.mRangeWithLabels FILTER as an array of string not apply

### ISSUE THREAD

**Issue by PierreMasson** [redis/node-redis#2266]
ts.mRangeWithLabels no longer takes the FILTER parameter into account as an array.

**ERR TSDB: missing labels for filter argument**

Downgrading to redis 4.1.0 in my package.json do the job.

Maybe this commit #5dd7d3149a633b762ece0ce8006ecbb4311a547f is to blame?

**Environment:**
 - **Node.js Version**: 14.18.1
 - **Redis Server Version**: 6.2.7
 - **Node Redis Version**: 4.3.1
 - **Platform**: Debian GNU/Linux 11 (bullseye)

**Comment by Shepless** [comment]
@leibale any ETA on the fix being released please?

**Comment by leibale** [comment]
@Shepless it's not in `redis@4.4.0`?

**Comment by Shepless** [comment]
> @Shepless it's not in `redis@4.4.0`?

@leibale I still get the same error on `redis@4.4.0` when using the time series package `@redis/time-series@1.0.3`

ERR TSDB: missing labels for filter argument

**Comment by Shepless** [comment]
@leibale sorry to keep bothering you, is the above related to the same issue? If not, do you want me to open a new issue for it? Thank you, all of your work and effort is appreciated :smiley:

**Comment by leibale** [comment]
@Shepless sorry about that, should be fixed in `redis@4.5.0`/`@redis/time-series@1.0.4`

**Comment by TombolaShepless** [comment]
Thanks @leibale will give it a try this evening!
