### ISSUE TITLE
HGETALL Fails

### ISSUE THREAD

**Issue by muscleman** [redis/node-redis#2270]
Simple call to get a hash from redis

`let replies = await this.redisClient.multi().HGETALL('key')`

Response
`[  
[Object: null prototype] {
    lastBlockFoundsolo: '1663633916648',
    lastBlockFoundprop: '1663536743055'
  }
]`

**Environment:**
 - **Node.js Version**: 14.15.4
 - **Redis Server Version**: 6.2.7
 - **Node Redis Version**: 4.3.1
 - **Platform**: Ubuntu 18.04

**Comment by leibale** [comment]
Where is the error/problem? `replies` is an array with all the replies, and `replies[0]` is an the reply from `HGETALL`

**Comment by muscleman** [comment]
let me surround a console.log(replies[0]) so you understand my issue
