### ISSUE TITLE
What is the correct syntax for a Redis JSON SET call with the 'nx' flag in a Node.JS app?

### ISSUE THREAD

**Issue by roschler** [redis/node-redis#2277]
I have a `Node.JS` app that uses the `Redis` NPM module.  I am trying to set a JSON key to a specific value but ***only if it does not exist***.  The Redis JSON docs for the non-JSON `SET` call say:

https://redis.io/commands/json.set/
```
The optional subcommands modify this behavior for both new RedisJSON data type keys as well as the JSON Object keys in them:

NX - only set the key if it does not already exist
XX - only set the key if it already exists
```

So I tried the following syntax in my Redis JSON SET call:
```js
        const successFailCode = await (self.redisClient.json.set(redisKey, '$', worldConferenceInitializationCountObj,  'nx'))
```
But that does not work.  Every time I make that call it *always* sets the object instead of only executing the `SET` operation if the *key does not already exist*.

I tried inspecting the NPM `redis` code, but it is highly abstracted *Typescript* code that is hard for me to follow so I can determine the proper way, if it is at all possible, to pass the `NX` flag to the Redis JSON `SET` call.

**NOTE**: I know I can first make a `get` call to see if the key exists, and *then* do the `set` call, but that opens up my app to a potential *race condition* where one *client* checks to see if the key exists, finds out it does not, and then before it executes the `SET` operation *another client* executes its `SET` operation first.  So when the first *client* executes (erroneously) its `SET` call it overwrites the `SET` operation of the second *client*.

Can anyone give me the correct syntax for making the Redis JSON `SET` call using the `NX` flag?

**Comment by simonprickett** [comment]
Hi there,

Try:

```javascript
const successFailCode = await self.redisClient.json.set(
  redisKey, 
  '$', 
  worldConferenceInitializationCountObj,  
  {
    NX: true
  }
)
```

I agree that this could be better documented, and am currently writing issues for Node Redis for our Hacktoberfest project.  Adding something like this to the `examples` folder will probably be one of those now!

Here's where I found the example for the above: https://github.com/redis/node-redis/blob/master/packages/json/lib/commands/SET.spec.ts

**Comment by roschler** [comment]
> ```js
>   {
>     NX: true
>   }
> ```

Hi Simon,

Thanks! That worked _great_.  

Some follow-up items for you and probably some more text that might go into the docs?

1) I get back `null` from the `await self.redisClient.json.set()` call.  The call works fine, but what is the significance of the `null` value?  In other words, what other values might I get back if that call does not `throw`?

2) A doc note on the return of `JSON.numIncrBy` would be helpful too.  I have noticed that if the path is incorrect (i.e. - there is no element to increment with the given key path), you get back an _empty array_ as the call result.  But if it succeeds, if you had a single path in your call, you get back _an array with one element set to the updated value for the JSON field the path resolves to_.  I'm guessing that if there are multiple paths in your path expression you will get back an array equal in length to the number of paths in your call parameters that led to a successful increment operation, with each array element being the corresponding updated value that resulted from each successful increment operation?  Or does it omit elements for any paths that were invalid (which would be a bit of a headache)?

**FEATURE SUGGESTION**: I would like to see an enhancement to `numIncrBy` where you could pass a flag in the options parameter that makes the call `throw` if _any_ path fails, and in that case, the returned error object contains an array of the invalid paths.  In fact, it would be very helpful to have that "flag" for any of the calls that accept paths.

**Comment by devSajan** [comment]
how can we set multiple data? can we use an array of objects?
```js
redisClient.json.set([{
    redisKey, 
    '$', 
     worldConferenceInitializationCountObj,  
     {
       NX: true
     }
   },
   .....
 ])
```

**Comment by leibale** [comment]
you can call `redisClient.json.set` multiple times and use `Promise.all` to wait for all of them:
```javascript
await Promise.all([
  client.json.set('1', '$', {}),
  client.json.set('2', '$', {})
  // ...
]);
```
