### ISSUE TITLE
Add example script showing how to connect to a Redis open source cluster.

### ISSUE THREAD

**Issue by simonprickett** [redis/node-redis#2281]
Add an example script that shows how to connect to a Redis open source cluster.  Your example can be based on the "Basic Example" code here:  https://github.com/redis/node-redis/blob/master/docs/clustering.md

Name your file `connect-to-cluster.js`.  Pay attention to the [guidelines for adding an example](https://github.com/redis/node-redis/tree/master/examples#coding-guidelines-for-examples) to ensure that your contribution can be merged.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by con-mark** [comment]
@simonprickett  @SuzeShardlow  I would be interested in doing this but might not get it done till the weekend not sure if you want to assign it elsewhere

**Comment by Shamik1836** [comment]
@simonprickett @SuzeShardlow I can work on this and get this issue resolved today only if you assign this to me

**Comment by SuzeShardlow** [comment]
> @simonprickett @SuzeShardlow I would be interested in doing this but might not get it done till the weekend not sure if you want to assign it elsewhere

@con-mark, thanks for your message. We will assign this elsewhere as you suggest, but please keep your eyes peeled because we will be adding more issues in the coming days and weeks.

You can view our latest open issues at https://redis.io/community/hacktoberfest 😀

**Comment by Shamik1836** [comment]
Hi, can you please help me in finding some information about open source cluster, since this is my first open source contribution, I don't know where to get information about this but I really want to contribute to this issue.

**Comment by SuzeShardlow** [comment]
This issue is available and up for grabs.  Please tag me and @simonprickett if you would like to work on it.

**Comment by vajid2113** [comment]
Hello, I would like to work on this issue @SuzeShardlow @simonprickett

**Comment by SuzeShardlow** [comment]
Hi @vajid2113, I have assigned this to you :) we look forward to receiving your PR in a couple of days.  Please check out our guidelines and have fun!

https://redis.io/community/hacktoberfest

**Comment by SuzeShardlow** [comment]
Hi @vajid2113, how are you doing with this? :)

**Comment by varadkarpe** [comment]
@SuzeShardlow 
If there are no updates regarding this issue from others I would like to contribute to this, I can get it done within 2 calendar days.

**Comment by SuzeShardlow** [comment]
@varadkarpe I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/

**Comment by varadkarpe** [comment]
Hey @SuzeShardlow 
I am trying to push my code but I am facing an error, it says : 
`Permission to redis/node-redis.git denied to varadkarpe.
fatal: unable to access 'https://github.com/redis/node-redis.git/': The requested URL returned error: 403`

Can you please help me out?

**Comment by SuzeShardlow** [comment]
Hi @varadkarpe, you can't push to our repo (as you've discovered) - you will have to fork the repo and make your changes there.  Then push to your fork and open a PR against our repo.

Have a look at these instructions:

https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by varadkarpe** [comment]
#2298 
I have made the PR, kindly review it.
