### ISSUE TITLE
ft.aggregate does not return expected values

### ISSUE THREAD

**Issue by Ducharme** [redis/node-redis#2282]
ft.aggregate does not return the tag for the aggregated count in the results

This is the index
`FT.CREATE topic-h3-idx ON HASH PREFIX 1 DEVLOC: SCHEMA topic TEXT h3r0 TAG`

This is the data
`client.hSet(key, { 'deviceId': 'test001', 'topic': 'mytopic', 'h3r0': "802bfffffffffff"});`

With CLI results include both the property tag and the aggregated count
`FT.AGGREGATE topic-h3-idx "@topic:mytopic @h3r0:{ 802bfffffffffff }" GROUPBY 1 @h3r0 REDUCE COUNT 0 AS num_devices`

Response
```
1) (integer) 1
2) 1) "h3r0"
   2) "802bfffffffffff"
   3) "num_devices"
   4) "1"
```

When calling with redis library the property tag @h3r0 is not returned
```
this.client.ft.aggregate("topic-h3-idx", "@topic:mytopic @h3r0:{ 802bfffffffffff }", {
  STEPS: [{
    type: AggregateSteps.GROUPBY,
    property: "@h3r0",
    REDUCE: [{
      type: AggregateGroupByReducers.COUNT,
      AS: 'num_devices'
    }]
  }]
})
```
Response
`{ total: 1, results: [ [Object: null prototype] { num_devices: '1' } ] }`

Expectation is to have the tag h3r0 and its value included in the results
`{ total: 1, results: [ { h3r0: '802bfffffffffff', num_devices: '1' } ] }`

**Environment:**
 - **Node.js Version**:  16.13.1
 - **Redis Server Version**: 6.2.6 (redislabs/redisearch:latest)
 - **Node Redis Version**: 4.3.1
 - **Platform**: Ubuntu 20.04.3 LTS

**Comment by leibale** [comment]
it's `properties`, not `property`... this should work:

```javascript
this.client.ft.aggregate("topic-h3-idx", "@topic:mytopic @h3r0:{ 802bfffffffffff }", {
  STEPS: [{
    type: AggregateSteps.GROUPBY,
    properties: ["@h3r0"],
    REDUCE: [{
      type: AggregateGroupByReducers.COUNT,
      AS: 'num_devices'
    }]
  }]
})
```

**Comment by Ducharme** [comment]
Correct, thanks.
