### ISSUE TITLE
4.x should be compatible with Node v12, but client@1.1.0 dropped support in a feature release

### ISSUE THREAD

**Issue by kirrg001** [redis/node-redis#2283]
https://github.com/redis/node-redis/blob/master/CHANGELOG.md#v400---24-nov-2021
https://github.com/redis/node-redis/releases/tag/client%401.1.0

Node v12

**Comment by leibale** [comment]
Node 12 is "dead" https://github.com/nodejs/release#release-schedule

**Comment by kirrg001** [comment]
Doesn't matter if it is dead or not.
