### ISSUE TITLE
ErrorReply: MOVED with single client and Can't connect to node-redis cluster connection with password and host[port]. 

### ISSUE THREAD

**Issue by xtianus79** [redis/node-redis#2284]
I am running this because there is nothing I can do to connect to my cluster with all of the nodes. I don't know if I am doing something wrong but I need to connect to a cluster instead of the client option. Everything else I connect to with my cluster works. My broker. Redis insight works with cluster and moves correctly/redirect. 

Specifically when I use cluster it gives me an error that username and password is incorrect but I would think that using the same url format would work. Am I doing it wrong? This causing a lot of issues with my cluster so I have to connect with the cluster version of the client. 

``` javascript
this.client = createClient({
     url: 'redis://default:<my-password>@<1-IP of node in a cluster>:6379',
```

**Environment:**
 - **Node.js Version**: 16
 - **Redis Server Version**: 7.0.4
 - **Node Redis Version**: 4.3.1
 - **Platform**: Ubuntu/linux

**Comment by leibale** [comment]
In order to connect to a cluster you'll need to use the `createCluster` function

```javascript
import { createCluster } from 'redis';

const cluster = createCluster({
  // there is no need to specify all of them
  rootNodes: [{
    url: 'redis://<IP of node1 in a cluster>:6379'
  }, {
    url: 'redis://<IP of node2 in a cluster>:6379'
  }],
  defaults: {
    username: 'default',
    password: '<password>'
  }
});

cluster.on('error', (err) => console.log('Redis Cluster Error', err));

await cluster.connect();
```

see https://github.com/redis/node-redis/blob/master/docs/clustering.md for more details
