### ISSUE TITLE
Add example script showing use of Hyperloglog commands.

### ISSUE THREAD

**Issue by simonprickett** [redis/node-redis#2285]
Add an example script that shows the use of the `PFADD` and `PFCOUNT` and optionally `PFMERGE` commands (see [Redis Hyperloglog Commands](https://redis.io/commands/?group=hyperloglog).

Make sure to use a real world example of the need to approximately count something, for example cars passing by a traffic monitoring camera perhaps.  Check out our [Hyperloglog video](https://www.youtube.com/watch?v=MunL8nnwscQ) for examples.

Name your file `hyperloglog.js`.  Pay attention to the [guidelines for adding an example](https://github.com/redis/node-redis/tree/master/examples#coding-guidelines-for-examples) to ensure that your contribution can be merged.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by Mephalich** [comment]
Hi. I could work on this task.

**Comment by simonprickett** [comment]
@Mephalich thanks - we're aiming for a wide range of new contributors for Hacktoberfest, if this is still available in a week please check back but we'd like to ensure everyone gets a go at a first issue before assigning subsequent issues to folks who have already successfully completed one.

**Comment by ade1705** [comment]
Hi @simonprickett , I would like to work on this.

**Comment by SuzeShardlow** [comment]
This issue is still open and up for grabs :) please reply and tag me and @simonprickett if you'd like to work on it.

**Comment by ade1705** [comment]
Hi @simonprickett @SuzeShardlow I would like to work on this

**Comment by SuzeShardlow** [comment]
Hi @ade1705, I've assigned this one to you, look forward to seeing your PR in a couple of days.  Please check out our guidelines at the below link and have fun!

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
Hi @ade1705, how are you doing with this?  :)

**Comment by ade1705** [comment]
@SuzeShardlow almost done. Apologies for the delay

**Comment by ade1705** [comment]
@SuzeShardlow I have created a PR for it. Please have a look [here](https://github.com/redis/node-redis/pull/2289)

**Comment by SuzeShardlow** [comment]
Thanks @ade1705! We will take a look in our daytime 😀

**Comment by SuzeShardlow** [comment]
Closed by #2289.  Thanks @ade1705!
