### ISSUE TITLE
How to use lua scripts in v4?

### ISSUE THREAD

**Issue by jatinkumarg** [redis/node-redis#2291]
Noticed the support for `script()` has been removed in v4. Wondering how lua scripts can be loaded in v4? 

I'm trying to update the `node-redis` to v4 in `bee-queue` but getting issue with loading lua scripts [here](https://github.com/bee-queue/bee-queue/blob/master/lib/lua/index.js#L41).

**Comment by leibale** [comment]
you can define lua scripts on the client and then use them like any other command.
checkout the ["scripts" section in the main readme](https://github.com/redis/node-redis#lua-scripts) and [this example file](https://github.com/redis/node-redis/blob/master/examples/lua-multi-incr.js)

**Comment by compwright** [comment]
Use sendCommand(), i.e.:

```javascript
const [exists] = await client.sendCommand('script', 'exists', scriptChecksum);
```
