### ISSUE TITLE
Can I update multiple heterogeneous paths with the the SET command?

### ISSUE THREAD

**Issue by roschler** [redis/node-redis#2294]
I know I can update multiple keys using a JsonPath pattern like the Redis JSON docs show:
```
redis> JSON.SET doc $ '{"f1": {"a":1}, "f2":{"a":2}}'
OK
redis> JSON.SET doc $..a 3
OK
redis> JSON.GET doc
"{\"f1\":{\"a\":3},\"f2\":{\"a\":3}}"
```
But that only works if you are updating keys with a common name, and the path pattern ("$..a") matches multiple keys.  Is there a way to update multiple keys with the same SET command but using a list of independent paths?  For example something akin to:
```js
            await self.redisClient.json.set(
                redisKey,
                ["$.key_1", "$.key_2", "$.key_3"],
                valueToAssign,
                {
                    NX: true
                }
            )
```
Where the value "valueToAssign" would be assigned to the top level keys: "key_1", "key_2", and key_3" in the above hypothetical example?  The above example uses the `NX` option so I would want the assignments to be made only if for those keys that do not already exist.

**Comment by leibale** [comment]
Unfortunately this is not supported by Redis JSON, see https://github.com/RedisJSON/RedisJSON/issues/414
