### ISSUE TITLE
Reconnect doesn't work without on('error') listener

### ISSUE THREAD

**Issue by ivanpepelko** [redis/node-redis#2302]
Node processes containing redis clients would crash with SocketClosedUnexpectedlyError.
The reason is well known - `timeout` in redis.conf (in our case it's set to 1h, and our node processes would crash within same interval).

The problem is that without on('error') listener the error is seemingly considered 'uncaught' and crashes the process.
After adding the listener (it simply logs the error), the library would recreate/reconnect to the server and process would continue to live on.
Is this behavior by design? Or I missed something in docs?

This issue might also be related or the same as #2276, #2274 and #2273.

**Environment:**
 - **Node.js Version**: 16
 - **Redis Server Version**: 6.0
 - **Node Redis Version**: 3 & 4
 - **Platform**: linux (debian, arch)

**Comment by leibale** [comment]
this is how Node `EventEmitter` is designed (see https://nodejs.org/api/events.html#events_error_events), but because this question/issue comes up a lot, we should address it in the main README
