### ISSUE TITLE
MGET returns an array wrapped around every returned object.

### ISSUE THREAD

**Issue by hypo-thesis** [redis/node-redis#2308]
**Environment:**
 - **Node.js Version**:  18.9.0
 - **Redis Server Version**: Redis server v=7.0.5 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=68bf11aad5b039df
 - **Platform**:  Ubuntu 20.04.3,

Redis `MGET `returns multiple objects in arrays of an array. 

I have on my DB : 

`A:1` as key with content `{a:1}` and `B:2` as key with `{b:2}` content. However `Redis.json.MGET(["A:1" , "B:2" , '$') `returns `[ [ {a:1} ] , [{b:2}] ] `instead of `[  {a:1}  , {b:2} ]`.

Can someone explain to me why? 

Edit: I just realized that `Redis.json.MGET(["A:1" , "B:2" , '.')` instead of `Redis.json.MGET(["A:1" , "B:2" , '$')` returns the correct value and the arrays are not wrapped within arrays inside.

**Comment by leibale** [comment]
This is the actual reply from RedisJSON.

> When using a single JSONPath, the root of the matching values is a JSON string with a top-level array of serialized JSON value. In contrast, a legacy path returns a single value.<br/>
When using multiple JSONPath arguments, the root of the matching values is a JSON string with a top-level object, with each object value being a top-level array of serialized JSON value. In contrast, if all paths are legacy paths, each object value is a single serialized JSON value. If there are multiple paths that include both legacy path and JSONPath, the returned value conforms to the JSONPath version (an array of values).

https://redis.io/commands/json.get/
