### ISSUE TITLE
branch master to be changed to main as it is more inclusive

### ISSUE THREAD

**Issue by alphabetkrish** [redis/node-redis#2313]
Please consider changing master branch name to main to be compliant with Inclusive language

**Comment by chayim** [comment]
The names master and main have different contexts in different languages, cultures, and groups. While we strive to respect all of the above, the reality is that not everyone can be happy with each decision.  Popular replacements for master (i.e unstable, or even main), are improper for various groups.

For now, we'll stick with what we have. However, the issue isn't closed - we continue to monitor and evolve on these, and other positions.
