### ISSUE TITLE
Raw XREAD command fails with "Invalid argument type"

### ISSUE THREAD

**Issue by almosnow** [redis/node-redis#2314]
(Assuming you have a working `client` and a stream named `stream`)

When trying to call `client.XREAD('STREAMS', 'stream', '0')`

the code throws a `TypeError: Invalid argument type` exception.

I think it's a bug, equivalent redis command is `XREAD STREAMS stream 0` and runs without issue through redis-cli.

**Comment by leibale** [comment]
```javascript
client.XREAD('STREAMS', {
  key: 'stream',
  id: '0'
})
```
this should work

**Comment by almosnow** [comment]
Just tried it out, still fails,

Please note that `XREAD` != `xRead`.

**Comment by leibale** [comment]
My bad, this should work (without the STREAMS)
```javascript
client.XREAD({
  key: 'stream',
  id: '0'
});
```

**Comment by almosnow** [comment]
It does work now, thanks!

I thought raw commands had a simple mapping to redis commands like literally [args, arg, arg, arg, ...]

I see that's not the case, is this documented anywhere?

**Comment by leibale** [comment]
https://redis.js.org/documentation/client/modules/lib_commands_XREAD.html
BTW, the package has full TS support, so you should get autocomplete in your IDE
