### ISSUE TITLE
Add a connectTimedOut to client.connect()?

### ISSUE THREAD

**Issue by dallascao** [redis/node-redis#2319]
This is a feature request, not a bug report. Sorry for the wrong label.

It would be useful if there is an `connectTimedOut` option to `client.connect()` method.

I used redis to remember some switches and redis is not crucial. But when there is a problem with my redis server, `client.connect()` waits forever.

I would like to be able to do something like this:
```javascript
try {
 await client.connect({connectTimedOut: 3000})
} catch (error) {
 //ignore this error. My program run well without redis service anyway.
}
```

**Comment by leibale** [comment]
You can do it with this config (see [client-configuration.md](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) for more details):
```javascript
createClient({
  socket: {
    connectTimeout: 1000, // in ms, `5000` by default
    reconnectStrategy: () => new Error('do not retry') // by default it'll return `Math.min(retries * 50, 500)`, which means retry forever
  }
});
```
