### ISSUE TITLE
Slow performance compared to Postgres

### ISSUE THREAD

**Issue by ghost** [redis/node-redis#2322]
**Environment:**
 - **Node.js Version**: 
 - v16.14.2
 - **Redis Server Version**: 
 - Redis official docker  image
 - **Node Redis Version**: 
 - latest (4.5.0)
 - **Platform**: 
 - Windows 10

Hello, im getting worse performance when doing Promise.all in redis.get compared to postgres select
Tried to enable pipelining, but understood it already enabled by default. am i missing something? object is pretty big - 2 million characters

await Promise.all([client.get('key'), ..10 times.])
329.252ms

await Promise.all([PostgresSelect(), ..10 times])
214.027ms

**Comment by leibale** [comment]
Hi, I just ran this script to compare the performance
```javascript
import postgres from 'postgres';
import { createClient } from '@redis/client';

const sql = postgres({
    username: 'admin',
    password: 'admin'
});

const client = createClient();

await client.connect();

await benchmark('postgres', () => sql`SELECT 'PONG'`);
await benchmark('redis', () => client.ping());

async function times(name, fn, n) {
    console.time(name);
    const promises = [];
    for (let i = 0; i < n; i++) {
        promises.push(fn());
    }
    await Promise.all(promises);
    console.timeEnd(name);
}

async function benchmark(name, fn, n = 100_000) {
    await times(`warmup ${name}`, fn, n * 0.1);
    await times(name, fn, n);
}
```
here are the results:
```
warmup postgres: 252.525ms
postgres: 1.605s
warmup redis: 97.745ms
redis: 581.823ms
```

I'm not too sure if comparing "PING" and "SELECT 'PONG'" is fair...

**Comment by daniandco1** [comment]
> Hi, I just ran this script to compare the performance
> 
> ```js
> import postgres from 'postgres';
> import { createClient } from '@redis/client';
> 
> const sql = postgres({
>     username: 'admin',
>     password: 'admin'
> });
> 
> await benchmark('postgres', () => sql`SELECT 'PONG'`);
> 
> const client = createClient();
> 
> await client.connect();
> 
> await benchmark('redis', () => client.ping());
> 
> async function times(name, fn, n) {
>     console.time(name);
>     const promises = [];
>     for (let i = 0; i < n; i++) {
>         promises.push(fn());
>     }
>     await Promise.all(promises);
>     console.timeEnd(name);
> }
> 
> async function benchmark(name, fn, n = 100_000) {
>     await times(`warmup ${name}`, fn, n * 0.1);
>     await times(name, fn, n);
> }
> ```
> 
> here are the results:
> 
> ```
> warmup postgres: 252.525ms
> postgres: 1.605s
> warmup redis: 97.745ms
> redis: 581.823ms
> ```
> 
> I'm not too sure if comparing "PING" and "SELECT 'PONG'" is fair...
thanks, the problem occurs for me with big string. toda btw :D
