### ISSUE TITLE
Support connection pooling

### ISSUE THREAD

**Issue by artur-ma** [redis/node-redis#2330]
Since Redis 6 supports multi-threading model for network I/O, can this feature now be added in node-redis?

https://redis.com/blog/diving-into-redis-6/

> Despite Redis’ well-deserved reputation for high performance, its single-threaded architecture has been controversial among engineers who wondered if Redis could be even faster. Redis 6 rings in a new era: while it retains a core single-threaded data-access interface, I/O is now threaded.

**Comment by leibale** [comment]
Duplicate of #226
