### ISSUE TITLE
Unable to perform clean-up during NodeJs "Signal event" 

### ISSUE THREAD

**Issue by bologer** [redis/node-redis#2331]
I have CLI script which uses node-redis package. The idea now is to implement clean-up routine in case of Signal event in NodeJS, for example `SIGINT`.

I've configure client and use it as following: 

```ts
redisClient = /* ... */

process.on('SIGINT', async () => {
    await redisClient.del('mykey'); // <- it looks like this part silently fails
});

try {
   /* some script execution */
   await redisClient.quit();
} catch(e) {
   /* Error handling */
} finally {
    await redisClient.quit();
}


```

I tried to minimize working example and set key directly via redis-cli and remove it via `SIGINT` (from CLI command), however it does not seem to do the job as I can still see the key in Redis. 

It seems like node-redis automatically disconnects on `SIGINT` (or other event) and therefore I'm unable to use any of the methods from client.

What is the best way to clean-up (e.g. remove key) before client disconnect or during `SIGINT`?
Is there special event, such as on before disconnect or similar? What is recommended approach?  

**Environment:**
 - **Node.js Version**: v16.13.0 
 - **Redis Server Version**: 7.0.5-alpine 
 - **Node Redis Version**:  4.5.0 
 - **Platform**: MacOS Monterey 12.4 )Macbook Pro on M1)

**Comment by leibale** [comment]
this worked for me (on linux)
```javascript
import { createClient } from '@redis/client';

const client = createClient();

client.on('error', err => console.error(err));

await client.connect();

process.on('SIGINT', async () => {
  await client.del('key');
  console.log(await client.get('key'));
});

await client.set('key', 'value');
console.log(await client.get('key'));
```

**Comment by bologer** [comment]
I was able to resolve the issue. 

It was related to the fact that I was using puppeteer, which underneath handles SIGINT event by itself. This caused NodeJS to exit earlier and therefore custom event handles from my script didn't finish gracefully. 

I recommend for anyone who encounter such problem to check libraries you use and see whether they handle such events on their own or not. 

If you are using puppeteer, you may disable default SIGINT behavior this way: 

```js
const config = {
      args: [
            '--no-sandbox',
            '--disable-dev-shm-usage',
            '--disable-web-security',
            '--disable-features=IsolateOrigins',
            '--disable-site-isolation-trials'
        ],
       // ...
       handleSIGINT: false, // <-- See this option
```

Docs - https://pptr.dev/api/puppeteer.launchoptions.handlesigint
