### ISSUE TITLE
Is there a way to see if the client is connected?

### ISSUE THREAD

**Issue by spock123** [redis/node-redis#2339]
Not a bug per se, I'm trying to build in some backoff logic, in case Redis connection for some reason does not work. If the client loses connection, etc etc.

Is there a way I can check the instantiated client, or should I implement some logic myself using the client events?

The main issue for the latter is that the error event doesn't seem to give a good parseable error message - it's just a text, making it very difficult to parse. I can't figure out how to get a specific error code - only a descriptive text.

So my question is:
How would you check that the client is connected? 

Thanks in advance

**Comment by leibale** [comment]
`client.isOpen` = the client is either connecting or reconnecting
`client.isReady` = the client is connected and ready for use

**Comment by spock123** [comment]
@leibale whoa that's amazing. So sorry for my stupidity.
I tried looking into the client value but couldn't find those values.

Closing and bowing out

**Comment by leibale** [comment]
More like not finished documentation... I'll leave this issue open as a documentation issue

**Comment by simonprickett** [comment]
I'll look at adding an example script for this into the `examples` folder.
