### ISSUE TITLE
"Cannot send commands in PubSub mode" error on ping

### ISSUE THREAD

**Issue by TarSzator** [redis/node-redis#2345]
As I understand the sentence 

> The commands that are allowed in the context of a subscribed client are SUBSCRIBE, SSUBSCRIBE, SUNSUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING, RESET, and QUIT.

on [Redis Pub/Sub](https://redis.io/docs/manual/pubsub/) 

I should not get the error

> Cannot send commands in PubSub mode

on a ping call with the redis client 

**Environment:**
 - **Node.js Version**: 18.12.1
 - **Redis Server Version**: 7.0.5
 - **Node Redis Version**: 4.5.1
 - **Platform**: Alpine in Docker (Host MacOS 13.0.1 on Apple M1 Max)

**Comment by TarSzator** [comment]
Thank you @leibale 😄 So fingers corsed that you get around to it this week 🤞🏼

**Comment by TarSzator** [comment]
@leibale Where you able to release?

**Comment by TarSzator** [comment]
Thank you @leibale for the response and the workaround hints.

I like your plan for the release 😃

**Comment by leibale** [comment]
@TarSzator apparently PubSub & Sharded PubSub + Cluster is a little bit more complicated than I anticipated, but it's almost ready... sorry for all the delays...

**Comment by TarSzator** [comment]
@leibale Thanks for keeping this issue up2date.

Still planing to finish `PubSub & Sharded PubSub + Cluster` or push this to a later release?

**Comment by leibale** [comment]
I'll release a version with or without it (depends if I'll finish it in time) tomorrow

**Comment by leibale** [comment]
@TarSzator I can't release an RC version of `redis` with an RC version or `@redis/client` without releasing a version for all the sub-packages (because the current "peer dependency" in all the sub-packages does not include RC versions). If you are using `@redis/client` directly I can release an RC version of that.

Sorry for all the delays.

**Comment by TarSzator** [comment]
I should be able to easily switch to `@redis/client` for now. So it would already solve my issue when you for now only release the fix on `@redis/client`

**Comment by leibale** [comment]
@TarSzator `@redis/client@1.5.0-next.0` is on npm :tada:

**Comment by leibale** [comment]
@TarSzator have you tried the "next" version? does it work?

**Comment by TarSzator** [comment]
@leibale Works fine for me. Thanks a lot. When will you release it as fully?

**Comment by TarSzator** [comment]
@leibale Is there an ETA for v1.5.0?

**Comment by leibale** [comment]
I already missed the "promised" day a couple of times, so I won't make that mistake again...
You can watch #2373 to get updates, the two missing parts are:
1. cluster + shared pub-sub (60-70% done)
2. tests (5-10% done)

Sorry for all the delays.

**Comment by leibale** [comment]
Once #2373 will be ready I'll merge it + (about) 10 more PRs and release them all

**Comment by leibale** [comment]
@TarSzator just an update.. I'm pretty sure that it works, just need to clean the code a bit + add more tests.. Hopefully my next comment will be after releasing it.. :)

**Comment by TarSzator** [comment]
@leibale Thanks a lot for keeping me in the loop

**Comment by leibale** [comment]
@TarSzator `redis@4.6.0`/`@redis/client@1.5.0` is on npm :tada:
