### ISSUE TITLE
Not able to use KEYS pattren in latest version 4.5.1

### ISSUE THREAD

**Issue by groverHg** [redis/node-redis#2350]
Node.js Version: 14.20
Node Redis Version: 4.5.1
Platform: Ubuntu 20

Hello all, 
I've recently upgraded my redis package version in my project and i'm facing a issue.

I'm trying to use this.client.keys(pattren) to get a list of keys in my redis but it is showing keys does not exist on this version
I'm attaching my code snippet below. It used to work in old version 3.something but in 4.5.1 it is not working anymore 
Note: commented code is of old version which used to work

```
async getKeyFromPattern(pattren: string): Promise<any> {
        const response = await this.client.keys(pattren)
        console.log(response)

        return response;
        // return new Promise((res, rej) => {
        //     this.client.keys(pattren, (err, reply) => {
        //         if (err) rej(err);
        //         else res(reply);
        //     });
        // });
    }
```

**Comment by groverHg** [comment]
I'm getting this error when using `const response = await this.client.keys(pattren)`
`Property 'keys' does not exist on type 'RedisClientType<RedisModules, RedisFunctions, RedisScripts>`

**Comment by leibale** [comment]
I tried to reproduce it in [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQDbBoB2MANHAEpoAmwAzvoSQCoCeYacAvnAGZQQQcAOTpadYQG4AsACg5AegVwArnWBEA5nABuGKMAwAjPJ1rpkMPKzlzkEInXjICxeAF4U6LLlckAFACUMvKyLkwwAHQO-sJoUAJQwuTxUHDuAHwoDnQQppGp0LFU4nCMbnAAognQyXCpgcG2shgA7hjAzn5R9kREaJZBIXY58ADWaKx06XBtHV0RkRNTsWBY2FBEwk2hisqtnQAWsyh4GHR0zS7n0wCyrCX05SSIcnDvcADE4W4AXJQ0J7dNgcYayD7ZRwwKAqSxFH4kf6PBjA9hoQKvcEQj4wQ70SLfbozBEwEIQrjNCHLOhBTHYj7oGAqTZwXH4wmLamxbBObZkj4U2SCoA) in two ways, both seem to work.. Can you please provide a non working example?

BTW, if you have `@types/redis` installed make sure to remove it, as the package includes built-in types now

**Comment by leibale** [comment]
If it's still an issue feel free to reopen
