### ISSUE TITLE
where is "Sharded Pub/Sub" function? (spublich, ssubscrib)

### ISSUE THREAD

**Issue by sungwoo-lifeoverflow** [redis/node-redis#2354]
https://redis.io/docs/manual/pubsub/

Are there any plans to add the functionality from the guide to the node package module?

**Comment by leibale** [comment]
Hi, I'm working on that in #2344
It should be ready soon

**Comment by sungwoo-lifeoverflow** [comment]
> Hi, I'm working on that in #2344 It should be ready soon

Thank you for your quick response.
Waiting for good news.

**Comment by sungwoo-lifeoverflow** [comment]
Can you let me know how your pr request is going?

**Comment by leibale** [comment]
@sungwoo-lifeoverflow Its pretty close, but I have some other stuff that I need to work on.. It'll be ready "soon"..

**Comment by leibale** [comment]
@sungwoo-lifeoverflow `redis@4.6.0`/`@redis/client@1.5.0` is on npm :tada:
