### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by jdgamble555** [redis/node-redis#2385]
**Environment:**
 - **Node.js Version**: 18.13.0
 - **Redis Server Version**: 6.26
 - **Node Redis Version**: 4.5.1
 - **Platform**:  Windows 11

```ts
import { createClient } from "redis";
import { REDIS_URL } from '$env/static/private';

const client = createClient({ url: REDIS_URL, socket: { keepAlive: false } });
client.setMaxListeners(0);

client.on('error', error => console.error('ERR:REDIS:', error));
client.connect();

export const query = async (q: string) => await client.graph.query('test-graphs', q);
```

This seems to be a prevalent issue for over 10 years, however, I could not find any bug reports in the Source repository (this repository).  As you can see, I even have `setMaxListeners` set to `0`  and `keepAlive` set to `false` to no avail.  Sure, I would like to ignore the error, but if I could figure out how to **FIX** the error, that would be nice; I can't seem to do either.

Is there a way to stop listening to the client after every query?  This seems to happen after I run 10 or so queries.  Sometimes it takes more (not sure why).

J

**Comment by leibale** [comment]
`setMaxListeners` is a built-in function on `EventEmitter`, see [here](https://nodejs.org/api/events.html#emittersetmaxlistenersn).
Why do you even use this function? What are you trying to prevent?
If you want to close the client at some point you can use `client.quit()`/`client.disconnect()`.

**Comment by jdgamble555** [comment]
### keepAlive
> From version 3.2 onwards, Redis has TCP keepalive (SO_KEEPALIVE socket option) enabled by default and set to about 300 seconds. This option is useful in order to detect dead peers (clients that cannot be reached even if they look connected). Moreover, if there is network equipment between clients and servers that need to see some traffic in order to take the connection open, the option will prevent unexpected connection closed events.

> TCP keepalive.
>
> If non-zero, use SO_KEEPALIVE to send TCP ACKs to clients in absence
> of communication. This is useful for two reasons:
>
> 1) Detect dead peers.
> 2) Force network equipment in the middle to consider the connection to be
>    alive.
>
> On Linux, the specified value (in seconds) is the period used to send ACKs.
> Note that to close the connection the double of the time is needed.
> On other kernels the period depends on the kernel configuration.
>
> A reasonable value for this option is 300 seconds, which is the new
> Redis default starting with Redis 3.2.1.
> tcp-keepalive 300

I don't see any other documentation, but I think the default is `false` (or is it 300?), as that seems to be the case in [other packages](https://docs.oracle.com/javase/8/docs/api/java/net/StandardSocketOptions.html#SO_KEEPALIVE).  There doesn't seem to be anywhere in `node-redis` docs that clearly explains what each option does. Does it stay open by default, reconnect? Maybe I'm misunderstanding what the above means? 🤷
___
### setMaxListeners
So, `setMaxListeners` exists on the redis `client` as well as in node events:

![listen](https://user-images.githubusercontent.com/8333090/214047076-01186622-4228-4f00-b59f-109137d2aa0f.png)

But I think you're right, I need to import it directly from `events` instead:
```js
import { setMaxListeners } from 'events';
setMaxListeners(0);
```
Also, when `setMaxListeners` is set to `0`, it does not mean 0 listeners, it means [unlimited listeners](https://nodejs.org/api/events.html#emittersetmaxlistenersn).

This seems to solve the the symptom to the problem by not displaying the warning, but `not the problem itself`. I don't want to create a listener each time I run a query.  I want to keep the (one) connection alive so I don't open up a lot of connections if there are multiple requests.  
___
### Quit Vs. Disconnect
So apparently I need to use [quit](https://github.com/redis/node-redis#disconnecting) instead of `disconnect`.  However, if I use either, I will have to re-open a client connection each time I run a query, which is not what I want.
___
### How do I keep my connection open, and prevent each query from creating a new listener?

This is my real problem.  It doesn't seem like there is a way to do this?

J

**Comment by leibale** [comment]
Running a query does not create a new socket/connection/"listener" (I think this is what you mean by "listener", but to be honest I'm not too sure..), it uses the existing connection and executes all the commands on it:

```javascript
import { createClient } from 'redis';

const client = createClient({ url: '<REDIS_URL>' });

client.on('error', error => console.error('ERR:REDIS:', error));

await client.connect();

// these commands are running on the same socket/connection
await client.ping();
await client.graph.query('a', '*');
await client.graph.query('b', '*');
```

If at some point you want to gracefully close the application (for , use `client.quit()/client.disconnect()`, for example:
```javascript
process.on('SIGINT', () => client.quit());
 ```

**Comment by jdgamble555** [comment]
So what is creating more than 10 `client side event listeners`? It seems each `query` creates one and I get the node error (after I run 10 or so queries) unless I specifically use this code:

```js
import { setMaxListeners } from 'events';
setMaxListeners(0);
```
which is just ignoring the problem and taking care of the symptom. 

Using this:
```js
const client = createClient({ url: REDIS_URL });
client.setMaxListeners(0);
```
has no effect.

I guess I need to close the `client side listeners` in order to prevent the error message?

J

___
**Note** - That makes sense for `gracefully quitting`.

**Comment by leibale** [comment]
Search for "client.on" in your project and make sure you are not creating listeners over time. If you want we can debug it together, I'll wait in [this meeting](https://meet.google.com/zpj-rzoi-spb) for the next 30 min

**Comment by jdgamble555** [comment]
I just left my computer until after 5 central, or I would be there! Not sure if this helps, but here is my repo...

https://github.com/jdgamble555/redisgraph-graphql-sveltekit/blob/master/src/lib/server/redis.ts

and where I make the calls

https://github.com/jdgamble555/redisgraph-graphql-sveltekit/blob/master/src/lib/server/db.ts

J

I can't definitely meet this evening or tom if all else fails!

**Comment by jdgamble555** [comment]
Wow. That fixed the problem! Thank you! Not even sure how you caught that!

Here is the final project if you're curious: https://redisgraph-graphql-sveltekit.vercel.app/

It really was just a test project to get me familiar with putting the technologies together.  I am a huge RedisGraph fan, and I'm not even sure why it isn't more popular.  I plan on writing articles about some of these concepts in the project on my site [Code.Build](https://code.build/).

Thanks for taking the time!

J
