### ISSUE TITLE
ERR unknown command for RedisStack commands

### ISSUE THREAD

**Issue by MR4online** [redis/node-redis#2399]
### Description

When I try to create the Index for RedisSearch + RedisJson I get the following error:

```
ErrorReply: ERR unknown command `FT.CREATE`, with args beginning with: `idx:users`, `ON`, `JSON`, `PREFIX`, `1`, `noderedis:users`, `SCHEMA`, `$.name`, `TEXT`, `SORTABLE`, `UNF`, `$.age`, `AS`, `age`, ]
```

I tried the sample-Code from https://github.com/con-mark/node-redis/blob/d29d5bf31e36fd1d27ecaa4abb92359a6388a455/examples/search-json.js :

```
            await client.ft.create('idx:users', {
                '$.name': {
                    type: SchemaFieldTypes.TEXT,
                    SORTABLE: 'UNF'
                },
                '$.age': {
                    type: SchemaFieldTypes.NUMERIC,
                    AS: 'age'
                },
                '$.coins': {
                    type: SchemaFieldTypes.NUMERIC,
                    AS: 'coins'
                },
                '$.email': {
                    type: SchemaFieldTypes.TAG,
                    AS: 'email'
                }
            }, {
                ON: 'JSON',
                PREFIX: 'noderedis:users'
            });
```

The checked the connection, but its already open. What am I'm doing wrong?
I'm using the redis/redis-stack:6.2.6-v0 docker image.

----

EDIT: It looks like there is a problem with all "none-default" commands. Meaning 
`client.exists(key)` -> works
`client.ft.dropIndex(index)` -> does not work (same unknown command error)

do I have to register the Redis Stack to node-redis?
I'm switching from ioredis to node-redis, with ioredis all this worked with the very same docker.

----

### Node.js Version

v16.16.0

### Redis Server Version

6.2.7

### Node Redis Version

4.6.3

### Platform

macOS

### Logs

```bash
RedisSearch 2.6.3
RedisJSON 2.4.2
```

**Comment by leibale** [comment]
I tried to run the [same example](https://github.com/con-mark/node-redis/blob/d29d5bf31e36fd1d27ecaa4abb92359a6388a455/examples/search-json.js) with `redis/redis-stack:6.2.6-v0` and this is the logs I get:

```
Users under 30 years old:
{
  "total": 1,
  "documents": [
    {
      "id": "noderedis:users:2",
      "value": {
        "name": "Bob",
        "age": 23,
        "coins": 15,
        "email": "bob@somewhere.gov"
      }
    }
  ]
}
Users with email "bob@somewhere.gov":
{
  "total": 1,
  "documents": [
    {
      "id": "noderedis:users:2",
      "value": {
        "name": "Bob",
        "age": 23,
        "coins": 15,
        "email": "bob@somewhere.gov"
      }
    }
  ]
}
Aggregation Demo:
{
  "total": 1,
  "results": [
    {
      "averageAge": "27.5",
      "totalCoins": "115"
    }
  ]
}
```

Have you tried to run the same command from `redis-cli`? Are you sure you are connecting to the `redis-stack` docker and not another `redis-server` without the modules? Maybe try to run `console.log(await client.moduleList());` and make sure search and json are included.

If you wanna debug it together, I'll be on [this call](https://meet.google.com/zpj-rzoi-spb?pli=1) for the next 30 minutes :)

**Comment by MR4online** [comment]
Thanks @leibale, you saved my day!
You are right, the script connected to another redis instance, because I didn't changed the connection-config proper.
