### ISSUE TITLE
[Typescript] RedisFlushModes aren't exported and can't be used

### ISSUE THREAD

**Issue by oleksii-donoha** [redis/node-redis#2411]
### Description

When writing code, which flushes DB/all: 

```
await client.flushDb()
```
There might be a need to flush asynchronously: https://redis.io/commands/flushdb/
`client.flushDB()` expects optional arg `mode?: RedisFlushModes | undefined`.
This enum is implemented here: https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/FLUSHALL.ts
But the `RedisFlushModes` is not exported by `redis` module and cannot be referenced in the code.
Am I missing something?

### Node.js Version

v16.18.1

### Redis Server Version

unrelated to server

### Node Redis Version

redis@4.6.4

### Platform

Linux

**Comment by leibale** [comment]
Until we fix it you can either import the type from the file directly
```javascript
import { RedisFlushModes } from '@redis/client/dist/lib/commands/FLUSHALL.js';
```
or use `as any`
```typescript
client.flushDb('SYNC' as any);
```

Thanks for reporting!
