### ISSUE TITLE
ConnectionTimeoutError: Connection timeout

### ISSUE THREAD

**Issue by chlguswns980105** [redis/node-redis#2412]
### Description

```
// 1.2.3.4 is not real host
// real service is working, local to service server connect is not working.
const redis_client = redis.createClient({ url: "redis://1.2.3.4:6379" }); 
(async () => { try { await redis_client.connect(); } catch (err) { logger.error(err); } })();
```
wanna detail about this

### Node.js Version

14.21.1

### Node Redis Version

4.6.4

### Platform

macOS

### Logs

```bash
error - Connection timeout
Error: Connection timeout
    at Socket.<anonymous> (node_modules/@redis/client/dist/lib/client/socket.js:142:124)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:400:28)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by leibale** [comment]
@chlguswns980105 have you tried to connect using `redis-cli`?

**Comment by chlguswns980105** [comment]
@leibale 
```
redis_client = redis.createClient({ socket: { port: 6379 } });
(async () => { try { await redis_client.connect(); } catch (err) { logger.error(err); } })()
```
in service server, just use this code.
my local network is working.

**Comment by leibale** [comment]
@chlguswns980105 Do you have a `redis-server` running on your local machine on port `6379`? Can you please try to connect to it using `redis-cli` and see if that works?

**Comment by chlguswns980105** [comment]
how to see `redis-cli`, `redis-server`?
I saw [INFO](https://redis.io/commands/info/), but I can't understood.

another person did all setting, but now he is not our company.
I know only nodejs code.

**Comment by leibale** [comment]
You can use `docker` to run `redis-server` locally - `docker run -p 6379:6379 redis`.

**Comment by chlguswns980105** [comment]
@leibale 
our project no use docker.

```
docker run -p 6379:6379 redis
-bash: docker: command not found
```

**Comment by leibale** [comment]
@chlguswns980105 https://redis.io/docs/getting-started/installation/

**Comment by chlguswns980105** [comment]
@leibale redis already installed use npm.
need I install redis use yum?

**Comment by chlguswns980105** [comment]
@leibale

The workaround I wanted was to connect to the server Redis, but I solved it by installing Redis on my local mac.

thanks for answer
