### ISSUE TITLE
RESP2 parser error with large, multi-chunk responses

### ISSUE THREAD

**Issue by fast-facts** [redis/node-redis#2419]
### Description

I'm running an FT.Search command that returns 5000 items (using a limit argument). Upon debugging, I noticed the data usually comes in through 8-10 chunks. 95% of the time, the command just hangs. I have to reduce the limit argument to about 1000 for the command to succeed regularly. It seems to be there's some race condition with a larger number of chunks.

I confirmed the issue is not with the redis server or with the network as I was running it directly from the redis-cli command without any issues.

After much debugging, I boiled down the issue to [the write function in the RESP2 decoder](https://github.com/redis/node-redis/blob/9ffae592f1023cc1e675eb7ec25a21f4f03de66e/packages/client/lib/client/RESP2/decoder.ts#L62).

After adding various logging, I noticed that you can guarantee the function finishes, at least for me, if you slow down [the parseBulkString function](https://github.com/redis/node-redis/blob/9ffae592f1023cc1e675eb7ec25a21f4f03de66e/packages/client/lib/client/RESP2/decoder.ts#L173), but obviously the function takes way longer to finish. I added a `console.trace` on line 178 to achieve this. It is possible that I could just slow down some other parts of the file as well to achieve the same result. It might not be anything special about that function.

I'm unsure of the nuances of it all to be able to resolve this on my own, but here's the information that I've gathered, mostly through inserting various logging. I'll keep working on it and providing feedback that might be helpful.

I modified the function as such to add logging

```
    write(chunk) {
        console.log('start:', this.cursor, chunk.length) // <---------- added this line
        while (this.cursor < chunk.length) {
            if (!this.type) {
                this.currentStringComposer = this.options.returnStringsAsBuffers() ?
                    this.bufferComposer :
                    this.stringComposer;
                this.type = chunk[this.cursor];
                if (++this.cursor >= chunk.length) {
                    break;
                }
            }
            const reply = this.parseType(chunk, this.type);
            if (reply start: undefined) {
                break;
            }
            this.type = undefined;
            this.options.onReply(reply);
        }
        this.cursor -= chunk.length;
        console.log('end:', this.cursor, chunk.length) // <---------- added this line
    }
```

Here's a sample of the log it produces during a successful run

```
start: 0 1460
end: 0 1460
start: 0 13140
end: 2 13140
start: 2 2920
end: 0 2920
start: 0 1460
end: 0 1460
start: 0 24820
end: 0 24820
start: 0 4380
end: 1 4380
start: 1 1460
end: 0 1460
start: 0 10220
end: 0 10220
start: 0 24795
end: 0 24795
```

Here's a sample of a hanging run (notice the negative numbers)

```
start: 0 1460
end: 0 1460
start: 0 13140
end: 2 13140
start: 2 1460
end: 0 1460
start: 0 7300
end: -7298 7300
start: -7298 20440
end: -27737 20440
start: -27737 1460
end: -29196 1460
start: -29196 14600
end: -43795 14600
start: -43795 24795
end: -68589 24795
```

### Node.js Version

18.12.1

### Redis Server Version

7.0.8

### Node Redis Version

4.6.4

### Platform

Windows and Linux

**Comment by leibale** [comment]
@fast-facts thanks for reporting! Can you share a code that reproduce it so i'll be able to debug that?

**Comment by leibale** [comment]
@fast-facts tnx, i'll use this to debug it tomorrow
Regarding `RETURN: 0` - use `RETURN: []` instead. `NOCONTENT` is indeed not implemented, but thats not high on the list (cause you can do `RETURN: []` as a workaround).

**Comment by acai2046** [comment]
> See below. I did also notice if I remove the `RETURN: '0'`, the issue goes away. However, I do want to do NOCONTENT and that argument isn't available in `client.ft.search` and the [ft.search page](https://redis.io/commands/ft.search/) states that `RETURN: '0'` acts like NOCONTENT.
> 
> ```
> import { createClient } from 'redis';
> 
> void (async () => {
>   const client = createClient({ url: 'redis://url' });
> 
>   await client.connect();
>   console.log('Connected');
> 
>   const { total, documents } = await client.ft.search('idx', '*', { RETURN: '0', LIMIT: { from: 0, size: 5000 }, DIALECT: 2 });
> 
>   console.log(total);
>   console.log(documents.length);
> })();
> ```
err:
Uncaught (in promise) TypeError: url_1.URL is not a constructor

**Comment by leibale** [comment]
@fast-facts which version of redisearch are you using?

**Comment by leibale** [comment]
@fast-facts I just checked with the latest version of RediSearch and looks like `RETURN 0` omits the document from the reply (instead of empty array/null), I think it wasn't like that in the old versions of RedisSearch, but I'm not sure. I'll address this issue as well.

**Comment by leibale** [comment]
@fast-facts I just tried with RedisSearch 2.0.16, the reply didn't change, it's #2366 that never worked with more than one document.. 🤦‍♂️
I'll fix that tomorrow, and hopefully I'll manage to fix the original issue as well and release a new version, but no promises..

Thanks for helping and answering all the questions :)

**Comment by leibale** [comment]
@fast-facts I tried to reproduce the original issue using this code
```javascript
import { createClient, SchemaFieldTypes } from 'redis';

const client = createClient();
client.on('error', err => console.error('Redis Client Error', err));

await client.connect();

const promises = [
  client.flushAll(),
  client.ft.create('idx', {
    field: SchemaFieldTypes.TEXT
  })
];
for (let i = 0; i < 100000; i++) {
  promises.push(client.hSet(i.toString(), 'field', 'value'));
}
await Promise.all(promises);

for (let i = 0; i < 100; i++) {
  console.log(`Starting ${i}`);
  const { documents: { length } } = await client.ft.search('idx', '*', { LIMIT: { from: 0, size: 100000 } }); 
  console.log(`${i} returnd ${length} documents`);
}
await client.disconnect();
```
but it's working... (make sure not to run this code on your production server, it's running `FLUSHALL` at the start)

**Comment by leibale** [comment]
@fast-facts I'll try with `RETURN: '0'`, I want to understand what is going on..

**Comment by leibale** [comment]
@fast-facts I think it'll be ready tomorrow, I want to review #2424 again and do #2411. You can follow the progress [here](https://github.com/redis/node-redis/projects/7).

Sorry for the release delay...

**Comment by leibale** [comment]
@fast-facts `redis@4.6.5`/`@redis/client@1.5.6` is on npm 🎉
