### ISSUE TITLE
Can't Deploy to Vercel Edge Function - Status 500

### ISSUE THREAD

**Issue by jdgamble555** [redis/node-redis#2438]
### Description

My App works fine when I deploy to Vercel, but when I try and deploy to the Edge Functions, I get this error:

Which makes me wonder if this is a `socket.js` error (see log below)?

This error seems to be the same for people that try and deploy to the browser.  This is NOT the case here.

Demo: [Requires Login](https://redisgraph-graphql-sveltekit.vercel.app/)

Repo: [GitHub](https://github.com/jdgamble555/redisgraph-graphql-sveltekit/blob/master/src/lib/server/redis.ts)

### Node.js Version

18.13.0

### Redis Server Version

6.26

### Node Redis Version

4.51

### Platform

Windows 11

### Logs

```bash
TypeError: Class extends value undefined is not a constructor or null
    at (../../../../node_modules/@redis/client/dist/lib/client/socket.js:20:35)
    at (../../../../.svelte-kit/vercel-tmp/render/edge.js:12:7)
    at (../../../../node_modules/@redis/client/dist/lib/client/index.js:16:17)
    at (../../../../.svelte-kit/vercel-tmp/render/edge.js:12:7)
    at (../../../../node_modules/@redis/client/dist/index.js:18:17)
    at (../../../../.svelte-kit/vercel-tmp/render/edge.js:12:7)
    at (../../../../node_modules/redis/dist/index.js:18:17)
    at (../../../../.svelte-kit/vercel-tmp/render/edge.js:12:7)
    at (../../../../.svelte-kit/output/server/entries/endpoints/graphql/_server.ts.js:3:29)
    at (../../../../.svelte-kit/vercel-tmp/render/edge.js:12:7)
```

**Comment by leibale** [comment]
@jdgamble555 https://vercel.com/docs/concepts/functions/edge-functions/limitations#most-node.js-apis-are-not-available
`net.createConnection` is not available, which means there is no way to create a TCP socket, which means you cannot connect to your redis server directly.
You can create an in-between HTTP server and use it as a "proxy". I'm pretty sure there is already a library (not node.js) that does that, try to search for "Redis over HTTP".

**Comment by jdgamble555** [comment]
Ok thanks. If I have to create a proxy, I might as well just not use the Edge functions as that defeats the purpose. I deployed directly to Cloudflare (Vercel uses Cloudflare for Edge functions), and I can confirm I get the same error.  However, there may be a way considering Cloudflare (but not Vercel Edge) supports Web Sockets

[Cloudflare Blog TCP](https://blog.cloudflare.com/introducing-socket-workers/)

Either way, it seems like this is impossible for the moment.  Upstash seems to work with their Redis implementation (probably has their own proxy), but they don't have Redisgraph or any other Modules that I can see.

☹️ 

Thanks for your help!

J

**Comment by leibale** [comment]
@itamarhaber

**Comment by jdgamble555** [comment]
I'm wondering if node-redis could be use with the new [connect()](https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/) api for Cloudflare?

I guess you would have to re-write the package with a new `socket.js` file?

Perhaps adding an option to use an external `connect` package instead of `socket.io` package? This would solve the problem I think...

J
