### ISSUE TITLE
Number of redis connections ever increasing when using Next.js serverless

### ISSUE THREAD

**Issue by StephenKennedy5** [redis/node-redis#2468]
### Description

I am using this redis client in a next.js app. Here is an outline of my code.

```
import { createClient, RedisClientType } from 'redis';

const redisUrl = process.env.REDIS_URL;

if (!redisUrl) {
  throw new Error('REDIS_URL env variable is needed');
}

class RedisPool {
  redis: RedisClientType;

  constructor(redisUrl: string) {
    console.log('CREATING REDISPOOL');

    this.redis = createClient({
      url: redisUrl,
    });
    this.redis.on('error', (error) => {
      // eslint-disable-next-line no-console
      console.log('ERROR');
      // eslint-disable-next-line no-console
      console.log({ error });
    });
    process.on('exit', () => {
      this.redis.disconnect();
    });
  }
  async connect(): Promise<RedisClientType> {
    if (!this.redis.isOpen) {
      console.log('CONNECTING TO REDIS');
      await this.redis.connect();
    }
    return this.redis;
  }
}
const redisPool = new RedisPool(redisUrl);
export default redisPool;

```
The way I utilize this is like so
```
const redis = await redisPool.connect();
      try {
        await redis.set(
          verification_namespace.key(identifier),
          JSON.stringify(verificationToken)
        );
      } finally {
        // await redisPool.disconnect();
      }
``` 

As I navigate through the app and run this command ` redis-cli info  | grep clients` I see the number of connected clients continually increase. 
I don't really have this problem when it's a normal server but when serverless I can't really crack why this is occurring.
I see the log "CREATING REDISPOOL" about 3 times as I navigate before it stops occurring and the connections plateau as 3 additional more. On every hot reload as I change the code it adds 3 more additional connections.
I tried to fix this by adding pooling options such as 
```
this.redis = createClient({
      url: redisUrl,
      isolationPoolOptions: {
        idleTimeoutMillis: 5000,
        min: 5,
        max: 40,
      },
    });
```
but all this did was increase the number of connections more quickly.

Any ideas on how to manage redis pooling in the context of a serverless app?

### Node.js Version

v18.14.1

### Redis Server Version

6.2.5

### Node Redis Version

redis@4.6.5

### Platform

macOS

**Comment by leibale** [comment]
@StephenKennedy5 are you calling `connect` for every request (inside `getStaticProps`) or just once when the app starts? If you can create a small repo that reproduces the problem it'll be awesome... :)

BTW, the "isolation pool" is only for commands/functionality that is client-based (blocking commands for example). You can read more about that [here](https://github.com/redis/node-redis/blob/master/docs/isolated-execution.md).

**Comment by StephenKennedy5** [comment]
@leibale sorry I missed your response, I got to fix my notifications. 

I am calling our connect method on the RedisPool Class on every request. I have logic in there that would ideally prevent redis.connect on every request (checking attribute redis.isOpen). 

Here is my example repo: https://github.com/StephenKennedy5/redis-example

In order to get this running you will want to do 
1.  Copy .env.example to .env.local
2. `npm install`
3.  `docker-compose up --build -d redis`
4.  `npm run dev` (Needs to start on port 3001)
5.  Click between the pages ("see all components" and "< Back to Home") and save any random file to ensure the app is hot reloaded
6. Occasionally run `docker exec -it redis_example_dev redis-cli info | grep clients` to observe the number of clients increasing

Please let me know if you have any issues running this or are unable to reproduce said bug. I still have not been able to figure this out since we last talked.

**Comment by StephenKennedy5** [comment]
@leibale hey just following up, I appreciate all the work you put into this project. I was hoping to get some clarity about this issue.

**Comment by leibale** [comment]
@StephenKennedy5 TBH I forgot about that.. I'll try to get to it tomorrow :)

**Comment by leibale** [comment]
@StephenKennedy5 Looks like it's a next.js bug/design issue, and you can work around that by attaching the client to `global` and reusing (instead of recreating) between restarts. See https://stackoverflow.com/questions/67025983/is-there-a-hook-before-next-js-hot-reload-happens and https://github.com/vercel/next.js/issues/7811.

Disclaimer: I've never used next.js, so I'm clueless..

**Comment by StephenKennedy5** [comment]
Thanks for the response! If it happens only in development I do not mind restarting my server. If it continues to happen in production then I'll try out the fix and report back on this ticket.

**Comment by leibale** [comment]
@StephenKennedy5 it shouldn't happen in production, it's due to ["fast refresh"](https://nextjs.org/docs/architecture/fast-refresh)
