### ISSUE TITLE
Add support for TIMEOUT in FT.Aggregate and FT.Search

### ISSUE THREAD

**Issue by fast-facts** [redis/node-redis#2486]
### Motivation

Provides support for the TIMEOUT argument in FT.Aggregate and FT.Search

### Basic Code Example

```JavaScript
await client.ft.search('idx', 'query', { RETURN: [], TIMEOUT: 5000 })
await client.ft.aggregate('idx', 'query', { STEPS: [...], TIMEOUT: 5000 })
```

**Comment by Nanak360** [comment]
I would love to take this up

**Comment by leibale** [comment]
@Nanak360 go for it.. :)
Thanks for contributing!!

**Comment by leibale** [comment]
https://github.com/redis/node-redis/blob/master/packages/search/lib/commands/AGGREGATE.ts
https://github.com/redis/node-redis/blob/master/packages/search/lib/commands/SEARCH.ts
@Nanak360 make sure to add tests as well :)

**Comment by Nanak360** [comment]
Hey @leibale, I've created a draft PR for this issue.
I have some doubts and would really appreciate your feedback or someone else's review of the changes.

I have added `TIMEOUT` as an optional parameter, but I'm a bit confused about the next steps. Currently, I have only included `TIMEOUT` in the return arguments.

You can find the draft PR [here](https://github.com/redis/node-redis/pull/2488), and any modifications or suggestions you have would be greatly appreciated.

**Comment by leibale** [comment]
@Nanak360 I left one comment, but overall looks good! Good job! :)
