### ISSUE TITLE
Set expiring date for hash value

### ISSUE THREAD

**Issue by RomainGuarinoni** [redis/node-redis#2493]
### Motivation

I know that we can set the expire date like this for a basic key / value pair : 

```ts
await client.set("key", "value", { EX : 60 });
```
But their is no such way to set expire date for a hash value, it would be great to have something like this : 

```ts
await client.hSet(
        'hash',
        {
          key: 'value',
        },
        {
          EX: 60,
        },
      );
```

### Basic Code Example

```JavaScript
await client.hSet(
        'hash',
        {
          key: 'value',
        },
        {
          EX: 60,
        },
      );
```

**Comment by leibale** [comment]
This is not supported by Redis at the moment (see [`SET`](https://redis.io/commands/hset/)). You can open an issue in [this repository](https://github.com/redis/redis/issues), but I'm pretty sure someone already asked for this feature...

In the meantime you can:
```javascript
// pipeline
await Promise.all([
  client.hSet('key', {}),
  client.expire('key', { EX: 60 })
]);

// multi
await client.multi()
  .hSet('key', {})
  .expire('key', { EX: 60 })
  .exec();
```

**Comment by RomainGuarinoni** [comment]
Thank you so much @leibale , it's exactly what i needed !!!
