### ISSUE TITLE
DB Option with createClient

### ISSUE THREAD

**Issue by reqshark** [redis/node-redis#2495]
### Description

`redis` version: **7.0.11**
`node-redis` version: **4.0.2**

In the past, a DB option given to `createClient` normally specified which index to use when starting clients.

This option doesn't work with the above mentioned versions. Instead, new client starts off with `db: 0`. This is redis cluster behavior but without a cluster. Not sure whether this is intentional but here's my code:

```js
const client1 = redis.createClient({ legacyMode: true, password, db: 1 })  /* db 0, ignores opt 1 */
const client3 = redis.createClient({ legacyMode: true, password, db: 3 })  /* db 0, ignores opt 3 */
```
So now I have to call `SELECT` after creating the client.
```js
const client1 = redis.createClient({ legacyMode: true, password }) /* no longer passing db option */ 
const client3 = redis.createClient({ legacyMode: true, password }) /* since it doesnt work */

client1.connect().then(()=> client1.select(1), console.log) /* now it uses db index 1 instead of 0 */
client3.connect().then(()=> client3.select(3), console.log) /* now it uses db index 3 instead of 0 */ 
```
Might be worth mentioning db option is useless now.

**Comment by leibale** [comment]
It's `database`, not `db` (see https://github.com/redis/node-redis/blob/master/docs/client-configuration.md):
```javascript
redis.createClient({ database: 1 });
```

**Comment by reqshark** [comment]
Oh it used to be `db`, now it's `database` that's good to know. Thanks!
