### ISSUE TITLE
sUnsubscribe throw CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by ngot** [redis/node-redis#2502]
### Description

I'm trying to use `sUnsubscribe` in the cluster mode. I find out it supports both string and array. Based on the current implementation, the array type implicitly enforces all the channels to be hashed to the same slot, otherwise an error will throw says `ErrorReply: CROSSSLOT Keys in request don't hash to the same slot`.

Just checking is that a intentional design or a bug?

https://github.com/redis/node-redis/blob/master/packages/client/lib/cluster/index.ts#LL372C10-L372C10

### Node.js Version

16

### Logs

```bash
ErrorReply: CROSSSLOT Keys in request don't hash to the same slot
```

**Comment by leibale** [comment]
`S[UN]SUBSCRIBE` behaves just like any other command, either use ["hash tags"](https://redis.io/docs/reference/cluster-spec/#hash-tags) or call `SSUBSCRIBE` twice:
```javascript
// make sure both channels are in the same slots using "hash tags"
await cluster.SSUBSCRIBE(['{tag}1', '{tag}2'], (message, channel) => {
  console.log(message, channel);
});

// SSBUCRIBE twice, once for each slot
await Promise.all([
  cluster.SSUBSCRIBE('1', (message, channel) => {
    console.log(message, channel);
  }),
  cluster.SSUBSCRIBE('2', (message, channel) => {
    console.log(message, channel);
  })
]);
```

**Comment by ngot** [comment]
Thanks @leibale . This finding originnates from https://github.com/socketio/socket.io-redis-adapter/issues/500 

I believe this is not bug in node-redis. I will cose it.
