### ISSUE TITLE
rPop doesn't recognize "count" argument

### ISSUE THREAD

**Issue by michal-grabowski** [redis/node-redis#2505]
### Description

According do redis docs  [https://redis.io/commands/rpop/ ](url)

_RPOP 
By default, the command pops a single element from the end of the list. When provided with the optional count argument, the reply will consist of up to count elements, depending on the list's length._

Unfortunately this optional argument doesn't  work with node-redis

This sample code should return max 5 elements from the list. Instead always returns 1 element, even if the are more elements available in the list.
`await client.rPop(key, {count:5});`

I also tried this way

`await client.rPop(key, 5);`

From redis command like it looks like this:
`LPUSH foo 1 2 3 4 5 6 7 8 9 10`
`RPOP foo 5`
`1) "1"`
`2) "2"`
`3) "3"`
`4) "4"`
`5) "5"`

### Node.js Version

v18.16.0

### Redis Server Version

7.0.11

### Node Redis Version

redis@4.6.6

### Platform

Linux debian 11

**Comment by michal-grabowski** [comment]
It works with 
`await client.sendCommand(['RPOP', key, len.toString()])`

So it seems that count parameter in rPop isn't support yet ?

**Comment by leibale** [comment]
Since the count option changes the reply type (from a single item to an array of items), its implemented as a different command:
```javascript
const values = await client.rPopCount('key', 10);
```

**Comment by michal-grabowski** [comment]
I couldn't find this in the docs. Do you have full list of methods and it's signatures? It works as expected, thank you.
