### ISSUE TITLE
@redis/client Isolated blocking command blocks all other commands on all sessions

### ISSUE THREAD

**Issue by mishase** [redis/node-redis#2512]
### While running this script:
```ts
import { createClient } from "redis";

const client = createClient({ url: "<redacted>" });

async function run() {
    await client.blPop(client.commandOptions({ isolated: true }), "test", 10);
    console.log("BLPOP Finished");
}

async function main() {
    await client.connect();

    for (let i = 0; i < 2; i++) run();
}

main();
```
### Output of the following code will be:
```text
<wait 10 seconds (first BLPOP timeout)>
BLPOP finished
<wait 10 seconds (second BLPOP timeout)>
BLPOP finished
```
### We can run `MONITOR` command in redis-cli and see output
```text
"AUTH" "(redacted)"
"AUTH" "(redacted)"
"BLPOP" "test" "10"
<wait 10 seconds (BLPOP timeout)>
"BLPOP" "test" "10"
```
### Node.js Version

v18.14.0

### Redis Server Version

7.0.11

### Node Redis Version

4.6.6

### Platform

Windows

**Comment by mishase** [comment]
Thanks, this was the solution! I can't see any isolationPoolOptions mentions in documentation (At least in [isolated-execution](https://github.com/redis/node-redis/blob/master/docs/isolated-execution.md) and [client-configuration](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md)) and google search `node-redis "isolationPoolOptions"` gives nothing at all. Maybe you should add this behavior to documentation and disclaimer about isolated commands in your examples on the main page?

**Comment by leibale** [comment]
@mishase we definitely need to improve the docs.. Hopefully the v5 docs will be more useful :)
