### ISSUE TITLE
I am not able to get the expired key properties from keyevent

### ISSUE THREAD

**Issue by hypo-thesis** [redis/node-redis#2533]
### Description

I have a key say `newKey` which is a json `{ "foo" : "bar" }` and expires at 10 secons. I can get the deleted key emitted to me by : 

`Rsub.subscribe('__keyevent@0__:expired', key => console.log(key, 'expired'));`

Yet I wash to know more about the deleted key, such as what foo value is. 
Is there a way to get the information inside the key or the name of the deleted key is the only accessible data to me?

### Node.js Version

20

### Redis Server Version

7

### Node Redis Version

4.5.1

### Platform

ubuntu

**Comment by 1Jo1** [comment]
it works on my machine :) 
redis-node version 4.6.7
