### ISSUE TITLE
Redis.v4 missing types

### ISSUE THREAD

**Issue by zhiyan114** [redis/node-redis#2559]
### Description

While using legacy mode (since the library is still in progress for v4), I've noticed that when using `Redis.v4["Command"]`, the command will result in `any` type (i.e. missing proper type).

Is this an intentional design?

### Node.js Version

18.14.0

### Redis Server Version

N/A

### Node Redis Version

4.6.7

### Platform

Windows

### Logs

```bash
N/A
```

**Comment by leibale** [comment]
1. "since the library is still in progress for v4" - v4 is ready for production use
2. the `v4` property is typed as "any" in v4
3. [We are improving it in v6](https://github.com/redis/node-redis/blob/v5/docs/v4-to-v5.md#legacy-mode) (v5 is still in progress..)

**Comment by zhiyan114** [comment]
The progress is referring to the libaray I'm using that relies on node-redis and thanks for the confirmation.
