### ISSUE TITLE
node-redis throw syntax error on FT.SEARCH query

### ISSUE THREAD

**Issue by DenisLutsky** [redis/node-redis#2574]
### Description

Expected result
https://redis.io/docs/interact/search-and-query/search/vectors/
`FT.SEARCH idx "*=>[KNN 10 @vec $BLOB]" PARAMS 2 BLOB "\x12\xa9\xf5\x6c" DIALECT 2`

Actual result
```ts
async function searchSimilar(vector: number[]) {
  const query = "*=>[KNN 10 @embedding $BLOB]";

  const options = {
    PARAMS: {
      BLOB: Buffer.from(new Float32Array(vector).buffer),
      DIALECT: 2,
    },
  };

  const result = await client.ft.search("idx:answers", query, options);

  return result;
}
```

### Node.js Version

v18.16.1

### Redis Server Version

Redis version=6.2.13

### Node Redis Version

4.6.7

### Platform

Ubuntu 22.04.2 LTS (WSL2)

### Logs

```bash
[ErrorReply: Syntax error at offset 1 near >[]
```

**Comment by leibale** [comment]
The `DIALECT` should be directly in `options`, not in `options.PARAMS` (with your code sent to the server as a "user param" that is not in use...):

```javascript
async function searchSimilar(vector: number[]) {
  const query = "*=>[KNN 10 @embedding $blob]";

  const options = {
    PARAMS: {
      blob: Buffer.from(new Float32Array(vector).buffer)
    },
    DIALECT: 2
  };

  const result = await client.ft.search("idx:answers", query, options);

  return result;
}
```

**Comment by DenisLutsky** [comment]
> The `DIALECT` should be directly in `options`, not in `options.PARAMS` (with your code sent to the server as a "user param" that is not in use...):
> 
> ```js
> async function searchSimilar(vector: number[]) {
>   const query = "*=>[KNN 10 @embedding $blob]";
> 
>   const options = {
>     PARAMS: {
>       blob: Buffer.from(new Float32Array(vector).buffer)
>     },
>     DIALECT: 2
>   };
> 
>   const result = await client.ft.search("idx:answers", query, options);
> 
>   return result;
> }
> ```

Thanks, I just get tired with this one and didn't see a tree in a forest.

**Comment by leibale** [comment]
@DenisLutsky I'm not gonna lie, this command is a bit confusing, but it's not something we can "hide" on the client side...

**Comment by DenisLutsky** [comment]
> @DenisLutsky I'm not gonna lie, this command is a bit confusing, but it's not something we can "hide" on the client side...

No, it's not you. I was inattentive and didn't see your examples. So I had to find the answers in different sources and in the end, I put `DIALECT` in wrong and section and I couldn't understand what I'm doing wrong
