### ISSUE TITLE
scanIterator method is not working as expected

### ISSUE THREAD

**Issue by nzmksk** [redis/node-redis#2578]
### Description

```JavaScript
const isTokenBlacklisted = async (employeeId, accessToken) => {
  try {
    let blacklistArray = [];

    const patternOptions = ["MATCH", `${employeeId}:BT*`];

    for await (const key of redis.scanIterator(0, patternOptions)) {
      if (key.startsWith(`${employeeId}:BT`)) {    // I have to add this line to make the function works as intended
        const blacklistedToken = await redis.get(key);
        blacklistArray.push(blacklistedToken);
      }
    }

    return blacklistArray.includes(accessToken);
  } catch (error) {
    ...
  }
};
```

The `scanIterator` method in the provided code is intended to iterate over all keys that match a specific pattern, i.e. keys associated with `employeeId` that are concatenated with `BT`. However, there seems to be an issue with the method's functionality, requiring the addition of an extra conditional statement to achieve the desired behavior.

If the conditional statement is not written, the `scanIterator` method will iterate all available keys, regardless of the specified pattern. Consequently, tokens that are not associated with the provided `employeeId` could potentially be added to the `blacklistArray`, leading to incorrect results when checking for the validity of the `accessToken`.

### Node.js Version

18.13.0

### Redis Server Version

7.0.12

### Node Redis Version

4.6.7

### Platform

Linux Ubuntu

**Comment by leibale** [comment]
the first argument for `scanIteartor` is an object with optional fields, one of them is `MATCH`:
```javascript
redis.scanIterator({
  MATCH: `${employeeId}:BT*`
});
```
see [here](https://github.com/redis/node-redis#scan-iterator) for more deatils.
