### ISSUE TITLE
Reconnect doesn't seem to work

### ISSUE THREAD

**Issue by vpzomtrrfrt** [redis/node-redis#2584]
### Description

According to <https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#reconnect-strategy>, there's supposed to be a default reconnection strategy of `retries => Math.min(retries * 50, 1000)`. But in my testing, this doesn't seem to be happening. Using the below code, if the connection fails then the program just exits without even reaching either "got value" or "got error".

```
const redis = require("redis");
const client = redis.createClient({url: "redis://localhost:6379"});

client.connect()
    .catch(err => {
        console.error("connection failed:", err);
    });

client.get("foo")
    .then(value => {
        console.log("got value:", value);
    })
    .catch(err => {
        console.error("got error:", err);
    });
```

### Node.js Version

v16.20.1

### Redis Server Version

7.0.12

### Node Redis Version

4.6.7

### Platform

Linux

### Logs

```bash
connection failed: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by iwpnd** [comment]
```
const redis = require("redis");
const client = redis.createClient({url: "redis://localhost:6379"}).on('error', (error) => console.log('error occured: ', error));

client.connect()
    .catch(err => {
        console.error("connection failed:", err);
    });

client.get("foo")
    .then(value => {
        console.log("got value:", value);
    })
    .catch(err => {
        console.error("got error:", err);
    });
```

if you're not handling the error event the application will exit before even considering a retry i think.

**Comment by vpzomtrrfrt** [comment]
That does seem to work, really seems like it should be in the docs though

**Comment by iwpnd** [comment]
https://github.com/redis/node-redis#events

**Comment by vpzomtrrfrt** [comment]
fair enough
