### ISSUE TITLE
Client received an unexpected reply

### ISSUE THREAD

**Issue by natanaelsimoes** [redis/node-redis#2597]
### Description

Our server has been running normally and stable for a few months now, but it got down because of a supposedly unexpected reply being processed by the client.

I'm suspecting of unexpected reply since every reply shifts from `#waitingForReply`. If a shift happened and it returned undefined, the client may not have sent the command but received a message from Redis anyway. Can you guys help me think about what might be causing that? Is this a common issue caused by any misusage of the library?

### Node.js Version

16.19

### Redis Server Version

6.0.16

### Node Redis Version

4.3.0

### Platform

Linux

### Logs

```bash
TypeError: Cannot destructure property 'resolve' of '__classPrivateFieldGet(...).shift(...)' as it is undefined.
    at Object.onReply (/var/common/node_modules/[4m@redis[24m/client/dist/lib/client/commands-queue.js:62:25)
    at RESP2Decoder.write (/var/common/node_modules/[4m@redis[24m/client/dist/lib/client/RESP2/decoder.js:119:26)
    at RedisCommandsQueue.onReplyChunk (/var/common/node_modules/[4m@redis[24m/client/dist/lib/client/commands-queue.js:154:72)
    at RedisSocket.<anonymous> (/var/common/node_modules/[4m@redis[24m/client/dist/lib/client/index.js:390:84)
    at RedisSocket.emit (node:events:513:28)[39m
    at RedisSocket.emit (node:domain:489:12)[39m
    at Socket.<anonymous> (/var/common/node_modules/[4m@redis[24m/client/dist/lib/client/socket.js:202:42)
    at Socket.emit (node:events:513:28)[39m
    at Socket.emit (node:domain:489:12)[39m
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by natanaelsimoes** [comment]
> Some Redis features (PubSub, `MONITOR`, and some more) are pushing messages to the client (without a comment being executed for every message). If you are using `.sendCommand` to enable one of these features it'll throw this error:
> 
> ```js
> await client.sendCommand(['MONITOR']);
> await client.sendCommand(['SUBSCRIBE', 'channel']);
> ```

@leibale we use only `on`, `connect`, `disconnect`, `get`, `set`, `del` and `scanIterator`

**Comment by leibale** [comment]
@natanaelsimoes And you are using a standard redis build? docker?

**Comment by natanaelsimoes** [comment]
@leibale Standard build, running with default install, from a dedicated EC2 machine on AWS

**Comment by leibale** [comment]
Can you please log the reply it self? it might help us understand the issue..

**Comment by leibale** [comment]
> Can you please log the reply it self? it might help us understand the issue..

the easiest way to do it is using the [`patch-package`](https://www.npmjs.com/package/patch-package) package

**Comment by leibale** [comment]
BTW, the reason the reply is not included in the error itself is to avoid data leaking.. maybe we should add a boolean config to enable that (something like `unsafeErrors` which will be `false` by default, but can be enabled to debug such issues)?

**Comment by XRFate** [comment]
> > Can you please log the reply it self? it might help us understand the issue..
> 
> the easiest way to do it is using the [`patch-package`](https://www.npmjs.com/package/patch-package) package

Debug Code: 
` console.log('this------', this);`
` console.log("waitingForReply---------", _RedisCommandsQueue_waitingForReply);`
`  var debug = __classPrivateFieldGet(this, _RedisCommandsQueue_waitingForReply, "f");`
`  console.log(debug);`
`  const { resolve, reject } = debug.shift();`

Here is the consoleLog

`this------ RedisCommandsQueue {}`
`waitingForReply--------- WeakMap { <items unknown> }`
`Yallist { tail: null, head: null, length: 0 }`

**Comment by XRFate** [comment]
> > > Can you please log the reply it self? it might help us understand the issue..
> > 
> > 
> > the easiest way to do it is using the [`patch-package`](https://www.npmjs.com/package/patch-package) package
> 
> Debug Code: ` console.log('this------', this);` ` console.log("waitingForReply---------", _RedisCommandsQueue_waitingForReply);` ` var debug = __classPrivateFieldGet(this, _RedisCommandsQueue_waitingForReply, "f");` ` console.log(debug);` ` const { resolve, reject } = debug.shift();`
> 
> Here is the consoleLog
> 
> `this------ RedisCommandsQueue {}` `waitingForReply--------- WeakMap { <items unknown> }` `Yallist { tail: null, head: null, length: 0 }`

Here is the reply

> reply--------- [ErrorReply: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. If you 
want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis 
from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode 
by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a an authentication password for the default user. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.]

**Comment by leibale** [comment]
Oh I forgot about that thing.. So just fix that and it should work. There's already an open issue about that (#2417)

**Comment by natanaelsimoes** [comment]
@leibale @XRFate thank you guys for the quick responses! I will talk to our team about the workarounds you pointed me here. Hope everything goes well. I will keep watching over the issue #2417 from now on. Really appreciate your help!
