### ISSUE TITLE
Failed to compile with typescript

### ISSUE THREAD

**Issue by XRFate** [redis/node-redis#2600]
### Description

` export function testRedisConnect(){`
`   var client = redis.createClient({`
`       url: ""`
`   });`
  `  var cb =  function (err, reply) {`
 `       console.log(reply);`
`    }`
  `  client.get("test",cb);`
`}`

error on ***("test",cb)***
Typescript 5.1.6 

> TS2345: Argument of type  ["test", (err: Error, reply: string) => void]  is not assignable to parameter of type
[key: RedisCommandArgument] | [options: CommandOptions<ClientCommandOptions>, key: RedisCommandArgument]
Type  ["test", (err: Error, reply: string) => void]  is not assignable to type
[options: CommandOptions<ClientCommandOptions>, key: RedisCommandArgument]
Type at position  0  in source is not compatible with type at position  0  in target.
Type  string  is not assignable to type  CommandOptions<ClientCommandOptions> 
Type  string  is not assignable to type  { readonly [symbol]: true; } 

### Node Redis Version

4.6.7

**Comment by leibale** [comment]
1. V4 works with `Promise`s, not callbacks.
2. You did not call `client.connect()` before using the client
3. You should reuse the client all over the app, not open and close a client for each command you wanna run

**Comment by XRFate** [comment]
> 1. V4 works with `Promise`s, not callbacks.
> 
>     2. You did not call `client.connect()` before using the client
> 
>     3. You should reuse the client all over the app, not open and close a client for each command you wanna run

Promises solves it. 😄
