### ISSUE TITLE
Have client.connect() return a Promise<client> instead of Promise<void>

### ISSUE THREAD

**Issue by franciscop** [redis/node-redis#2601]
### Motivation

It's not possible to create a client in a single step that defers the creation (even if async), so now if we need a promise of the client we need to do this:

```js
const storeProm = (async() => {
  const client = createClient();
  await client.connect();
  return client;
})();
// Can use the client promise
```

If I want to use Redis as a KV store, it needs to be initialized and awaited:

```js
const client = createClient();

// Need to await, which we might not yet be in the right place to do so
await client.connect();

const api = fch.create({ cache: { store: client } });
```

However it'd be nice if we could join both steps into one, so that it could be done in a single step without the extra syntax:

```js
const store = await createClient().connect();
const api = fch.create({ cache: { store }});
```

More specifically, I have a library called [Swear](https://www.npmjs.com/swear) that is able to very nicely wrap the creation promise and avoid any await at all until the "leaf" function is called and awaited:

```js
// Currently
const store = swear((async() => {
  const client = createClient();
  await client.connect();
  return client;
})());
await store.set('a', 'b');
await store.get('a');

// If .connect() returned a Promise<client>
const store = swear(createClient().connect());
await store.set('a', 'b');
await store.get('a');
```

### Basic Code Example

```JavaScript
// Would love to do this:
const store = await createClient().connect();
const api = fch.create({ cache: { store }});

// Which would also unlock also this with my library `swear`:
const store = swear(createClient().connect());
await store.set('a', 'b');
await store.get('a');
```

**Comment by franciscop** [comment]
I'd be happy to try giving it a stab at it, I believe it would be here:

```ts
// Before
connect(): Promise<void> {
    // see comment in constructor
    this.#isolationPool ??= this.#initiateIsolationPool();
    return this.#socket.connect();
}

// After
async connect(): Promise<void> {
    // see comment in constructor
    this.#isolationPool ??= this.#initiateIsolationPool();
    await this.#socket.connect();
    return this;
}
```

**Comment by leibale** [comment]
I like this idea! :) Wanna open a PR?

BTW, don't forget to add a listener to `error`  events as well, otherwise it will crash your application (see [here](https://github.com/redis/node-redis#events))

**Comment by bigDP** [comment]
Hi, Can i take this task?

**Comment by leibale** [comment]
@bigDP This is already done in #2602 (and should've been closed when I merged it, which did not happen for some reason). Sorry for the confusion, and thanks for wanting to contribute! :)

**Comment by franciscop** [comment]
Just wanted to come back to thank again for accepting this, I integrated it into my library Polystore and it works great!

```js
import kv from "polystore";
import { createClient } from "redis";

const store = kv(createClient().connect());

await store.set("key1", "Hello world", { expires: "1h" });
console.log(await store.get("key1"));
// "Hello world"
```

https://polystore.dev/documentation#redis
