### ISSUE TITLE
Vitest Cannot Spy on json property of client

### ISSUE THREAD

**Issue by prests** [redis/node-redis#2615]
### Description

If you create a client 

```ts
import { createClient } from 'redis';

const client = createClient();
```

you can see that `json` exists and can be used on the type

however when trying to mock various properties like `client.json.get(...)` vitest cannot find any of its properties

```ts
import { vi } from 'vitest';

// valid
client.json.get(...)

// not found
vi.spyOn(client, 'json.get')
```

I'm assuming jest will probably have this problem too?

### Node.js Version

18

### Redis Server Version

N/A

### Node Redis Version

4.6.7

### Platform

macOS

### Logs

```bash
Error: json.get does not exist
```

**Comment by leibale** [comment]
TBH I'm not too sure about vitest, but I believe `vi.spyOn(client.json, 'get')` should work..

**Comment by prests** [comment]
Whoops. Good catch haha worked on vitest too
