### ISSUE TITLE
 SyntaxError: Unexpected token '??=' in @redis/client

### ISSUE THREAD

**Issue by ashfaqhaq** [redis/node-redis#2616]
### Description

**Issue description**:

While running my Next.js application, I encountered a syntax error originating from the `@redis/client` module. 

**Error Details**:
```
File: /var/app/current/node_modules/@redis/client/dist/lib/client/index.js
Line: 195
Error: this[name.toLowerCase()] ??= this[name];
        ^^^
       SyntaxError: Unexpected token '??='

Stack Trace:
- at wrapSafe (internal/modules/cjs/loader.js:1029:16)
- at Module._compile (internal/modules/cjs/loader.js:1078:27)
- at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
- at Module.load (internal/modules/cjs/loader.js:979:32)
- at Function.Module._load (internal/modules/cjs/loader.js:819:12)
- at Module.require (internal/modules/cjs/loader.js:1003:19)
- at require (internal/modules/cjs/helpers.js:107:18)
- at Object.<anonymous> (/var/app/current/node_modules/@redis/client/dist/index.js:18:18)
- at Module._compile (internal/modules/cjs/loader.js:1114:14)
- at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

Additional Information:
npm ERR! code ELIFECYCLE
```

**Environment Details**:

- Node.js version: Node.js 14 running on 64bit Amazon Linux 2/5.8.5
- Next.js version:  "next": "^10.0.4",

### Node.js Version

14

### Platform

Linux

**Comment by CuteTechGuy** [comment]
You should use node v15 or higher. The last version redis@4.6.9 has some breaking changes for the node v14. Also node v14 is deprecated and I suggest you to use v16 or v18 which is LTS for now. Or you can fix your redis to 4.6.0 as a temporary solution.

**Comment by grelca** [comment]
while i agree that we should all be updating our EOL node versions, patch versions should not introduce breaking changes. i would call dropping support for older node versions a breaking change.

**Comment by davebullock-ujet** [comment]
This is a breaking change and should be rolled back.

**Comment by bsaracalign** [comment]
Can you guys please do a major release if you are updating something that'll break people's working stuff? All morning our builds are failing and while I do agree people should keep their stuff up to date and you do that too, which is great but make major update so it doesnt screw up 100,000 applications that are using this and running fine...

**Comment by abhisheksingh75** [comment]
Ya same is happing with us...is there any update on this issue
