### ISSUE TITLE
unexpected token '('

### ISSUE THREAD

**Issue by Prabha-koinpark** [redis/node-redis#2617]
### Description

Hi,
From Today morning onwards redis npm packages giving error like 

unexpected token '('

Node Version V14

redis version 4.6.3

we tried 4.6.0 , 4.6.7 also.. 

but same error from today morning onwards only.

### Node.js Version

v14

### Redis Server Version

5.0.8

### Node Redis Version

4.6.3

### Platform

linux

### Logs

```bash
SyntaxError: unexpected token '('
```

**Comment by Didas-git** [comment]
This issue is due to the removal of support for node 14 & 16, you can check more in:
#2616 #2618
