### ISSUE TITLE
Can not install redis on node 16.14.2 because @redis/client@1.5.10 requires node >=18

### ISSUE THREAD

**Issue by dechkopetrov** [redis/node-redis#2618]
### Description

Currently I cannot install redis because of @redis/client dependency . yarn is throwing error because the node version is not compatible. Currently I am on node 16.14.2. I just checked @redis/client@1.5.9 requires  ` "engines": {    "node": ">=14"  } `  and now @redis/client@1.5.10 requires  ` "engines": {    "node": ">=18"  } `  .... Thats major 4 versions difference. Can some explain why ?  

https://github.com/redis/node-redis/blob/redis%404.6.9/packages/client/package.json#L39

### Node.js Version

16.14.2

### Platform

linux

**Comment by aosatinskyzengo** [comment]
same here

**Comment by Didas-git** [comment]
There was a conversation on [discord](https://discord.com/channels/697882427875393627/865653905299865600/1154484589323096184) about this.
A fast resume:
Node16 EOL was declared by node team 10 days ago so now LTS/minimum is node 18, however this should have been a minor release and not a patch release
