### ISSUE TITLE
Version 4.6.9 breaking on Node 14.21.3 LTS

### ISSUE THREAD

**Issue by RohitFL** [redis/node-redis#2619]
### Description

Redis Version 4.6.9 is breaking on Node 14 due to this[name.toLowerCase()] ??= this[name]; Unexpected ??= token issue

### Node.js Version

14.21.3

### Node Redis Version

4.6.9

### Platform

MacOS

**Comment by Didas-git** [comment]
In node-redis version 4.6.9 the minimum node version is 18
This is something that is declared on at least the `client` package but seems to be missing on the main one, parhaps @leibale could add it to the main package.json

**Comment by croconut** [comment]
i think the big question here is why npm doesnt warn me by default about engine resolution issues in my dependency graph. 

i added that command to my npm config, but why is it something that we need to turn on manually... found another issue with lru-cache, so im basically forced into freezing my lru-cache version / whatever depends on it and then upgrading to node 16 pretty much asap.

glad this got fixed tho
