### ISSUE TITLE
ZRANGE with LIMIT inside MULTI doesn't work

### ISSUE THREAD

**Issue by edgework** [redis/node-redis#2633]
### Description

When I call this 

multi.ZRANGEBYSCORE('zlist', 2, 4, 'LIMIT', 1 , 2, 'WITHSCORES');

In a redis-cli with MONITOR running I get this

1697839213.111413 [0 127.0.0.1:63875] "MULTI"
1697839213.111516 [0 127.0.0.1:63875] "ZRANGE" "zlist" "2" "4"
1697839213.111527 [0 127.0.0.1:63875] "EXEC"

So clearly limit and withscores is ignored.    Outside of multi I can get around this by using  sendCommand  but  multi does not seem to support sendCommand.

This happens for mostly any command with extended parameters like   NX,  BYLEX etc. etc.   Also  ZREVRANGE is totally unsupported in multi.

I suggest you at least implement sendCommand for multi so we can stop using depreciated versions of the commands.

### Node.js Version

18+

### Redis Server Version

6.2.5

### Node Redis Version

redis@4.6.10

### Platform

MacOS and Linux

**Comment by leibale** [comment]
1. Optional parameters are usually are in an optional object as the last parameter. TS/TS language server (which works automatically in most modern IDE) should be able to show you the function signature for all commands. You can read more about it [here](https://github.com/redis/node-redis#redis-commands).
2. The `WITHSCORES` argument is implemented as a different command to allow for better types (without WITHSCORES - an array of strings, with it - an array of objects).
3. `multi.addCommand` is the equivalent of `client.sendCommand` for multi

```javascript
// this is equivalent to ZRANGEBYSCORE zlist 2 4 LIMIT 1 2
client.ZRANGEBYSCORE('zlist', 2, 4, {
  LIMIT: {
    offset: 1,
    count: 2
  }
);

// this is equivalent to ZRANGEBYSCORE zlist 2 4 LIMIT 1 2
client.ZRANGEBYSCORE_WITHSCORES('zlist', 2, 4, {
  LIMIT: {
    offset: 1,
    count: 2
  }
);
```

**Comment by edgework** [comment]
It would be nice if the documentation at https://www.npmjs.com/package/redis    includes these tidbits.

**Comment by leibale** [comment]
1. https://www.npmjs.com/package/redis#redis-commands
2. It's not practical to include examples for all the commands..
3. `sendCommand` implies that it's going be to sent to the server immediately, but in the context of MULTI it will only be sent when you call `exec`.
4. Be more respectful, nobody owes you anything.

**Comment by edgework** [comment]
> 1. https://www.npmjs.com/package/redis#redis-commands

Incomplete.  No mention of  callCommand etc.

> 2. It's not practical to include examples for all the commands..

Not asking for that,  but maybe have something for stuff like  LIMIT or WITHSCORES? 

> 3. `sendCommand` implies that it's going be to sent to the server immediately, but in the context of MULTI it will only be sent when you call `exec`.

Well then DOCUMENT THAT!


> 4. Be more respectful, nobody owes you anything.

I totally understand now why the 3.x version has significantly more monthly downloads than the 3.x version.  You made a bunch of changes, mostly unnecessary. The "js friendly" stuff could have been an addition not a replacement. Not only that, you didn't bother to document most of them.  Whatever.

**Comment by leibale** [comment]
1. https://www.npmjs.com/package/redis?activeTab=readme#unsupported-redis-commands
2. https://www.npmjs.com/package/redis?activeTab=readme#unsupported-redis-commands:~:text=Modifiers%20to%20commands%20are%20specified%20using%20a%20JavaScript%20object%3A
3. That should be documented. PRs are welcome.
4. Thank you for your kind words. I won't be answering messages from you with that attitude anymore.
