### ISSUE TITLE
LMPOP doesn't work

### ISSUE THREAD

**Issue by rick-rheo** [redis/node-redis#2639]
### Description

None of the following work 
```
client.LMPOP(3, 'lmlist1', 'lmlist2', 'lmlist3', 'LEFT', 'COUNT', '2'})
client.LMPOP(3, 'lmlist1', 'lmlist2', 'lmlist3', 'LEFT', {COUNT: 2})
client.LMPOP(['lmlist1', 'lmlist2', 'lmlist3'], 'LEFT', {COUNT: 2})
client.sendCommand(['LMPOP', '3', 'lmlist1', 'lmlist2', 'lmlist3', 'LEFT', 'COUNT', '2'])
```

Errors:  
```
ERR unknown command `LMPOP`, with args beginning with: `3`, `lmlist1`, `lmlist2`, `lmlist3`, `LEFT`, `COUNT`, `2`, 

or

TypeError: Invalid argument type
```   

While against the same server using redis-cli
```
lmpop 3 lmlist1 lmlist2 lmlist3 LEFT COUNT 2
```
works fine.

Same thing for BLMPOP

### Node.js Version

18

### Redis Server Version

7

### Node Redis Version

redis@4.6.10

### Platform

Linux

**Comment by leibale** [comment]
I just tried
```
client.LMPOP(['lmlist1', 'lmlist2', 'lmlist3'], 'LEFT', {COUNT: 2});
```
and it works for me.. am I missing something?

**Comment by edgework** [comment]
It definitely does not work for me.  Are you running  redis@4.6.10 ?  

<img width="1015" alt="image" src="https://github.com/redis/node-redis/assets/5122883/9b8c753c-9f2e-420e-9561-d1dec4f4b01e">

**Comment by rick-rheo** [comment]
It definitely does not work for me.  Are you running 4.6.10?

<img width="1008" alt="image" src="https://github.com/redis/node-redis/assets/26754458/1a5f96ae-fa54-4342-911c-4ff25b5af02a">

**Comment by rick-rheo** [comment]
It definitely does not work for me.  Are you using 4.6.10?

<img width="1008" alt="image" src="https://github.com/redis/node-redis/assets/26754458/ad1e5f83-51d7-4850-b0b2-739d6bb8c06f">
