### ISSUE TITLE
BZMPOP doesn't work

### ISSUE THREAD

**Issue by rick-rheo** [redis/node-redis#2640]
### Description

None of the following work

```
client.BZMPOP(0, 1, 'myzset', 'MIN');
client.BZMPOP('0', '1', 'myzset', 'MIN');
client.BZMPOP('0', '1', 'myzset', 'MIN', {COUNT: 1});
```

First returns with error:

```
Invalid argument type
```

Last two return with error:

```
ERR unknown command `BZMPOP`, with args beginning with: `0`, `1`, `1`, `myzset`, 
```

Using sendCommand works  but  sendCommand does not seem to support isolated connections.

### Node.js Version

18

### Redis Server Version

7

### Node Redis Version

redis@4.6.10

### Platform

Linux

**Comment by leibale** [comment]
The command wrapper is preparing the `numkeys` argument for you.. if you are using TypeScript (or an IDEA with TS Language Server) it should be able to show you the function signature.

```typescript
type BZMPOPArguments = [
  timeout: number,
  keys: string | Buffer | Array<string | Buffer>,
  side: 'MIN' | 'MAX',
  options?: { COUNT: number }
];

client.BZMPOP(0, 'myzset', 'MIN');
client.BZMPOP(0, 'myzset', 'MIN', { COUNT: 1 });
client.BZMPOP(0, ['myzset1', 'myzset2'], 'MIN');
client.BZMPOP(0, ['myzset1', 'myzset2'], 'MIN', { COUNT: 1 });
```

**Comment by rick-rheo** [comment]
Not for me

<img width="1001" alt="image" src="https://github.com/redis/node-redis/assets/26754458/0e25aa14-448d-4956-9a19-8442cb47a10c">
