### ISSUE TITLE
DUMP / RESTORE broken

### ISSUE THREAD

**Issue by rick-rheo** [redis/node-redis#2649]
### Description

The following code fails with error `ERR DUMP payload version or checksum are wrong`

```
await client.set('dumpme', 'yayayayayayayaya');

const dumped = await client.dump('dumpme');

await client.del('dumpme');

let res = await client.restore('dumpme', 0, dumped);
```

### Node.js Version

18+

### Redis Server Version

7

### Node Redis Version

redis@4.6.10

### Platform

MacOS and Linux

**Comment by leibale** [comment]
By default, the client converts redis "blob string" into javascript strings, which is a "lossy" transformation if the data is not 
"utf8 safe". You should use the `returnBuffers` option for that:
```javascript
await client.set('dumpme', 'yayayayayayayaya');
const dump = await client.dump(client.commandOptions({ returnBuffers: true }), 'dumpme');
// dump is a buffer now, not a string
await client.restore('dumpme', 0, dump);
```

BTW, I'm pretty sure that you'll get an error if you dump and restore to the same key without using the `REPLACE` option

**Comment by rick-rheo** [comment]
Your suggestion works.  Thanks
