### ISSUE TITLE
Session max age gets disregarded when in cluster mode

### ISSUE THREAD

**Issue by sbsg35** [redis/node-redis#2656]
### Description

Session maxAge gets disregarded when using cluster mode along with `express-session` and `connect-redis`.
The session TTL from the `cookie.maxAge` is not applied. 

When I switch out for `ioredis`, it works as expected. It also works when I have a single node using the `createClient` constructor.

To recreate:
1. Start up a cluster. I used the [create cluster script](https://github.com/redis/redis/tree/unstable/utils/create-cluster) to achieve this.
2. Dependencies:
```
    "connect-redis": "^7.1.0",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "redis": "^4.6.11",
```
3. Run the following code and visit http://localhost:3000/

```javascript
import RedisStore from "connect-redis";
import session from "express-session";
import { createCluster } from "redis";

import express from "express";
const app = express();

const redisClient = createCluster({
  rootNodes: [
    {
      socket: {
        host: "127.0.0.1",
        port: 7001,
      },
    },
  ],
  useReplicas: true,
});

redisClient.connect().catch(console.error);

let redisStore = new RedisStore({
  client: redisClient,
  prefix: "myapp:",
});

app.use(
  session({
    store: redisStore,
    resave: true,
    saveUninitialized: false, 
    secret: "mysecret",
    cookie: {
      secure: false,
      httpOnly: false,
      maxAge: 30 * 1000, // 30 seconds
    },
  })
);

app.get("/", (req, res) => {
  const sess = req.session;
  (sess as any).userId = "87098798";
  (sess as any).otherData = "abc";
  res.send("Hello World!");
});

app.listen(3000, () => {
  console.log(`Example app listening on port 3000`);
});
```

4. Inspect your redis store and you can see that the TTL has no limit
<img width="605" alt="image" src="https://github.com/redis/node-redis/assets/137849468/af64c4e0-cf6e-4060-a66b-40a4d4cb0b01">

### Node.js Version

18.17.0

### Redis Server Version

7.2.3

### Node Redis Version

4.6.11

### Platform

macOS

**Comment by leibale** [comment]
This is a bug in `connect-redis` which uses `"scanIterator" in client` to check if a client is a node-redis client, which will be `false` when using a cluster, because `scanIterator` is not implemented on `RedisCluster` (BTW, having `scanIterator` on `RedisCluster`.

On top of that, the [`scanIterator`](https://github.com/tj/connect-redis/blob/master/index.ts#L65) function (which is used by `clear`, `length`, `ids`, and `all`) won't work as expected with ioredis, because the scan command will be redirected to a random node every time, and you'll see different results.

**Comment by sbsg35** [comment]
nice thanks @leibale you just bet me to it :)
I realised that it was an issue with `connect-redis` and [created an issue there](https://github.com/tj/connect-redis/issues/404).
