### ISSUE TITLE
RPOP and LPOP do not support count argument

### ISSUE THREAD

**Issue by ajmichels** [redis/node-redis#2668]
### Motivation

In Redis v6.2 a second argument was added to the [RPOP](https://redis.io/commands/rpop/) and [LPOP](https://redis.io/commands/lpop/) commands that allows for specifying a `count` of items that should be attempted to fetch from a list. It doesn't look like this support has been added to the library yet. Without these extra arguments is the necessary to perform a multi-command request. I realize it is possible to use `client.sendCommand(['RPOP', 'key', '10'])`, I am just not sure what this project's stance is on feature parity.

Adding support for this would require that RPOP and LPOP return different data types (string or array) depending on the arguments given.

### Basic Code Example

```JavaScript
await client.RPOP('myKey');
// 'value'

await client.RPOP('myKey', 1);
// ['value']

await client.RPOP('myKey', 2);
// ['value1', 'value2']
```

**Comment by leibale** [comment]
since the count argument changes the reply type it is exposed as `RPOP_COUNT`/`rPopCount`

**Comment by ajmichels** [comment]
Thanks. That is helpful.

Out of curiosity, how was one supposed to know that was available in the API? I have run into numerous situations where situations where "out of the box commands" don't really work but there isn't really anything in the docs for this package explaining that.
