### ISSUE TITLE
Improve connection speed by running fewer commands

### ISSUE THREAD

**Issue by chayim** [redis/node-redis#2675]
### Description

Today, connecting to a Redis instance, involves running multiple commands, and parsing the response repeatedly, this includes usage such as [setinfo](https://redis.io/commands/client-setinfo), which itself is run twice. The example below illustrates, that it's possible to pass all connection configuration information within a pipeline. In turn, the HELLO call returns the version of Redis, which could perhaps be used later for other things.

This is marked as _good-first-issue_ not because it's necessarily easy to implement, inasmuch as it's a good entrypoint, to learning how connections to redis occur.

```
127.0.0.1:6379> multi
OK
127.0.0.1:6379(TX)> auth bob smurf
QUEUED
127.0.0.1:6379(TX)> select 5
QUEUED
127.0.0.1:6379[5](TX)> hello 3
QUEUED
127.0.0.1:6379[5](TX)> client setinfo lib-name predis
QUEUED
127.0.0.1:6379[5](TX)>  client setinfo lib-ver 55.5.0
QUEUED
127.0.0.1:6379[5](TX)> client tracking on optin
QUEUED
127.0.0.1:6379[5](TX)> CLIENT caching yes
QUEUED
127.0.0.1:6379[5](TX)> exec
1) OK
2) OK
3) 1# "server" => "redis"
   2# "version" => "7.2.3"
   3# "proto" => (integer) 3
   4# "id" => (integer) 26
   5# "mode" => "standalone"
   6# "role" => "master"
   7# "modules" => (empty array)
4) OK
5) OK
6) OK
7) OK
127.0.0.1:6379[5]> 
```

**Comment by leibale** [comment]
Node-Redis already pipelines those commands (not in a `MULTI`, but the client does not wait for responses to execute the next commands. See [here](https://github.com/redis/node-redis/blob/master/packages/client/lib/client/index.ts#L266).)..
