### ISSUE TITLE
Is there support for READONLY commands?

### ISSUE THREAD

**Issue by jake-chambers** [redis/node-redis#2683]
### Description

I am using Elasticache with cluster mode disabled. I have a primary node, and 2 read replicas. All of my reads are going to the primary node, and the read replicas aren't being used. In the Redis documentation it says we can use the readonly command to leverage the read replicas. 

How can this be done using this library?

**Comment by leibale** [comment]
You can enable reading from replicas using the `useReplicas` flag for `createCluster` (see [here](https://github.com/redis/node-redis/blob/master/docs/clustering.md)), or if you wish to connect to the replica directly yourself, you can use the `readonly` flag for `createClient` (see [here](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md)).
