### ISSUE TITLE
how to use no_ready_check in version 4?

### ISSUE THREAD

**Issue by jackwoods** [redis/node-redis#2686]
### Description

We want to use twemproxy

**Comment by jackwoods** [comment]
Seems no need to use this option, can already use twemproxy.

**Comment by jackwoods** [comment]
but when use the version 4.1.12, it fails
tried on 4.1.10, it can work.

**Comment by jackwoods** [comment]
found this: 
disableClientInfo:true,

**Comment by ShaharBenEzra7** [comment]
Hey Jackwoods, where did you find the option to add the disableClientInfo configuration?
