### ISSUE TITLE
No way to quit a BLOCKed connection?

### ISSUE THREAD

**Issue by PaulHamdinger** [redis/node-redis#2746]
Am I right in understanding that there is no way to disconnect a client while that client is blocking? I have a script where I keep an XREAD open indefinitely with BLOCK 0, but when it's time to exit my script I can't call quit() (it never completes) or disconnect() ("DisconnectsClientError").

```
...
redis_client.sendCommand( [ `XREAD`, `BLOCK`, `0`, `STREAMS`, `foo:bar`, `$` ] );
await redis_client.quit(); // Queue'd forever? Never run.
await redis_client.disconnect(); // Error : DisconnectsClientError: Disconnects client at Commander.disconnect...
...
```

**Comment by leibale** [comment]
Redis (the server) processes commands in order, so `QUIT` will wait for `XREAD BLOCK` to finish before processing the `QUIT` command.
Regarding `disconnect` - that should work, but it'll make the sendCommand promise throw `DisconnectsClientError` which you'll need to catch.

```javascript
client.sendCommand([`XREAD`, `BLOCK`, `0`, `STREAMS`, `foo:bar`, `$` ])
  .then(result => {
    // this will be called if/when the command is process successfully
  })
  .catch(err => {
    // this will be called if/when the command did not process successfully for any reason, including calling `disconnect` before the command is finished
  });

await client.disconnect(); // will cause any running commands to throw/be rejected with `DisconnectsClientError`
```

**Comment by PaulHamdinger** [comment]
Thanks for the help, that works.
