### ISSUE TITLE
Not able to work with binary data (gzip)

### ISSUE THREAD

**Issue by skhaz** [redis/node-redis#2748]
### Description

It's impossible to retrieve the data; although it's set correctly, when I attempt to decompress the data from Redis, I receive an error saying that the header is invalid. However, the data within Redis appears to be fine, and decompressing the original compressed data works without issues.

As you can see, the data is compressed using gzip and stored in Redis with the correct encoding:

<img width="1582" alt="Screenshot 2024-05-03 at 14 28 50" src="https://github.com/redis/node-redis/assets/46259/913da45f-d9fd-4254-be6e-ed43a7987a07">

Sample code:

```typescript
import { promisify } from 'node:util'
import { gzip } from 'node:zlib'
import { gunzip } from 'node:zlib'

import { redis } from '~/library/provider'

const asyncGzip = promisify(gzip)
const asyncGunzip = promisify(gunzip)

export async function handler() {
  try {
    await redis.connect()
  } catch (/* c8 ignore next */ error) {}

  const compressed = await asyncGzip(Buffer.from(JSON.stringify({ ok: true })))

  await redis.set('gzip', compressed) // OK

  console.log('>>> compressed', compressed)

  const data = (await redis.get('gzip')) || Buffer.from('{}')

  console.log('>>> data', data)

  const payload = await asyncGunzip(compressed) // OK!

  console.log('>>> payload', payload)

  const decompressed = await asyncGunzip(data) // FAIL

  console.log('>>> decompressed', decompressed.toString())

  await redis.disconnect()

  return {
    statusCode: 200,
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    body: JSON.stringify({ result: JSON.parse(decompressed.toString()) }),
  }
}
```

### Node.js Version

20.11.1

### Redis Server Version

6.2.6 (UpStash)

### Node Redis Version

4.6.13

### Platform

macOS & AWS Lambda

**Comment by leibale** [comment]
Converting `Buffer`s to `string`s is lossy (and when using `client.get`, the client will return a `string` by default, not a `buffer`).. use `await redis.get(client.commandOptions({ returnBuffers: true }), 'gzip')` to get the value as a buffer, then it should work.
