### ISSUE TITLE
How to handle Bigint cursor?

### ISSUE THREAD

**Issue by holopekochan** [redis/node-redis#2765]
Hi, I am running into a problem with Bigint cursor. I am currently using the redis library to connect with AWS ElastiCache Serverless. In the Redis CLI, I can perform a scan and receive the cursor value 9286422431637966426. However, in my program, this value is converted to 9286422431637965000. (I think it is larger than the "Number.MAX_SAFE_INTEGER" 9007199254740991 for Javascript) When I tried using client.scanIterator, it never stops and runs into an infinite loop. I also tested the client.scan function and found that the cursor number changes to 9286422431637965000, which is why the scan does not terminate.

Is there a configuration I could set to use Bigint from the library?

**Comment by holopekochan** [comment]
Found a configuration 'string_numbers' in the documentation. However, the scan operation is still returning a number instead of a "string number". The cursor is still converted to 9286422431637965000
Tried with the small code
`const client = redis.createClient({
    url: <my_redis_url>
    string_numbers: true
}); 

let test = async () => {
     try { 
        await client.connect() 
        const reply = await client.scan("0", 'MATCH', '*' , 'COUNT', '1000')
        console.log(reply)
     } catch (err) {
        console.error(err)
     }
}
test()
`

**Comment by leibale** [comment]
I'm guessing you are using v4.x? for this version the only way to solve it is to use `.sendCommand` directly:
```javascript
await client.sendCommand(['SCAN', '0', 'MATCH', '*', 'COUNT', '1000']);

async function* scanIterator() {
  let cursor = '0';
  do {
    const reply = await this.sendCommand(['SCAN', cursor, 'MATCH', '*', 'COUNT', '1000']);
    cursor = reply[0];
    yield reply[1];
  } while (cursor !== '0');
}

for await (const chunk of scanIterator()) {
  // ...
}
```
this is already fixed in v5 which you can try using `@redis/client@next`.

**Comment by holopekochan** [comment]
> ```js
> await client.sendCommand(['SCAN', '0', 'MATCH', '*', 'COUNT', '1000']);
> ```

Thank you. It works when using sendCommand. I will try v5 next. thank you
