### ISSUE TITLE
Not able to see node js as code snippets

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [redis/node-redis#2780]
### Description

I was reading redis docs but unable to find node js snippets for specific operations like lpop,lpush,blpop etc....
![image](https://github.com/redis/node-redis/assets/101992909/96c77f4d-af84-4bf3-8ae0-fad6d01306e3)
A few months ago there was a option of node js but now there is only java and python
Where i can find the node js syntax of these specific operations because i found node js redis documentation but there is only how to create client ,how to connect to redis etc etc
Can anybody help me with this?

**Comment by leibale** [comment]
@dmaier-redislabs @uglide

**Comment by uglide** [comment]
Some step names in doctests have mixed cases https://github.com/redis/node-redis/blob/emb-examples/doctests/dt-list.js#L65

cc @dwdougherty

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@uglide if we get the node js code snippets  also for these function on redis official docs site then it would be more helpful...

**Comment by dwdougherty** [comment]
Hi @uglide @Rudra-Sankha-Sinhamahapatra . Turns out, there's bug on the docs site that ignores Node.js code examples altogether. I'll fix this soon and close this issue as part of that commit.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Thanks for noticing this issue...

**Comment by dwdougherty** [comment]
You're welcome, @Rudra-Sankha-Sinhamahapatra . Please note that there are still quite a few missing Node.js examples for the data structures pages, but we're working to get those available as soon as possible.
