### ISSUE TITLE
Ability to start a transaction with WATCH.

### ISSUE THREAD

**Issue by chakrit** [redis/node-redis#329]
Since most `MULTI/EXEC` use cases does not work without a prior `WATCH` (and maybe a `GET` or `SMEMBERS` or something similar) to watch for key changes I suggest the following:

Provides a `.watch()` api that is similar to `.multi()` which gets executed at the time of `.exec()`

something like this:

``` javascript
redis.watch('someset') // starts a dedicated connection or something
  .sismember('someset', 'lock', function(e, ok) {
    // save state here or UNWATCH someset
  })
  .multi()
  .srem('someset', 'lock', function() { /* access state previously saved */ })
  .del('someset:lock', function() { /* access state previously saved */ })
  .exec()
```

Sorry if the use case isn't totally clear but I'm sure you can come up with a better example.

I actually encounter a lot of use cases similar to this and simply calling `.multi()` right away does not really help. I had to adds a `fork()` method instead to create a new connection in order to be able to achieve this.

**Comment by chakrit** [comment]
This is very unfortunate. All other Redis drivers on other platforms I have worked with have connection pooling mechanism built in. And this is never an issue on client-side code.

**Comment by BridgeAR** [comment]
@chakrit As far as I understand it this is a feature request to return a new redis instance that calls watch right after completion and returns that after finishing. Am I correct?

This could be implemented, but it would be backwards incompatible right now and therefor might need a new command for it. Adding individual commands is not all that nice though. This might be a good option to change the watch function in v.3.0 though.

**Comment by BridgeAR** [comment]
I am going to reopen this. I would not implement it as suggested but I think it is useful to have a mechanism so people can use atomic operations easier.

Refs: #1320

**Comment by funny-falcon-at-joomcode** [comment]
https://redis.io/topics/transactions
> Redis scripting and transactions
> A Redis script is transactional by definition, so everything you can do with a Redis transaction, you can also do with a script, and usually the script will be both simpler and faster.
