### ISSUE TITLE
Plan for cluster support

### ISSUE THREAD

**Issue by crzidea** [redis/node-redis#574]
Is there any plan for cluster support?
Redis 3.0.0 beta has been released for a month.

**Comment by danmaz74** [comment]
@brycebaril any updates regarding Redis cluster support? I read there was a refactoring going on, but didn't see any recent updates. Thanks!

**Comment by jadbox** [comment]
+1 for cluster support

**Comment by MetaThis** [comment]
+1

**Comment by shaharmor** [comment]
Redis cluster is out now, any chance to implement support for it now?

**Comment by thelinuxlich** [comment]
+1

**Comment by lemonizer** [comment]
:+1:

**Comment by sebbo2002** [comment]
+1

**Comment by julien51** [comment]
+1

**Comment by genediazjr** [comment]
@mranney any comments sir?

**Comment by henryoswald** [comment]
We (sharelatex.com) would be interested in sponsoring this feature if that helps. I am not sure how much work it would be to develop, potentially a few other companies would pitch in?

**Comment by thelinuxlich** [comment]
There are already two alternative modules which support Redis 3.0 cluster and are better performant than node-redis:

https://github.com/thunks/thunk-redis
https://github.com/luin/ioredis

**Comment by henryoswald** [comment]
Very interesting, thanks!

On Wed, Apr 29, 2015 at 12:24 PM, Alisson Cavalcante Agiani <
notifications@github.com> wrote:

> There are already two alternative modules which support Redis 3.0 cluster
> and are better performant than node-redis:
>
> https://github.com/thunks/thunk-redis
> https://github.com/luin/ioredis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mranney/node_redis/issues/574#issuecomment-97392398>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by simontabor** [comment]
I'd be happy to try and manage getting cluster support into node_redis. I think I've got a pretty good base at https://github.com/gosquared/redis-clustr (stable in production with many ops). If anyone has suggestions/would like to jump in then go ahead :)

**Comment by vivekkrbajpai** [comment]
:+1:

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reopening this as it is not resolved. @simontabor would you still be up to try getting cluster support into node_redis?

**Comment by simontabor** [comment]
Yeah. Will need to find some time - hopefully soon!

**Comment by BridgeAR** [comment]
@simontabor Sounds good :+1:

**Comment by BridgeAR** [comment]
I'd like to keep cluster as a separate module but usable as default from node_redis. Right now I'm trying to clean up all other things and this is not soon on my list, even though I think it's one of the most important things to be included soon.

So if someone is willing to help out, that would be great! @simontabor you said you won't have the time for it soon but if I remember correct you have a cluster module that could be moved to NodeRedis, if you agree, right?

**Comment by simontabor** [comment]
I've left GoSquared now, and the repo is under that organisation (https://github.com/gosquared/redis-clustr). I *think* they'd be willing to move the repo to NodeRedis org so long as there's a credit given to them, alternatively NodeRedis could quite easily fork the repo and continue to develop and maintain it over there.

**Comment by ohjames** [comment]
The top of the readme states: "complete and feature rich Redis client", with the absence of cluster support I might debate the usage of the world "complete" here.

**Comment by gsccheng** [comment]
... and now I have to migrate to ioredis: [https://github.com/luin/ioredis](https://github.com/luin/ioredis) . It is "full-featured" that supports Cluster, Sentinel, and Pipelining.

**Comment by BrainBacon** [comment]
@gsccheng In the same boat here. I was definitely under the impression that clustering would work.

**Comment by mvtcode** [comment]
I using redis 3.2.8 and setup nodes cluster

> { ReplyError: MOVED 8238 127.0.0.1:6380
>     at parseError (/home/tanmv/test/node_modules/redis-parser/lib/parser.js:181:12)
>     at parseType (/home/tanmv/test/node_modules/redis-parser/lib/parser.js:291:14)
>   command: 'SET',
>   args: [ 'test-4', 2017-02-27T07:39:07.656Z ],
>   code: 'MOVED' }

> { ReplyError: MOVED 8238 127.0.0.1:6380
>     at parseError (/home/tanmv/test/node_modules/redis-parser/lib/parser.js:181:12)
>     at parseType (/home/tanmv/test/node_modules/redis-parser/lib/parser.js:291:14) command: 'GET', args: [ 'test-4' ], code: 'MOVED' }

using this module not working.
I have found the module "Redis Cluster Client" (https://www.npmjs.com/package/redis-node-cluster), because before that I have not used so I parked it. 
The ruby programming language support has examples in https://github.com/antirez/redis-rb-cluster

**Comment by sam2x** [comment]
no news about this ? everyone who wants cluster feature needs to migrate to ioredis ?

**Comment by simontabor** [comment]
my earlier comment is still 100% relevant: https://github.com/NodeRedis/node_redis/issues/574#issuecomment-169081871. [redis-clustr](https://github.com/gosquared/redis-clustr) is stable and actively in-use with some pretty big clusters

**Comment by sam2x** [comment]
Ho great, it's a wrapper to this lib "It tries to be as unobtrusive as possible - mimicing the behaviour of the node_redis client.". Thanks @simontabor for the feedback

**Comment by Somebi** [comment]
Indeed, have to move to ioredis package because of this. Didn't knew this package is not supporting clustering. It's a fail... 
Why this is a recommended package?
Have to add a bold not in the read me. That this package is not supporting clusters feature. To stop confusing end users.

**Comment by thelinuxlich** [comment]
last update was almost a year ago so I think it's safe to say this library is deprecated.

**Comment by stockholmux** [comment]
@thelinuxlich nope. Not deprecated. We have updates that come from upstream (`redis-parser` and `redis-commands`) - it just doesn't show in this repo.

**Comment by Somebi** [comment]
Eventually i have migrated to ioredis and successfully integrated sharded cluster. Suggest using ioredis and this team to move to ioredis team, to help them if possible.

**Comment by naseemkullah** [comment]
As per https://redislabs.com/lp/node-js-redis/ 
> Node_redis’ support for the Cluster API is provided by an additional shim, redis-clustr.

https://github.com/gosquared/redis-clustr

**Comment by minhna** [comment]
it's 2020, almost 6 years since this issue opened. Hopefully there will be good news.

**Comment by thelinuxlich** [comment]
6 years ago I switched to ioredis for the cluster support

**Comment by aayushmall** [comment]
Any update on Cluster support on this?

**Comment by fcheong3b** [comment]
Any update for cluster support?
