### ISSUE TITLE
Create first party TypeScript definitions 

### ISSUE THREAD

**Issue by czechboy0** [redis/node-redis#727]
Hey, it would be great if first party TypeScript definitions could be created. The ones out there are usually wrong or incomplete. This is where they'd go: https://github.com/borisyankov/DefinitelyTyped

**Comment by BridgeAR** [comment]
This is not likely to happen. It would be best if you could write them and open a PR.

**Comment by BridgeAR** [comment]
I'm not a fan of TypeScript but to make live easier for everyone that uses it, I reconsidered your request. 

I would be very fond of a pull request for the current state (maybe even with a built tool that checks and implements the newest commands? :smile: ).

**Comment by sdiaz** [comment]
Hello, you can find the typings contributed at this moment at

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redis

**Comment by jpike88** [comment]
Please pull the typings into this project, it's easy to maintain them

**Comment by Salakar** [comment]
Having first party support for a TypeScript definition file is planned now, this will get added soon, I've got a few other issues to get through first though, thanks

**Comment by ciaranashton** [comment]
Any updates on this?

**Comment by vanakema** [comment]
Another bump for an update if possible :)

**Comment by regnaio** [comment]
Thanks for looking into this!
