### ISSUE TITLE
If client is in a reconnecting state, commands (set, get, etc...) never call their handlers, exhausting the commands queue 

### ISSUE THREAD

**Issue by lxe** [redis/node-redis#932]
Here's an example of a perpetually-retrying redis client:

``` javascript
var client = require('redis').createClient({
  port: 12345 // Deliberately bad port
  max_attempts: 0, // Keep attempting forever
});

client.on('error', function (err) {
  console.error('Error listener called:', err);
});

client.set('key', 'value', function (err) {
  // Should call the set handler (but it never does)
  console.error('Set failed:', err);
});
```

The handler to `client.set` will never get called, as long as the client is in the state of perpetual reconnection attempts.

I think it would make more sense if we receive `ECONNREFUSED` and attempt to reconnect, all commands in the queue should also fail. otherwise we run into some `offline_queue` exhaustion issues like this:

``` javascript
// An http server, 
require('http').createServer(function (req, res) {

  client.set('key', 'value', function (err) {
    // Should actually call this (but it doesn't)
    // The client hangs, as redis attempts to reconnect
    if (err) return res.end(err.message);
    res.end('OK');
  });
});
```

If you make a large number of requests to this server, even if we respond to the client outside the redis command handler, you can see that both `offline_queue` and `mem.rss` will grow indefinitely until we crash. This has a potential for DDOS and other bad things.

One way to remedy this, is to not set `max_attempts` to 0, but something more sustainable, like 5. This way, the offline command queue resolves, and the handlers get called with an error. In this case however, the client will never attempt to reconnect again, leaving itself in `CONNECTION_BROKEN` state.

I think we should resolve the offline command queue, and call command handlers with `ECONNREFUSED` errors, even if we attempt to reconnect indefinitely.

**Comment by ganemone** [comment]
+1 - this is a huge issue for applications that want to degrade gracefully during redis failures.

**Comment by freeqaz** [comment]
This would be a huge help to fix. Redis failures are rare, but they are valid edge case for high-availability services.

+1

**Comment by BridgeAR** [comment]
I thought about adding a specific timeout for each command but this is not really working, since commands that could have altered a state in the meanwhile would be ignored and other commands would fire if the server gets back.
Another solution might be to add a maximum limit of elements that may be added to the offline_queue and reject all following ones after that amount has been reached. But what if a few commands take way more space than lots of small ones?

What you want right now is to deactivate the offline_queue as this is almost the same as rejecting on ECONNREFUSED.

**Comment by BridgeAR** [comment]
@lxe what do you think about adding a option to set the maximum memory footprint the offline queue may grow to and after reaching that point either flush all commands that are in the queue or unshift elements until the memory is below that point again? The later is a bit dangerous in my opinion as there might be other commands in the offline queue relying on the result of the flushed command.

Ping @NodeRedis/contributors

**Comment by stockholmux** [comment]
I'd vote for keeping this mostly in application code, if possible. Different situations might require different behaviors; that can be decided by the programmer, not the library. Perhaps I'm missing something but why can't something like this solve the problem at the app level:

```
var client = require('redis').createClient({
  port: 12345, // Deliberately bad port
  max_attempts: 0, // Keep attempting forever
});

client.on('error', function (err) {
  console.error('Error listener called:', err);
  if (client.offline_queue.length > 3) {
    client.flush_and_error(new Error('Redis connection not connecting right now'))
  }
  console.log('client',client.offline_queue);
});
setInterval(function() {
  var
    ts = new Date().getTime();
  client.set('key', 'value', function (err) {
    // Should call the set handler
    console.error(ts, 'Set failed:', err);
  });
},500);
```

Of course, if crazy amounts of activity occurs between retry attempts, the memory footprint could still be a problem. Another option to handle this type of problem could be an event that is triggered by the `offline_queue.length` exceeding a size threshold.

**Comment by leibale** [comment]
see `disableOfflineQueue` and `commandsQueueMaxLength` [here](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md).
