### ISSUE TITLE
Reconnecting when maxclients is reached

### ISSUE THREAD

**Issue by cody-greene** [redis/node-redis#959]
Exponential backoff should be used when the server has reach `maxclients`. Currently, once a server has reached the `maxclients` threshold the client will be spammed with error events every 200ms:

```
Ready check failed: ERR max number of clients reached
Redis connection to 192.168.99.100:6379 failed - read ECONNRESET
```

Due to the way redis-server handles this config option (connect -> immediately return error -> close) the client doesn't get a chance to _backoff_ on its reconnection attempts like it would when the connection is simply refused. So it just reconnects every `client.retry_delay`.

**Comment by BridgeAR** [comment]
@cody-greene redis allows lots of connections at the same time and I wonder why you use so many^^.

But it is a valid point that this is inconvenient. I'm just wondering if there is a nicer solution. Checking the error and keeping that info even after connecting properly again is not all that nice (but I can't think of a better one just of out my head right now either).

Please also feel free to open a PR for this.

**Comment by BridgeAR** [comment]
I thought about it again and I'm actually thinking about not retrying in case of this error at all. That way the user can handle it.

This has the following advantages: 

1. If another client attempts to connect in addition to the already failed one after a short period of time and there is space again Redis can handle everything properly right away.
2. The backoff would only reduce the returned errors over time and the user would still be spammed in the beginning and depending on how the app works, this would not be resolved at any point of time. By not reconnecting at all this is completely resolved.
3. The user probably knows best what to do in such a situation.
4. node_redis does not need another state

What do you all think about that? @cody-greene @NodeRedis/contributors @dirkbonhomme

**Comment by dirkbonhomme** [comment]
Agreed. Retrying with backoff will just postpone the errors.

**Comment by cody-greene** [comment]
That sounds great, but what would be the best way for a user to detect this has happened? 
- listen for the `end` event (differentiate from `redis.quit()` or `redis.end()` somehow)
- listen for the `error` event and match against `err.message`

**Comment by BridgeAR** [comment]
I think emitting an error is the best way in this case. In addition to the error message I'd also add a error code like e.g. `NR_CLIENTS_EXCEEDED` (I hate coming up with names. If you can think of a better one, I'm very open for suggestions :laughing:).

**Comment by cody-greene** [comment]
awesome 👍

**Comment by cody-greene** [comment]
Looking back on what prompted me to open this issue: This only happens, in practice, due to some a application error like creating a new connection on each iteration of a loop or something equally rediculous. So it's best to just stop the client myself. It would still be nice to have a specific `err.code` for this though.
```javascript
const redis = require('redis')
  .createClient(process.env.REDIS_URL, {
    enableOfflineQueue: false,
    retryStrategy: opt => expBackoff(1e3, 30e3, opt.attempt)
  })
  .on('connect', function () {
    console.log('redis connected')
  })
  .on('reconnecting', function (info) {
    if (info.attempt === 1) {
      console.log('redis lost connection')
    }
  })
  .on('warning', function (msg) {
    console.log('redis ' + msg)
  })
  .on('error', function (err) {
    stdlog.error('redis ' + err.toString())
    // would rather check for err.code === 'NR_CLIENTS_EXCEEDED'
    if (err.message.indexOf('max number of clients reached') !== -1) {
      console.log('redis connection closed')
      this.end(true) // stop the retry strategy
      // should kill the app too, probably
    }
  })
```
